### ISSUE TITLE
Geeklog User Submission Email missing Link to Profile

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1000]
The profile link is missing from the Geeklog User Submission email for some reason. See example below:

```
Username: ExampleName
Email: example@mail.com
Reg. Date: Wednesday, November 20 2019 @ 04:50 pm EST

Profile 


------------------------------

End of Message

------------------------------
```

**Comment by eSilverStrike** [comment]
This issue affects any of our emails that have links in brackets like <>

This includes user, comment,article, etc.. submissions

From issue #430 and changeset 9f5346da058772dba0938a7c8fd3875f16ac7e1a

Issue seems to be gl text class and function removeAllHTMLTagsAndAttributes

It strips all html tags including bad tags which I think is what it considers our link to be ie

`<http://www.example.com/users.php?mode=profile&uid=62>`

There for set removeAllHTMLTagsAndAttributes to leave bad html tags alone

**Comment by eSilverStrike** [comment]
@mystralkk is there any reason that you know of why the links Geeklog has in notification emails like for user and comment submissions have to have the brackets < > around them?

My last fix just turned those brackets into html entities and now this below happens 

```
Username: test
Email: test@test.com
Reg. Date: Tuesday, November 26 2019 @ 11:27 am EST

Profile &lt;https://www.geeklog.net/users.php?mode=profile&amp;uid=19461&gt;
```

I know the From and To email addresses get surrounded by < > but that is in the header so it doesn't go through all our filtering like the message body does.

if there is no reason I will switch my last commit back and update all the email notifications in core that include a hardcoded link in the message body and remove the brackets < >. 

This may affect some third party Geeklog plugins if they followed a similar template for notificaitons but they will just have to fix their own code I guess.

Is this the best route to go by removing the brackets < > around links in the email message body or do you have a better idea?

**Comment by mystralkk** [comment]
I have no idea why <> are included in notification email.  Removing the brackets < > around links in the email message body seems reasonable to me.

**Comment by eSilverStrike** [comment]
Done

**Comment by eSilverStrike** [comment]
Opening as a reminder to test when Beta 3 live and on Geeklog.net that the notification emails with  urls and variables, that the  "&" in the urls don't get converted to html entities

**Comment by eSilverStrike** [comment]
@mystralkk I have done a bunch more tests using the demo mode and Geeklog.net (which is using Beta 2) to receive actual emails

Currently as it sits now all bad tags will remove and for some reason in htmlLawed it looks like links that are by themselves like: 

https://www.geeklog.net/users.php?mode=newpwd&amp;uid=121&amp;rid=0c92920ad4d05475

have their “&” next variable names get converted to HTML Entities (though I don’t see this happen in demo mode when the email is displayed to us on the page which is a bit weird).

Do you know a way of stopping this from happening via htmlLawed ?

I looked through the docs and don’t see a way but maybe I missed something

www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm

Do we just need to run htmlspecialchars_decode after GLText::removeAllHTMLTagsAndAttributes is run in the mail class to fix this issue?

Also I did add a feature request for the next version of geeklog (#1003) to support HTML emails for things like email notifications since our conversion to plaintext only really handles paragraphs and page breaks so a lot of these type of emails don’t get converted very well.

**Comment by eSilverStrike** [comment]
hhmmm I ran a quick test on geeklog.net and added

`$text = htmlspecialchars_decode($text); `

in the function GLText::removeAllHTMLTagsAndAttributes

It didn't fix the problem with the urls in the emails. 

It looks like the change happens after GLText::removeAllHTMLTagsAndAttributes is called in the mail class...

Does the mail class (I don't see where) or swiftmail convert html special characters instead sometime after GLText::removeAllHTMLTagsAndAttributes is called?

But then again **when I removed GLText::removeAllHTMLTagsAndAttributes from being called with my previous tests**, this problem doesn't happen....

This is very confusing to debug. Maybe you will have better luck?

**Comment by eSilverStrike** [comment]
hmmm I ran a quick test on geeklog.net and added:
`$text = htmlspecialchars_decode($text); `
in the function GLText::removeAllHTMLTagsAndAttributes

It did fix the problem with the urls in the emails. Do you see any potential problems with this fix or is there a way by using htmlLawed?

**Comment by mystralkk** [comment]
If "&amp;amp;" is converted into "&", it may not cause much trouble, but if "&amp;lt;" is converted into "<", it is very risky.  So I would not use htmlspecialcahrs_decode but would do it manually like:
```PHP
$text = str_replace(
    ['&amp;', '&quot;', '&apos;', '&#039;'],
    ['&', '"', "'", "'"],
    $text
);
```

**Comment by eSilverStrike** [comment]
The emails are sent as plain text so anything stored as entities when converted back should be displayed as text. 

The problem we are having is that the $message sent to com_mail should already be completely filtered as depending on what is being sent (ie straight notification text emails with no user generated content or emails with the actual comment or article text in it) depends on how it is filtered.

For example a comment about actual HTML entities could have html entities codes in the example surrounded by the code html tag. With our current filtering this all gets stripped away. Things will never look perfectly in these emails if the html tags use css classes but I am wondering if **I make your small change now just to be on the safe side and I leave the rest of this issue for #1003 (add html emails option) and Geeklog 2.2.2 (just so we can get Beta 3 released)**

I can update #1003 to include the feature that all emails sent by Geeklog should use a standard filter (either a new class or added to the GL Text class?) with a few different settings depending on what is being sent. Right now for example the comment submission notification and article submission notification have their own code to deal with striping away html tags and prepping the article or comment text for sending via email. This way if the text is being converted we can do things in a standardized way and if the text is being converted from html to plain text we can even do a few more things to make it look better than just stripping all html tags (like adding \n for <br> tags and </p> tags, etc…)

We can also do this so com_mail is backwards compatible and can filter content still if for example a flag is not set when the function is called then we know that whatever called com_mail didn’t most likely filter the message  properly and it can do the filtering we already have in place.

@mystralkk What do you think?

**Comment by mystralkk** [comment]
What I wanted to say is GLText::removeAllHTMLTagsAndAttributes may be used by someone who doesn't exactly know how it works.  You and I know the output of this method shouldn't be used in HTML document, but others may not know.  So I don't think it is a good idea to put htmlspecialchars_decode **INSIDE** the GLText::removeAllHTMLTagsAndAttributes method.  So, I would suggest removing htmlspecialchars_decode from GLText::removeAllHTMLTagsAndAttributes and adding htmlspecialchars_decode after calling this method.

**Comment by mystralkk** [comment]
That said, I noticed that the GLText::removeAllHTMLTagsAndAttributes method is called twice while sending a plain text email in COM_mail (line 3841) and Geeklog\Mail::send(line 163), the latter of which is called from within the former.

**Comment by eSilverStrike** [comment]
Sounds good. I had actually committed something earlier for this but forgot to push it so I reverted my change and let your fix stay.

Do you like my idea above of developing a standard way of filtering all emails for Geeklog v2.2.2. I did update #1003 to include this feature request.
