### ISSUE TITLE
User Image Names not always compatible with OS

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1002]
Geeklog.net I believe uses a Linux enviroment while my development server is Windows.

While migrating the Geeklog.net database on my windows machine by using the install, I got this message in the error log

`18/11/2019 10:41:00 - 192.168.0.190 - Migration notice: The image "::Ben.jpg" listed in the "users" table could not be found in C:/wamp64/www/geeklogtest/public_html/images/userphotos/  `

The reason for this is that the file could not copy over when I initially did it because windows files cannot have colons : in their filenames.

When Geeklog adds a userphoto to the database (or any photos like articles) we should make sure the file name is good for both Linux and Windows (so just alpha numeric letters).

**Comment by mystralkk** [comment]
Fixed with change set 9fea562
