### ISSUE TITLE
Sessions - Remember Me User Time is ignored

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1006]
The "Remember Me For" time (user option cookietimeout) does not work since the autologin keys are stored in the session table and those records get deleted when actual sessions expire which is set to a default of 2 hours.

Just as a reminder, before the new session handler we use to store the user Id and password using 2 cookies called the permanent cookie and password cookie and never used autologin keys so we need to figure how to handle this new situation. This permanent cookies only lasted as long as the remember me was set for when it was created. If the user came back these cookies were not updated so by the end of the remember me period when the user initially logged in, they would have to log in again.

Now we store a random key only. These keys last up to a month (Remember Me For) so they need to be stored for as long as the user has set to be remembered. If the user uses the site again within the remember me period do we update the start time for the autokey?

Users need to be remembered if the log into the site from different devices/browsers so multiple auto login keys can be generated.

**Comment by eSilverStrike** [comment]
@mystralkk - I will finish this one up since you mentioned you are busy. I will probably start this on Monday. I think the easiest route to go  is to create a separate table instead of trying to use the sessions table. I will call the new table "userautologin" and include the columns

sess_id, uid, autologin_key, expire_time

I am going to try to make this work like before where Remember me if set for a month will only last for the month and then the user will be required to relogin again. 

The other option is whenever the user logs in either the normal way or via the autologin key, the key expiry date gets extended by whatever the remember me value is.

**Comment by eSilverStrike** [comment]
Okay last commit added
- Autologin Keys stored as a hash in DB using password encryption settings (except salt)
- Autologin keys now are kept until expired for each individual users remember me setting.
- All Autologin keys for user are now deleted on password, email, and remember me setting changed

**Comment by eSilverStrike** [comment]
@mystralkk - Currently every time  a user loads a page the autologin key expiry gets extended by the remember me value. I think we should change this to work like before so the auto login key expiry_date for the session never gets extended. This way it would force the user to log in every week if remember me is set to 1 week. Does this sound good?

**Comment by mystralkk** [comment]
Sounds good to me.

**Comment by eSilverStrike** [comment]
Oops didn't mean to close it just yet as it needs a bit more testing. @mystralkk I think this is done but as you know it is fairly complex. I plan on retesting everything again probably tomorrow when my mind is fresh. If you have time can you double check things? 

Since there have been a number of changes since the Beta 3 release I think we should release a Beta 4 just in case.

BTW, the Last commit fixed:

- Added min and max range for session timeout config option so admin user cannot create a session timeout that is to short (min timeout possible is now 5 minutes)
- Autologin expiry now includes session timeout so it can never be lower than session timeout
- User Settings page includes a tooltip now better explaining how “Remember Me For” works
- Autologin Key expiry once set does not change. This is for better security as it will force a manual login at some point (as long as the session gets to expire due to inactivity from the user)
- If cookie does not match stored hash then new cookie key and hash generated which keeps same expiry as old hash

Also fixes for issues created because we don’t delete expired sessions and autologin keys on every page load for all users (because it is expensive to run), ONLY on when a  new session is actually created. This could cause issues for websites that don’t get many new visitors but only existing users, especially if they keep visiting the website before their session expires due to inactivity. This means SESS_sessionCheck now checks if current session found for user along with key if expired or not which results in a little bit of extra overhead on each page load.

**Comment by mystralkk** [comment]
I did some tests and it seems to work fine.

**Comment by eSilverStrike** [comment]
Okay everything looks good.
