### ISSUE TITLE
Add ability to Create A Geeklog Upgrade Package from Phing

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1009]
The install package using Phing to create the install distribution tarball.

It would be nice if we could automatically create an upgrade package to include just the change files. (plus any required readme files and the install directory)

We should also maybe include a list of removed files as well so the webmaster knows what should be deleted.

It could use the same settings found in build.properties to set the previous and current Git hash tag to create the upgrade for.

The upgrade package also should be renamed from what the regular install file name like 

geeklog-2.2.1.tar.gz 

to something that includes the version number upgrading from like

geeklog-2.2.0-to-2.2.1.tar.gz

We could launch this command like:

phing.bat dist-upgrade

**Comment by eSilverStrike** [comment]
Removed file list added with change set 411dea822983713053dede265084910afa5c2227

**Comment by mystralkk** [comment]
Implemented with change set 20e610c

**Comment by eSilverStrike** [comment]
Nice, this will be a great feature.
