### ISSUE TITLE
CKEditor Toolbar Incorrect in Article and Comment Editor

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1024]
After commit 0051762747469f6c9f0faa9b095b7e849f752720 Advanced Editor CKEdtitor toolbar setting doesn't work in Article Editor. Comment editor displays all toolbar buttons instead of just a simple toolbar.

**Comment by mystralkk** [comment]
Fixed with change set 58f8348.  I mistakenly overwritten "config.js".
