### ISSUE TITLE
Language Synch Problems with Returns in language string

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1028]
Notice when I did a language synch on the current repository that there is an issue with the install language files. Seems to be replacing variables and comments it doesn't have to and there is an issue with control linefeeds.

For example here is part of the Japanese synch (notice the \n)

```
    'charactersets' => "以下に示すのは、Geeklogがインストール時にサポートする言語の文字セットと対応するデータベースの文字セット、推奨するデータベースの照合順序です。文字セットとデータベースの文字セット/照合順序に関する詳しい情報は、<a href=\"/docs/english/install.html\">Geeklogインストールドキュメント</a>をご覧ください。
\n    <div class=\"uk-overflow-auto\">
\n    <table class=\"uk-table uk-table-striped\">
\n        <thead>
\n            <tr>
\n                <th>言語</th><th>サイトの文字セット</th><th>MySQLの文字セット</th><th>MySQLの照合順序</th><th>PostgreSQLの文字セット</th><th>PostgreSQLの照合順序</th>
\n            </tr>
\n        </thead>
\n        <tbody>
```

I also notice (this has been happening for a while) that all dates on the language files get changed even if the file has no changes. It would be nice if this only happened on files that actually have changes. Not sure if we can prevent this with the way the synch currently works (though I don't remember this happening before)

**Comment by mystralkk** [comment]
Fixed with change set aab6de2
