### ISSUE TITLE
[Bugs] Missing interface based mechanism to move data, sql, system etc. directories.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#103]
**Reported by nsaaman on 20 Apr 2008 18:44**

**Description:**
After a successful installation the security check tells us that the existence of certain directories like data, sql etc. in publicly accessible folders may lead to security issues and hence should be moved to safer place. It will be great if we can do this shifting by the interface itself. I mean we do all the configuration through interface in GL 1.5, which is great, why leave this ?

[Mantis Bugtracker #612](http://project.geeklog.net/tracking/view.php?id=612)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 20 Apr 2008 19:07**

The &quot;shifting&quot; will have to be done by the user during the upload.

We should, however, look into the possibility of doing some of the recommendations (make config files non-writable, delete install directory) in Geeklog / in the install script.

Not in 1.5.0, though. We need to get this release out in time for the start of the SoC coding period.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
