### ISSUE TITLE
[Feature Requests] Admin list "Users in group ..." always includes Root users

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#104]
**Reported by dhaun on 22 Apr 2008 08:46**

**Description:**
The list "Users in group ..." is somewhat confusing as it always lists all the users with access to the group in question, i.e. it includes users in the Root group.

Since this is sometimes what you want (to see who has access to an object owned by a certain group) and sometimes isn't what you want (to see who has been assigned to a group but is not a Root user), there should be an option to filter Root users.

[Mantis Bugtracker #613](http://project.geeklog.net/tracking/view.php?id=613)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
