### ISSUE TITLE
Update jQuery to the latest version

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1059]
As of Geeklog v2.2.1sr1 we are using jQuery 3.4.1. 

As of writting this issue jQuery is up to version 3.5.0

jQuery UI version is 1.12.1 (which is what Geeklog is currently using). Double check we have the latest version.

This means we need to check things that use jQuery like the Tabs and Help pop-up boxes.

**Comment by mystralkk** [comment]
Updated jQuery to v3.5.1 and UIkit3 to v3.4.6 respectively.  Seems to work fine.

**Comment by eSilverStrike** [comment]
Yeah tested the tabs, and Date popup box for the article, and the help popup box in the advanced search and it all worked.

**Comment by eSilverStrike** [comment]
Looking at this forum post:

https://www.geeklog.net/forum/viewtopic.php?showtopic=97291

from OMAL. He is having troubles with jQuery. I reopened this issue since I notice that we have an older jQuery (jquery.min.js) located in the public_html/javascript directory. We should delete this since we have it stored in the vendor directory now.

We also have an old copy of jquery ui in the directory as well public_html/javascript/jquery_ui. This should be removed since it is now located in the public_html/vendor directory. This directory also has some slider and timepicker addon files used by the articles. It looks like these files should be relocated. I don't know if the timepicker needs to be updated. I hope it working with the new verision of jquery and jquery ui.

**Comment by mystralkk** [comment]
Removed old jQuery and jQuery UI files under public_html/javascript/ and relocated their addons to public_html/vendor/jquery-ui/ with change set 2d85c4e.
