### ISSUE TITLE
Standardize the way the Anonymous Name is Retrieved and Set so Plugins can use it

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1069]
When an anonymous user leaves a comment, if they specify a name, a cookie is set to it can be retrieved again if they leave another comment and the name field gets auto filled. 

We should create a Plugin API to standardize the setting and retrieval of this cookie so plugins like the Forum can use it as well

**Comment by mystralkk** [comment]
Implemented with change set 95b01a0.  Now COM_getDisplayName() returns a user name taking into account $_COOKIE[$_CONF['cookie_anon_name']] in case of an anonymous user.

**Comment by eSilverStrike** [comment]
Found issue #1072 which was related to this feature request. Can't grab cookie for anonymous user name in COM_getDisplayName as it is used to retrieve name of records for other anonymous users and not just the current anonymous user. Plugins will just have to retrieve (and set) name in cookie the original way.

Updated forum plugin to do this. For example see: b53e7a9e4e9dfb80bfa38c241ff4af8c8050954b
