### ISSUE TITLE
Adding "iframe" to HTML Filtering Include config option doesn't allow user to set SRC attribute in content

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1078]
Adding iframe to HTML filtering config option works but when user sets the "src" attribute it gets filtered out. 

From the Geeklog Forum: https://www.geeklog.net/forum/viewtopic.php?showtopic=97346#97346

I thought there was a way to set attributes for a tag when added to the filter array but I don't see it in the code or remember how to do it. If there is then we should add this info to the docs.

Assume we need to fix this somewhere in HTMLawed class?

**Comment by mystralkk** [comment]
I succeeded in adding iframe tag with src attribute in the configuration.

<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/2015377/149085116-677f991a-b37f-4f15-80c7-716254d757c3.png">

**Comment by eSilverStrike** [comment]
Yup you are right. My mistake, I was thinking that the + just added a new tag not an attribute for that tag. (not sure why as it is kind of obvious)

Since myself and OMAL both missed it I will update the docs to better explain it,
