### ISSUE TITLE
Check Geeklog and Plugins compatibility with PHP 7.4 and PHP 8

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1079]
Haven't looked at 8 yet so not sure of the changes...

**Comment by eSilverStrike** [comment]
Webservices has some PHP warnings for PHP 7.3+

See forum post: https://www.geeklog.net/forum/viewtopic.php?showtopic=97380

When I try to edit or add a new story I get the following error, 

`A PHP error has occurred: (This text is only displayed to users in the group 'Root') E_WARNING(2) - "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? @ /home/system/lib-webservices.php line 577 `

**Comment by mystralkk** [comment]
> Webservices has some PHP warnings for PHP 7.3+
> 
> See forum post: https://www.geeklog.net/forum/viewtopic.php?showtopic=97380
> 
> When I try to edit or add a new story I get the following error,
> 
> `A PHP error has occurred: (This text is only displayed to users in the group 'Root') E_WARNING(2) - "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? @ /home/system/lib-webservices.php line 577 `

Fixed with change set e6a1e1f.

**Comment by eSilverStrike** [comment]
We will have to check the Geeklog install, upgrade and migrate processes as well to make sure they are compatible with PHP 7.4 and 8.

An install issue that seems to deal with PHP 8 was found. See #1087

**Comment by mystralkk** [comment]
Created a new repository for plugin information: https://github.com/Geeklog-Core/Plugin-Compatibility-List .

**Comment by mystralkk** [comment]
I have updated many of the plugins in https://github.com/Geeklog-Plugins to work with Geeklog 2.2.2 and PHP 8.1.  Are there any other plugins we would like to have work with Geeklog 2.2.2 and PHP 8.1?

**Comment by eSilverStrike** [comment]
Great! 👍 

All the plugins I have been releasing with Geeklog should have a repository in that list.

Did you double check the forum? I can't remember if I did but I do see it is marked as Yes in the compatibility list

https://github.com/Geeklog-Core/Plugin-Compatibility-List

**Comment by mystralkk** [comment]
I haven't fully checked the Forum yet with Geeklog 2.2.2 and PHP 8.1, but the plugin mostly seems to be working well.  I will look into it later.

**Comment by eSilverStrike** [comment]
It should be I was doing some work with it before I believe using PHP 8.0.

**Comment by mystralkk** [comment]
I changed a few places, and the plugin is working fine with PHP 8.1.
