### ISSUE TITLE
Geeklog Persian language

### ISSUE THREAD

**Issue by 2548ir** [Geeklog-Core/geeklog#1080]
Dear Geeklog Developers,

I am the author of Geeklog Persian language, please update your repository with my recent files:

[Geeklog-Persian.zip](https://github.com/Geeklog-Core/geeklog/files/5792965/Geeklog-Persian.zip)

Thanks for your awesome content management system

**Comment by eSilverStrike** [comment]
Thank-you.

We will add this to the next version of Geeklog.

**Comment by realmontazeri** [comment]
I appreciate if you remove the old incomplete translation files that called farsi_utf-8.php

Also here is Geeklog Persian official language repository and resources - https://github.com/realmontazeri/Geeklog-Persian

**Comment by eSilverStrike** [comment]
Sounds Good

**Comment by mystralkk** [comment]
Updated Persian language files (now renamed 'persian_utf-8.php') provided by Mahdi Montazeri with change set e9e060efe20f72d932eca107a0c4ce8a1a92844a.  Thanks!
