### ISSUE TITLE
WARNING with php8.0 + clean install

### ISSUE THREAD

**Issue by hirorongl** [Geeklog-Core/geeklog#1087]
apache 2.4.25 + php8.0.3 + Geeklog-Core2021/04/22(github)

Click Install All Plugins > 

E_WARNING(2) - Trying to access array offset on value of type null @ /var/www/example.com/private/gl2/system/lib-topic.php line 105

**Comment by hirorongl** [comment]
It seems that the installation of Geeklog is finished.
All plugins were not installed.

**Comment by hirorongl** [comment]
Extracted the URL of 500 error from access.log.
"GET /admin/install/index.php?mode=install&step=3&dbconfig_path=%2Fvar%2Fwww%2Fexample.com%2Fprivate%2Fgl2%2Fdb-config.php&install_plugins=false&language=japanese_utf-8&site_name=WkTeS%E3%83%86%E3%82%B9%E3%83%88SITE&site_slogan=WkTeS%E3%83%86%E3%82%B9%E3%83%88SITE&site_url=https%3A%2F%2Fexample.com&site_admin_url=https%3A%2F%2Fexample.com%2Fadmin&site_mail=admin%40example.com&noreply_mail=noreply%40example.com&utf8=true&innodb=true HTTP/2.0"

**Comment by hirorongl** [comment]
public_html\admin\install\classes\Install.php : function step3() line 305 require lib-common.php
`                    require str_replace('siteconfig.php', 'lib-common.php', Common::$env['siteconfig_path']);
`
public_html\lib-common.php : line 684
`    $_TOPICS = TOPIC_buildTree(TOPIC_ROOT, true);
`
$LANG27 value exists in lib-common.php
But $LANG27 doesn't exist in TOPIC_buildTree () in lib-topic.php
Similarly, $ GLOBALS ['LANG27'] has no value

**Comment by mystralkk** [comment]
Tried to fix this issue with change set d469668

**Comment by eSilverStrike** [comment]
Another report of PHP 8 not working with the installer. Was with a clean install I believe so I assume the fix above should fix it but I will add a link to it here just incase: [Geeklog Forum Post - Can't Install Geeklog](https://www.geeklog.net/forum/viewtopic.php?showtopic=97466)
