### ISSUE TITLE
envcheck.php error when phpinfo function is disabled

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1089]
Reported in the Geeklog Forum by spergol. See: 

https://www.geeklog.net/forum/viewtopic.php?showtopic=97408#97408

They get the following error when visiting the envcheck.php page:

```
E_WARNING(2) - phpinfo() has been disabled for security reasons @ /var/www/virtual//my_site/htdocs/admin/envcheck.php line 817
Call Stack
# Function File Line
1 phpinfo /var/www/virtual/my_site/htdocs/admin/envcheck.php 817
2 _phpinfo /var/www/virtual/my_site/htdocs/admin/envcheck.php 634
3 _checkEnvironment /var/www/virtual/my_site/htdocs/admin/envcheck.php 842
```

It looks like phpinfo has been disabled. The Hosting Environment Check page should check for this and disable the call to the function, disable the button to "Show/Hide Full PHP Info",  and include a message under "Current PHP Settings" that in order to view the current php settings they will have to contact their host and enable access to the phpinfo() function.

He also is reporting a double slash in the array returned by the root debug (see page element). We should look into this as well (maybe it is a setting issue on their website????):

```
array(1) {
["T"]=>
object(Template)#13 (17) {
["classname"]=>
string(8) "Template"
["debug"]=>
int(0)
["root":"Template":private]=>
array(1) {
[0]=>
string(58) "/var/www/virtual/my_site/htdocs/layout/denim/admin"
}
["file":"Template":private]=>
array(2) {
["page"]=>
string(81) "/var/www/virtual/my_site/data/layout_cache/english//denim__admin__envcheck.php"
["status"]=>
string(80) "/var/www/virtual/my_site/data/layout_cache/english/denim__admin__envcheck.php"
}
```

**Comment by mystralkk** [comment]
Fixed with change set 5c4e2d2.  As for the double slash, I cannot recreate it.Fixed with change set 5c4e2d2.  As for the double slash, I cannot recreate it.
