### ISSUE TITLE
Fixed a warning when stories goes to zero

### ISSUE THREAD

**Issue by hirorongl** [Geeklog-Core/geeklog#1096]
Fixed a warning when stories goes to zero

`E_WARNING(2) - Trying to access array offset on value of type bool @ /var/www/public_html/lib-common.php line 706
`

fix: line 706
`if (isset($_VARS['last_article_publish']) && isset($A['date']) && ($_VARS['last_article_publish'] != $A['date'])) {`

**Comment by eSilverStrike** [comment]
Can you quote us the line it is replacing just to make it easier to find and replace since the current development version line numbers will be different than the version you are using.

**Comment by hirorongl** [comment]
It is line 706 of lib-common.php of the contents pulled by github on 2021/09/15. Please see the image

![20210916144822](https://user-images.githubusercontent.com/3713620/133556728-6221412a-a094-4428-85ae-862ac53c3c27.png)

**Comment by eSilverStrike** [comment]
Thanks
