### ISSUE TITLE
Fix Themes included with Geeklog use of the H1 tag to better follow SEO Guidelines / Best Practices

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1106]
The H1 tag should be used for the page title as it helps Search Engines understand what the page is about.

This is consider best practice: https://ahrefs.com/blog/h1-tag/

Therefore the themes included with Geeklog, we should remove the H1 tag from around the website name in the Header and use the h1 tag for the page title (in most cases).

This may create some issues with pages that will have to be fixed with code changes (not just template changes) like with issue #1104

**Comment by mystralkk** [comment]
Related to issue #1104
