### ISSUE TITLE
Swiftmailer is abandoned - Replace with Symfony or another Library like PHPMailer

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1107]
Composer reports:
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.

https://swiftmailer.symfony.com/docs/introduction.html
Swift Mailer will stop being maintained at the end of November 2021.
Please, move to Symfony Mailer at your earliest convenience. Symfony Mailer is the next evolution of Swift Mailer. It provides the same features with support for modern PHP code and support for third-party providers.

**Comment by mystralkk** [comment]
Replaced SwiftMailer with PHPMailer in change set 38b470ee3475106dcb765b51bb213966dc451894
