### ISSUE TITLE
Drop readonly database tables (was:  Drop $_TABLES['dateformats'] table)

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#1112]
The $_TABLES['dateformats'] table is readonly, so it is meaningless to have the data as a database table.  I suggest making the table into an array of the Locale class.

**Comment by eSilverStrike** [comment]
Makes sense. I guess it was put in a table to allow plugins to add more date formats?? (just guessing or maybe it was more of a potential language thing)

How about $_TABLES['cookiecodes']? (any other tables?)

I don't think that one gets touched either and it should be faster to keep it in an array.

**Comment by mystralkk** [comment]
As far as I know, $_TABLES['dateformats'] is just read by MediaGallery, so no plugins including the Geeklog core write into the table.  I'll look into $_TABLES['cookiecodes'].

**Comment by mystralkk** [comment]
As for $_TABLES['cookiecodes'], this table is readonly, too.  I'll convert this one into an array.  By the way, what is the $_TABLES['maillist'] table for?  This one does not seem to be used anywhere...

**Comment by mystralkk** [comment]
Done with change set 020cee1e549991c72ff1165215441e3613e333fa.  Now, cookie codes can be obtained by calling COM_getCookieCodes().

**Comment by eSilverStrike** [comment]
> By the way, what is the $_TABLES['maillist'] table for? This one does not seem to be used anywhere...

Never noticed that one. Maybe at some point was used with the Daily Digest by the language used in the one record it has.

Definitely should be removed.

**Comment by mystralkk** [comment]
Done with change set 86d3a2cd7da17d549fc1261ac9c2a0419ddb4aa0
