### ISSUE TITLE
Geeklog Configuration displays and empty input box when in some cases it should be a 0 

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1114]
I was updating some Daily Digest config settings and I notice that the settings

 cron_schedule_interval, default_cache_time_block

found under the Miscellaneous tab was missing (text box was empty) when they should have been 0.

I couldn't save my settings until I updated  cron_schedule_interval, default_cache_time_block

Looks like if the config option is 0 it is not displayed. This was working in Geeklog 2.2.1sr1 so it must be a recent code change.

**Comment by mystralkk** [comment]
Fixed with change set 7ff806ef568250759e9a6d027f3ab0590b135d3f.  This bug seems to have gone unnoticed for some time, but has appeared with newer PHP versions.
