### ISSUE TITLE
Geeklog Configuration Errors when you delete all elements for a config option and then save

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1115]
For example on setting "Include Articles from these Topics" (news_sitemap_topics) if I delete all elements for this config array on save I will get the following error. Assume this happens with any similar config option (XMLSitemap has a few config options like this and so does the Calendar and Spam-X plugins)

>E_WARNING(2) - foreach() argument must be of type array|object, bool given @ C:\wamp64\www\geeklogdev\system\classes\config.class.php line 
1138

Call Stack
1 | _UI_get_change_block | C:\wamp64\www\geeklogdev\system\classes\config.class.php | 1095
2 | get_ui | C:\wamp64\www\geeklogdev\public_html\admin\configuration.php | 632

**Comment by mystralkk** [comment]
Fixed with change set e43f1c02d5bfa2d35524f6acb73961b9cb7321e8
