### ISSUE TITLE
Likes System - Add Top 10 Likes and Dislikes to User Profile

### ISSUE THREAD

**Issue by remyKobolski** [Geeklog-Core/geeklog#1120]
Geeklog gives a negative impression due to the huge amount of dislikes, especially on postings of gl developers.
My proposal:

- show only likes to anon users
- add number of likes to the user page
- add number of dislikes to the user page

Cause: don't let robots interfere with the content. At least gl features a spam detection.

**Comment by eSilverStrike** [comment]
That is the problem with allowing likes for anonymous users as bots will click these links. That is part of the reason why we have a likes speedlimit (so it can only happen every 45 seconds). Having the ban and gus plugin installed would also help as it will filter out bad behaving ips (at least those that match the defined rules).

Adding a like or dislike can also be enabled only for actual users if needed (still displays for anonymous).

Dislikes can also be disabled for different content types (so only Likes are allowed)

Allow only Likes for Anonymous users would create a similar problem but skewed the other way.

I like the idea of having Likes and Dislikes displayed on the user page.

We should also maybe have some sort of system that will allow Likes/Dislikes Cleanup incase there was a bunch of spam likes. This could be done for the entire system or the individual piece of content for the past X number of hours.

**Comment by eSilverStrike** [comment]
User profile page now displays list of last 10 items user liked or disliked.
