### ISSUE TITLE
Install of XML Sitemap Plugin Fails with PHP 8.1

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1124]
I get the following error in the install (or just by trying to install the plugin on the Plugins Admin page) for the XML Sitemap Plugin using PHP 8.1.

Not sure how to fix this one... @mystralkk do you have an idea?

E_DEPRECATED(8192) - Return type of HTTP_Request2::attach(SplObserver $observer) should either be compatible with SplSubject::attach(SplObserver $observer): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice @ C:\wamp64\www\geeklogdev\system\vendor\pear\http_request2\HTTP\Request2.php line 723

Call Stack
--

1 | include | C:\wamp64\www\geeklogdev\system\vendor\composer\ClassLoader.php | 571
2 | Composer\Autoload\includeFile | C:\wamp64\www\geeklogdev\system\vendor\composer\ClassLoader.php | 428
3 | loadClass | C:\wamp64\www\geeklogdev\plugins\xmlsitemap\xmlsitemap.class.php | 1137
4 | sendPing | C:\wamp64\www\geeklogdev\plugins\xmlsitemap\functions.inc | 399
5 | XMLSMAP_update | C:\wamp64\www\geeklogdev\plugins\xmlsitemap\autoinstall.php | 137
6 | plugin_postinstall_xmlsitemap | C:\wamp64\www\geeklogdev\public_html\admin\plugins.php | 1288
7 | plugin_do_autoinstall | C:\wamp64\www\geeklogdev\public_html\admin\plugins.php | 1057
8 | plugin_autoinstall | C:\wamp64\www\geeklogdev\public_html\admin\plugins.php | 1417

**Comment by mystralkk** [comment]
Updated all libraries, including PEAR libraries, via composer.  I hope this update will fix the issue.

**Comment by eSilverStrike** [comment]
Thanks .... it did. I thought I had updated all the libraries recently. I guess a new version was released.
