### ISSUE TITLE
Clairifying Geeklog Language Support for New Installs

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1125]
@mystralkk 
This is related to https://github.com/Geeklog-Plugins/messenger/issues/7

I believe this database I am using was originally Latin-1 which was updated to utf8mb4. I guess when I did this I didn't update the user language selection to be english-utf8 which is part of the messenger plugin issue but these settings should still really work okay I guess???

Also I know Geeklog still supports latin1 for older databases but on new installs we require a utf-8 DB charset right? I did a new install and wasn't asked about UTF-8. Not sure if it detected the database collation here are just assumed it...

The install docs (/public_html/docs/english/install.html) still says we ask if they want UTF-8

Quoted from doc
_During the install process you can indicate whether to use UTF-8 as the default character set for your site independent of the language you are using. This will set the database character set to UTF-8. If you have checked this setting, make sure your database collation is compatible with the character set (usually for MySQL this is either utf8_general_ci or, if you wish to support emojis utf8mb4_general_ci). Checking this will not change the collation of your database, this must be done manually before you proceed with the install. If you leave 'Use UTF-8' unchecked your installs default language selection character set will be used._
 End of quote

I think the install docs are mostly correct but we should better indicate what we support for a new Geeklog Install. Can a new install still support a db collation of latin1? (if so that is fine) or is a UTF-8 language required now?

Maybe it is just in the docs where it says "During the install process you can indicate whether to use UTF-8 as the default character set " that has me confused.... 

What should the install docs actually say here?

I see in db-config.dist and site-config.php.dist the charset still start off with the older default charset.

Sorry just a bit confused here during my testing of the install and that issue with the messenger plugin and just want to make sure the Geeklog Install docs are correct.

**Comment by mystralkk** [comment]
Since almost all MySQL servers used now support UTF-8, I believed requiring UTF-8 charset would not cause a big issue, so removed the "UTF-8" checkbox for fresh install.  However, I forgot to update the document.  Sorry to confuse you.  Should I update the document or reintroduce the "UTF-8" checkbox, @eSilverStrike ?

**Comment by eSilverStrike** [comment]
I agree we should require UTF-8 on new installs so the docs can just be updated.

If someone has done all the work of converting their database from latin1 to utf8 then they will have to manually update the Geeklog settings to use the new charset.

Issue #1129 would still need to be fixed though for those sites that have stayed on a different charset

**Comment by mystralkk** [comment]
Updated the docs with change set 97c3dd2abf04a466b6bb9e7475d1cd7efa3de36b.
