### ISSUE TITLE
On Geeklog Upgrade Language Configuration Option has incorrect selection

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1129]
Upgrading a Geeklog website that is using just english (not english_utf8), after upgraded the Language Configuration defaults to the first item in the list since English doesn't exist in the language dropdown (only english_utf8). 

Should this config language selection only show supported languages based on the db charset?

Also upgrading a site that has the language config set to english_utf8 gets reset to just english for some reason.

Also I notice that the language config option record stored in the DB default value is english. We should probably update that to english_utf8 and also update the docs.

Another question (which I think we did talk about) is for upgrades that the language file doesn't exist anymore what happens? It defaults to English UTF8 right (or just english if not utf8 charset???)?

**Comment by mystralkk** [comment]
> Upgrading a Geeklog website that is using just english (not english_utf8), after upgraded the Language Configuration defaults to the first item in the list since English doesn't exist in the language dropdown (only english_utf8).

> Should this config language selection only show supported languages based on the db charset?

The language files to be used for installation are Chinese, English, German, Hebrew and Japanese, but this doesn't mean other languages are not supported by Geeklog.

> Also upgrading a site that has the language config set to english_utf8 gets reset to just english for some reason.

> Also I notice that the language config option record stored in the DB default value is english. We should probably update that to english_utf8 and also update the docs.

I didn't know such a problem happens.  Of, course, this should be fixed.

> Another question (which I think we did talk about) is for upgrades that the language file doesn't exist anymore what happens? It defaults to English UTF8 right (or just english if not utf8 charset???)?

The default English is English, not English UTF-8.  I wanted to make it English UTF-8, but this would cause trouble for older plugins.

**Comment by mystralkk** [comment]
Fixed with change set 476f3776e0d76d00a61256aac09c2305e56f8dd1.
