### ISSUE TITLE
Geeklog Filemanager - PHP 8+ Issues - Config Value not Converted Properly

### ISSUE THREAD

**Issue by ramosgt** [Geeklog-Core/geeklog#1140]
I'm having problems uploading images with the filemanager, I've done:

<a href="https://ibb.co/FHzGNf0"><img src="https://i.ibb.co/VwTXrhQ/bug2.png" alt="bug2" border="0"></a>

1. Check directory permissions
2. Check size and type of files

I am using ubuntu server 22.04 with php8.1

I can, create folders, copy the existing images on the server to another folder using filemanager, but I can't upload new ones, I have enabled debug and all I can see is the following:

Server error.
A PHP error has occurred:
This is being displayed as "Root Debugging" is enabled in your Geeklog configuration.

If this is a production website you must disable this option once you have resolved any issues you are investigating.

E_DEPRECATED(8192) - Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice @ /home/ramos/VirtualHost/contraste/system/vendor/illuminate/container/Container.php line 1159
Call Stack

Additionally, I tried to enter geeklog.net to use the forum, but after entering the data the site shows up with an error.

<a href="https://ibb.co/YfXfxkJ"><img src="https://i.ibb.co/GC9Cq2G/bug.jpg" alt="bug" border="0"></a>

**Comment by eSilverStrike** [comment]
>> Additionally, I tried to enter geeklog.net to use the forum, but after entering the data the site shows up with an error.

I see this error in the error log.  The error log points to a missing language variable in the forum for non english languages. I have updated the other languages in the forum. Is it fixed?

Also, I am not sure what you mean in the quoted text above. Where you initially able to access Geeklog.net or did it always error out? What data did you enter?

Also where you logged in and what language are you using?

Thanks

**Comment by ramosgt** [comment]
Login from here:

https://www.geeklog.net/users.php

I'm not sure if I change the language to Spanish, my username is alb3rt

**Comment by eSilverStrike** [comment]
@ramosgt The geeklog.net issue should be fixed now. Found some other forum language variables that were not defined for other languages.

**Comment by eSilverStrike** [comment]
**BUG Found in File Manager Config**

[filemanager_upload_file_size_limit] Config Option says the value is in MIB and by default is set to 16.
When you attempt to upload it says the max file size is only 16 bytes so you need to change this value to 16000000 to get 16MiB. Need to fix this so 16 Mib means 16 MiB

**Comment by ramosgt** [comment]
> 
I made sure to define the size, I made sure the permissions. But it couldn't find the error since it doesn't give me more information, it just shows that the file could not be uploaded, I check the log of both geeklog and apache and I can't see anything.

**Comment by eSilverStrike** [comment]
Just checked File Manager works in PHP 7.x

It seems to have some issues in PHP 8.0 like uploads not working (but the file explorer seems okay)

In PHP 8.1 the File Explorer doesn't even load (if you have error_reporting set to -1).

This will be fixed in Geeklog 2.2.3

**Comment by mystralkk** [comment]
Sorry, this is my mistake.  Fixed with change set #bdf2a630a4f970fce7aea2d81e33f003343c17ca
