### ISSUE TITLE
[Feature Requests] Required visual cues in Calendar Plugin's Event Editor v1.5b1

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#126]
**Reported by nsaaman on 17 May 2008 18:00**

**Description:**
In the Event Editor page there is zero visual cue on the necessary fields like
Title, Time and Event description. Only after pressing Save, the user is informed 
of the error. Also, there is no Back button on the error page. 

Possible solutions exists like not migrating from the page and displaying the errors on the same page.
Also, an easier solution exists which is to define CSS classes named "required-fields" and "missing-fields" and use them appropriately to provide visual cues and feedback to the user.

[Mantis Bugtracker #635](http://project.geeklog.net/tracking/view.php?id=635)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 18 May 2008 20:27**

This isn&#039;t restricted to the Calendar but applies to all editor-type forms in Geeklog: There should be visible clues as to which fields are required.

A rare case where we do something like that (without any explanation, though): When sending a Trackback, e.g. via .../admin/trackback.php?mode=fresh, the labels of the required fields show up in bold.

This should be moved to a CSS class, though. But not in 1.5.0 ...

**Comment by mystralkk** [comment]
**Comment posted by jmucchiello on 21 May 2008 17:20**

You can add such classes to the style.css and then add the classes to the fields yourself. Doing so just means you&#039;ve created your own theme.

Dirk, surely you can add two empty styles to style.css so that everyone who sees this idea uses the same names for required-fields and optional-fields class names. Then in 1.5.1 actually modify GL to use those fields.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 22 May 2008 07:49**

.missing-field {
  /* reserved for future use */
}
.required-field {
  /* reserved for future use */
}

added to CVS now.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
