### ISSUE TITLE
[Feature Requests] Checking "All Day Event" field should freeze the End Event Time widgets v1.5b1

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#127]
**Reported by nsaaman on 17 May 2008 18:05**

**Description:**
In the Event Editor of Calendar the All Day Event checkbox is pretty handy. But,
it would be better if on checking this option the widgets for manipulation of End Event Time are freezed indicating that they aren't of any use in this scenario.

I guess a simple CSS solution will do the trick.

[Mantis Bugtracker #636](http://project.geeklog.net/tracking/view.php?id=636)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 18 May 2008 20:28**

Sounds more like a job for JavaScript (if you want it to change dynamically).

**Comment by mystralkk** [comment]
**Comment posted by jmucchiello on 23 Jun 2008 17:00**

Shouldn&#039;t an all day event freeze/hide both start and end Time fields?

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 23 Jun 2008 17:48**

Yep.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
