### ISSUE TITLE
[Bugs] Missing list of all personal events for a day

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#132]
**Reported by @dhaun on 22 May 2008 16:23**

**Version:** 1.5.0

**Description:**
The somewhat undocumented feature that calling up .../calendar/event.php without any parameters will list all of the events for the current day is missing a mode for personal events.

I.e. .../calendar/event.php?mode=personal should list all personal events for the current day. It currently only lists the site events.

**Additional Information:**
Somewhat related issue: In this "list today's personal events" mode, an edit icon is displayed for site events, even when the user does not have calendar.edit permissions. They can't actually edit the events, but the edit option shouldn't show up in the first place.

In 1.4.1, the edit link is actually missing the eid.

Note: For site events that the the user has added to their personal events, the edit option would be okay, as it would let them edit their personal copy of the site event.

[Mantis Bugtracker #641](http://project.geeklog.net/tracking/view.php?id=641)

**Comment by mystralkk** [comment]
**Comment posted by jmucchiello on 24 May 2008 08:10**

Note: For site events that the the user has added to their personal events, the edit option would be okay, as it would let them edit their personal copy of the site event.

My observation of the code says that users cannot modify personal copies of master events. It makes sense and it doesn&#039;t. Should the user be able to change the date? Probably not. Most likely he just have access to modify the description. But that&#039;s a bit weird to code.

My thought was to leave this as is. You can&#039;t modify master events in your personal calendar. Then whenever master events are modified, you update all personal copies of the same event to keep them in sync.

Unless there is a better behavior?

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
