### ISSUE TITLE
[Feature Requests] Functions to allow Expanded ACLs

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#162]
**Reported by jmucchiello on 26 Jun 2008 23:46**

**Version:** 1.5.0

**Description:**
Currently GL1 only supports three access levels: None, Read only and Full access. Part of this is a coding limitation. Assumptions in the code that 3 includes 2 and 1 doesn't exist abound. My proposal is to soften the edge of those assumptions with functions:

``` PHP
SEC_hasReadAccess($access)
{
    global $_CONF
    if ($_CONF['ACLs_oldstyle']) {
        return $access >= 2;
    }
    return ($access & 2) > 0;
}

SEC_hasWriteAccess($access)
{
    global $_CONF
    if ($_CONF['ACLs_oldstyle']) {
        return $access == 3;
    }
    return ($access & 1) > 0;
}
```

If the core used these kinds of functions throughout, additional bitflags could be added to the existing ACLs.

[Mantis Bugtracker #672](http://project.geeklog.net/tracking/view.php?id=672)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
