### ISSUE TITLE
[Feature Requests] Calender Event invitations

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#164]
**Reported by cchiapusio on 29 Jun 2008 15:30**

**Version:** Future

**Description:**
provide links in calendar events to send logged in user a 'meeting request' invitation so that they can be reminded of an event in their own PIM.

**Additional Information:**
May require separate links for Outlook, Google, and Yahoo style invites, though I'm not sure. You also might want to provide a dialog so the user can select how early before an event that the reminder should trigger. This would be valuable to people that sync PDAs to PIM. Come to think of it you may be able to just provide a 'download' link for a .ics file.

http://en.wikipedia.org/wiki/ICalendar
http://www.fileinfo.net/extension/ics

[Mantis Bugtracker #674](http://project.geeklog.net/tracking/view.php?id=674)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
