### ISSUE TITLE
[Feature Requests] Calendar Event Reminder Email

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#165]
**Reported by cchiapusio on 29 Jun 2008 15:33**

**Version:** Future

**Description:**
enable a user to request a reminder email for a calendar event.

**Additional Information:**
would require site has cron enabled to generate email reminders (possibly at a fixed 24 hours prior) of a pending calendar event

[Mantis Bugtracker #675](http://project.geeklog.net/tracking/view.php?id=675)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
