### ISSUE TITLE
[Feature Requests] Allowing UID as $_CONF['site_mail']

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#185]
**Reported by lwc on 31 Jul 2008 00:54**

**Version:** Future

**Description:**
It makes no sense to be forced to choose a manual e-mail address when 99% of the admins would choose an e-mail address that is already used by one of their users (usually themselves).

Which is why it would be great to use, for example:

``` PHP
$_CONF['site_mail'] = 2;
```

(in v1.5+ it would be set up through the GUI, of course).

Then all it takes is for lib-common.php to do this:

``` PHP
if (strpos($_CONF['site_mail'], '@') === false && is_numeric($_CONF['site_mail']) {
    $result = DB_query("SELECT email FROM {$_TABLES['users']} WHERE uid = {$_CONF['default_contact']}");
    if ($result) {
      $A = DB_fetchArray($result);
      $_CONF['site_mail'] = $A['email'];
    } else
      $_CONF['site_mail'] = $_CONF['noreply_mail'];
}
```

[Mantis Bugtracker #697](http://project.geeklog.net/tracking/view.php?id=697)

**Comment by mystralkk** [comment]
Related to #93

**Comment by eSilverStrike** [comment]
Not sure if this feature request is worth it. There will be problems when dealing with a large user list unless we limit to root users or something. Should we close this issue?

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
