### ISSUE TITLE
[Feature Requests] Separate DB read and write access

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#196]
**Reported by @dhaun on 14 Aug 2008 10:25**

**Version:** Future

**Description:**
To improve performance on large sites, we should be looking into separating read and write access to the database. There are two aspects to this:

1) Mix of "static" and non-static fields in tables

Some tables contain both relatively static content and content that is updated frequently. E.g. the gl_stories table contains the "static" story text but also the view count that is updated every time the article is displayed.

Possible solution:
a) move data that is updated regularly into a separate table
b) if it's only view / hits counters, add an option to disable them

(First step: Have a separate function to update hit counters, similar to COM_hit)

2) Allow for the DB class to use separate DB connections for read and write access

This is only useful once you reach the level where having one database server is not enough. It's relatively easy to set up one master DB server for all write accesses that is then replicated to one or more slave DB servers that are read-only.

For calls like DB_delete, DB_getItem, etc. it's easy to figure out whether they're read or write. DB_query may need to look at the actual SQL request first.

[Mantis Bugtracker #708](http://project.geeklog.net/tracking/view.php?id=708)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
