### ISSUE TITLE
[Bugs] Using the browser's back button can cause confusion in multi-language setups

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#200]
**Reported by @dhaun on 27 Aug 2008 14:02**

**Version:** 1.5.0

**Description:**
When switching the language, then clicking the browser's Back button and selecting another link (from a language-aware list of links, see below), you end up with a page that displays the body text (e.g. an article) in one language and the navigation in another.

**Steps To Reproduce:**
Assuming a multi-lingual site with 2 or more languages, e.g. German and English:
1. start with German, go to a story, e.g. article.php/test_de
2. switch language to English (article.php/test_en is displayed)
3. click the browser's Back button (you're back at article.php/test_de)
4. select a language-aware link from the navigation

The last bit requires some explanation. Suppose you have a language-aware list of links to other articles. After hitting the Back button, you're back at the German article, so all those other links point to German articles.

Now when you click on one of those links, you end up with the German article text and an English navigation.

**Additional Information:**
Strictly speaking, this is not a bug: Switching the language will change the visitors language (to English, in the above example). After that, the visitor explicitly requests a page in German, so that's what we display.

It is, however, confusing for the average visitor.

[Mantis Bugtracker #712](http://project.geeklog.net/tracking/view.php?id=712)

**Comment by eSilverStrike** [comment]
Just checked and this seems to have been fixed at some point. Language aware links reflect the url the person is on along with what is displayed in the Switch Language Block even if you hit the back button on the browser.
