### ISSUE TITLE
[Feature Requests] Select cookie duration time with a drop down menu when logging in?

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#209]
**Reported by hallomarkus on 30 Aug 2008 13:03**

**Version:** Future

**Description:**
There had been a feature request for "stay logged-in for ever" when logging in. We had discussed that this was not possible but that it would be good to be able to choose the cookie duration time with a drop down menu.

The simple machines forum has such a log-in field with drop down menu for the length of the cookie time: http://www.simplemachines.org/about/

[Mantis Bugtracker #721](http://project.geeklog.net/tracking/view.php?id=721)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
