### ISSUE TITLE
[Bugs] Calendar does not use date formatting as set in configuration panel

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#223]
**Reported by euan on 13 Sep 2008 02:14**

**Version:** 1.5.1

**Description:**
When viewing an event in the calendar plugin, the date format is incorrect in Japanese at least, and appears not use any date formats as set in the configuration panel.

Screenshot attached: year does not have suffix character for year. Order in Japanese would probably be %Y %m instead of %m %Y.

**Additional Information:**
Because use of pre-formatted date strings returns (I believe) JIS characters, which become corrupted when displaying in UTF8, it would be best to have the format of these strings controlled from the administration interface.

[Mantis Bugtracker #735](http://project.geeklog.net/tracking/view.php?id=735)

![date-issue](https://cloud.githubusercontent.com/assets/2015377/12320948/e400380c-baee-11e5-9f8a-8001f54ad026.jpg)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
