### ISSUE TITLE
[Bugs] Advanced editor: cannot save story with images

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#227]
**Reported by euan on 16 Sep 2008 07:44**

**Version:** 1.5.1

**Description:**
On upgrading a site from 1.4.1 to 1.5.1rc1, it is not possible to edit stories with images using the advanced editor.
1. On editing a pre-existing story, although images appear in the advanced editor
2. on saving, an error message appears on save stating that images were not used.
3. The entry is not saved.

**Additional Information:**
Error appears in both Safari and Camino on OSX 10.5.5.

[Mantis Bugtracker #739](http://project.geeklog.net/tracking/view.php?id=739)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
