### ISSUE TITLE
[Patches] Allow users to enter a password on the registration page

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#228]
**Reported by euan on 16 Sep 2008 10:45**

**Version:** 1.5.2

**Description:**
When registering, users are now required to enter a username and email address.
A randomly-generated password is then sent to their email address.

Administrators should be able to select an alternative registration form, on which new users enter a username, email address and password, which is then stored immediately. An optional activation link can then be sent to the user's email address.

**Additional Information:**
This would make it much easier for non-computer savvy users to register on Geeklog sites, and would be more in line with current registration processes on many other sites.
The current system is a hurdle that some users find too difficult to understand.

[Mantis Bugtracker #740](http://project.geeklog.net/tracking/view.php?id=740)

[geeklog.tar.gz](https://github.com/Geeklog-Core/geeklog/files/90167/geeklog.tar.gz)
[wso-users.zip](https://github.com/Geeklog-Core/geeklog/files/90168/wso-users.zip)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
