### ISSUE TITLE
[Feature Requests] Turn on / off static pages information separately per page

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#235]
**Reported by hallomarkus on 27 Sep 2008 19:02**

**Version:** 1.5.1

**Description:**
the information about a static page can only be turned on an off centrally for all static pages. Instead there schould be a switch for each single page.
Turn on / off static pages information

http://www.geeklog.net/forum/viewtopic.php?showtopic=84453

[Mantis Bugtracker #747](http://project.geeklog.net/tracking/view.php?id=747)

**Comment by eSilverStrike** [comment]
Hits and dates can be turned on or off per page now as of Geeklog v2.1.2.
