### ISSUE TITLE
[Bugs] Events and event submission form accessible when Calendar set to "login required"

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#240]
**Reported by @dhaun on 1 Oct 2008 21:05**

**Version:** 1.5.1

**Description:**
It appears that events are visible (e.g. in Upcoming Events block) and accessible (when you know the URL, e.g. via Upcoming Events) even when the Calendar is set to "login required". Access to the actual Calendar is properly blocked. This doesn't seem to make sense.

Additionally, you can get to the event submission form from the event's page.

**Steps To Reproduce:**
1. Create an event for the current day
2. Configuration > Calendar > Login Required: True
3. log out

**Additional Information:**
Credit: Reported by JuJuBee on IRC.

[Mantis Bugtracker #752](http://project.geeklog.net/tracking/view.php?id=752)

**Comment by mystralkk** [comment]
**Comment posted by jujubee on 1 Oct 2008 21:15**

I am using this (going to ) for a boy scout troop.  Having some events public (intended for potential recruits) and some private (members only) is a great thing.  I like allowing Passers-By to be able to see the Anonymous (Read Only) events.  Trying to encourage others to join.  But protecting posts/events with login is great security since most of our members are minors.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 17 Jan 2009 08:48**

So this started out as a bug report but turned into half a feature request. Since we&#039;re going to have to change the current behavior one way or another anyway, I&#039;d like to push this to the next major release (1.6) instead of addressing it in a minor release (1.5.2).

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 18 Apr 2009 21:00**

*sigh*

Still not sure how to handle this and we need to release 1.6.0 ASAP. Pushing this back into the Future (again).

**Comment by mystralkk** [comment]
**Comment posted by Roccivic on 8 Nov 2010 00:02**

I wonder if this was addressed in the new calendar plugin.

**Comment by eSilverStrike** [comment]
Lets confirm if this is still an issue or not in 2.2.0

**Comment by mystralkk** [comment]
Fixed with change set 6ba635c.
