### ISSUE TITLE
[Feature Requests] Give Topics an option to show or hide from front page

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#252]
**Reported by samstone on 17 Oct 2008 14:20**

**Version:** Future

**Description:**
I think it will be very useful to have a checkbox (on the Topic management page) to led a topic show or hide from the front page. Currently we can do so by individual story, or by setting the default configuration to make all stories appear on the front page or not. However, I find the need to assign stories of certain topics not to appear on the front page at all. I hope it make sense.

[Mantis Bugtracker #764](http://project.geeklog.net/tracking/view.php?id=764)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 17 Oct 2008 14:33**

Good idea - I had a need for this feature myself on occasion.

The only problem is that in the Admin&#039;s story editor, you only select the topic while you&#039;re already in the editor, i.e. we would need some JavaScript magic to change the &quot;Show only in topic&quot; dropdown when you switch topics.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
