### ISSUE TITLE
[Bugs] Lots of "text-align:left" in style.css

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#253]
**Reported by lwc on 17 Oct 2008 18:24**

**Version:** 1.5.1

**Description:**
There are lots of "text-align:left" in public_html/layout/professional/style.css - for example, in the TH element.

It makes RTL pages look bad.

[Mantis Bugtracker #765](http://project.geeklog.net/tracking/view.php?id=765)

**Comment by mystralkk** [comment]
**Comment posted by lwc on 17 Oct 2008 18:25**

In the title of this report, I meant style.css and not styles.css, of course. Can you fix that?

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
