### ISSUE TITLE
[Feature Requests] Allow objects to respect owner (root) read permission

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#260]
**Reported by cordiste (@hostellerie) on 12 Nov 2008 12:10**

**Version:** 1.5.1

**Description:**
As discussed in http://www.geeklog.net/forum/viewtopic.php?showtopic=85221 s it would be a nice feature if in the config we can choose if we want roots always see objects or not.

[Mantis Bugtracker #772](http://project.geeklog.net/tracking/view.php?id=772)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
