### ISSUE TITLE
[Feature Requests] RSS feeds that take into account access rights

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#267]
**Reported by scubasteve on 4 Dec 2008 20:48**

**Description:**
It would be cool to have RSS feeds display any content you want but also take into account access rights for the respective content. This would allow you to have any content displayed in an RSS feed, but require authentication depending on what the content is.

**Additional Information:**
I have my site set completely private and you have to be logged in to view content. I do however have a need to RSS feeds to show for instance story titles but still require authentication to actually read them.

[Mantis Bugtracker #780](http://project.geeklog.net/tracking/view.php?id=780)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 17 Jan 2009 08:56**

Currently, feeds are simply files on the webserver - that&#039;s why they only contain content accessible to anonymous users.

For access control, we would need to create the feeds dynamically, i.e. route things through a .php script.

Need to check how other systems are doing this, e.g. we probably don&#039;t want the user&#039;s password as a part of the URL ...

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 6 Mar 2010 14:48**

Also see http://wiki.geeklog.net/index.php/SoC_dynamic_feeds

**Comment by eSilverStrike** [comment]
Not sure if this is worth doing. Should we close the issue?

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
