### ISSUE TITLE
[Feature Requests] Don`t allow users to change settings in "Exclude Topics and Authors" and "Show & hide boxes"

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#274]
**Reported by hallomarkus on 16 Dec 2008 15:48**

**Version:** 1.5.1

**Description:**
The areas "Exclude Topics and Authors" and "Show & hide boxes" of the user`s account settings may both lead to misunderstandings. It would be great if the admin could take them off the changeable settings of a user.

In other words don`t allow users to change any settings there.

http://geeklog.info/forum/viewtopic.php?showtopic=6968

[Mantis Bugtracker #787](http://project.geeklog.net/tracking/view.php?id=787)

**Comment by eSilverStrike** [comment]
Related to #988

**Comment by mystralkk** [comment]
Finished removing unnecessary settings and tables with change set 69320eae987525ca4de90dbd4eb10089a0642d5c
