### ISSUE TITLE
[Bugs] A fix for when unserialize goes wrong

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#282]
**Reported by lwc on 1 Jan 2009 23:28**

**Version:** 1.5.1

**Description:**
I've installed Geeklog in a host in which unserialize returns false for various $_CONF values, without saying why. After lots of agonizing testings, I've managed to fix it by changing:

geeklog/system/classes/config.class.php

``` PHP
                    $value = @unserialize($row[1]);
```

to

``` PHP
                    $row[1] = preg_replace('!s:(\d+):"(.*?)";!e', "'s:'.strlen('$2').':\"$2\";'", $row[1]);
                    $value = @unserialize($row[1]); 
```

The preg_replace solution was invented by some genious in php.net/unserialize

Other solutions that were offered there didn't work for me.

**Additional Information:**
This patch seems to have fixed everything for me, although I'm sure there are other unserialize commands out there in Geeklog. Maybe this specific one is just more susceptible to problems, I don't know.

The point is Geeklog may just doesn't work without it. More importantly, it doesn't seem to cause any problems where it's not needed. In other words, it only has advantages so please apply it.

[Mantis Bugtracker #795](http://project.geeklog.net/tracking/view.php?id=795)

[Unserialization failed on.zip](https://github.com/Geeklog-Core/geeklog/files/89647/Unserialization.failed.on.zip)

**Comment by mystralkk** [comment]
**Comment posted by lwc on 3 Jan 2009 11:04**

The same file also needs this fix in function _get_extended. So to sum up, here are the 2 changes in the entire file:

Change 1:

// custom code - start
                    $row[1] = preg_replace(&#039;!s:(\d+):&quot;(.*?)&quot;;!e&#039;, &quot;&#039;s:&#039;.strlen(&#039;$2&#039;).&#039;:\&quot;$2\&quot;;&#039;&quot;, $row[1]);
// custom code - end
                    $value = @unserialize($row[1]);

Change 2:

// custom code - start
            $cur[4] = preg_replace(&#039;!s:(\d+):&quot;(.*?)&quot;;!e&#039;, &quot;&#039;s:&#039;.strlen(&#039;$2&#039;).&#039;:\&quot;$2\&quot;;&#039;&quot;, $cur[4]);
// custom code - end
            $res[$cur[3]][$cur[0]] =

(don&#039;t worry, the usage of $cur[4]) is part of what&#039;s after that &quot;=&quot;).

**Comment by mystralkk** [comment]
**Comment posted by jmucchiello on 5 Jan 2009 01:03**

Technically, this will not work if there is a &quot; in the string as the strlen will report the wrong length. However, I doubt that will be important on the strings where this kind of error occurs -- paths and urls.

**Comment by mystralkk** [comment]
**Comment posted by lwc on 25 Mar 2010 20:56**

Any chance to implement this? Without these only 2 lines some sites simply can&#039;t run Geeklog.

**Comment by mystralkk** [comment]
**Comment posted by mstefanro on 9 Apr 2010 18:50**

What you have discovered is probably a bug in Geeklog, caused mainly by the fact that the configuration data is not properly inserted into the database. Due to this fact, the unserialization process can fail on the retrieved data, most likely because of the incorrect escaping (i.e. escaping the serialized string twice before insertion can cause this). However, what you have provided above is far from a solution and can cause more trouble than it solves, thus I strongly advise against applying it. What that regular expression pattern you have shown above does is to assume that strings never contain any double-quotes followed by a semi-colon and modify the serialized thing based upon that. Obviously, this cannot be relied on:
&gt;&gt;&gt; $v = serialize(&#039;hello&quot;;world&#039;); /* serialize the string hello&quot;;world */
&gt;&gt;&gt; print $v;
s:12:&quot;hello&quot;;world&quot;;
&gt;&gt;&gt; print unserialize($v); /* unserializing it back obviously works fine */
hello&quot;;world
&gt;&gt;&gt; print var_dump( unserialize( preg_replace(&#039;!s:(\d+):&quot;(.*?)&quot;;!e&#039;, &quot;&#039;s:&#039;.strlen(&#039;$2&#039;).&#039;:\&quot;$2\&quot;;&#039;&quot;, $v) ) ); /* unserializing after applying the regex pattern breaks the initial string */
string(5) &quot;hello&quot;

Can you please provide us with more debugging information so we can reproduce the error?
Try removing your regex pattern (preg_replace) and after the line &quot;$value = @unserialize($row[1]);&quot; add:
if ($value === false) { echo &quot;Unserialization failed on: &quot;;var_dump($row[1]); echo &#039;\nRow is: &#039;; var_dump($row); }

I will analyze the code and try to come up with a fix in the meantime.

**Comment by mystralkk** [comment]
**Comment posted by lwc on 9 Apr 2010 20:43**

You only addressed the first occurence of unserialize, but I uploaded the results.

**Comment by mystralkk** [comment]
**Comment posted by mstefanro on 9 Apr 2010 21:02**

I see. Well, the problem is definitely not because of unserialize. As you can see, the string: s:36:&quot;http://mydomain.com&quot;;
appears in your configuration table, which is clearly incorrect. The 36 is supposed to mean the size of the string that was serialized, which in this case is &quot;http://mydomain.com&quot; of only 19 characters (unless you have altered it before posting). This means that the problem has occurred whenever the string $_CONF[&#039;site_url&#039;] has been changed.
It is hard to imagine how this could have happened. Have you tried to directly modify the string in the database? Have you executed any SQL queries on the configuration table yourself or used a SQL Browser to change information in the configuration table?
If not, do you think that you can reproduce this error using a freshly installed copy of geeklog?

**Comment by mystralkk** [comment]
**Comment posted by lwc on 9 Apr 2010 23:07**

Sorry, I thought it&#039;s obvious I removed my private details. If you look at any general details, you&#039;d see the count is fine. It&#039;s unserialize that goes wrong.

**Comment by mystralkk** [comment]
**Comment posted by mstefanro on 9 Apr 2010 23:17**

I&#039;m sorry, but I don&#039;t see the count being fine for any of the strings:
string(35) &quot;s:39:&quot;Multilingual FAQ management&quot;;&quot; // incorrect
string(16) &quot;s:14:&quot;MultiFAQ&quot;;&quot; // incorrect
You might be mistakenly looking at the number between the braces of string, i.e. string(XX). Those are obviously correct, they were generated by var_dump. However, the numbers you are supposed to look after are those inside the vardumped string, i.e. s:XX:&quot;...&quot;;
Obviously MultiFAQ does not have 14 characters and Multilingual FAQ management does not have 39 characters (unless you have replaced those too, in which case you have replaced all of them and the uploaded file would be of no use).
If you haven&#039;t replaced e.g. MultiFAQ, then the count in its serialization is wrong. I&#039;m thinking of the unlikely case of different encoding usage issue. Do you think you can list some steps towards reproducing this bug by starting with a fresh copy of geeklog?
I tend to think that someone has incorrectly made changes directly into the database which have caused this problem.

**Comment by mystralkk** [comment]
**Comment posted by jmucchiello on 10 Apr 2010 01:26**

lwc, what is the encoding of your conf_values table? Is it UTF-8 or some other code page?

**Comment by mystralkk** [comment]
**Comment posted by lwc on 10 Apr 2010 08:16**

I&#039;ve replaced just personal things (url and path), which means you may be on to something with the wrong count. Is it just MultiFAQ though?

I use UTF-8 for everything.

**Comment by mystralkk** [comment]
**Comment posted by mstefanro on 10 Apr 2010 22:57**

No, it&#039;s for all the strings that have appeared in the file. The script only shows them in the file if the count is wrong. Even if you replace &quot;mydomain.com&quot; with the original string, the count will still be wrong.
Please answer to the two question I&#039;ve asked initially:
1) Have you worked directly with the database? (i.e. executing SQL queries or using some kind of database manager to modify it)
2) Do you think you can reproduce this error on a newly installed geeklog?

**Comment by mystralkk** [comment]
**Comment posted by lwc on 7 Oct 2012 16:57**

Oops, sorry:

1) No.
2) No, because the relevant host eventually started supporting the unserialize command.

I just know my patch saved the day back when that host didn&#039;t support unserialize.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
