### ISSUE TITLE
[Feature Requests] Identify e-mail messages sent through the contact form

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#296]
**Reported by lwc on 3 Feb 2009 10:46**

**Version:** 1.5.1

**Description:**
One way to identify them would be to include the referrer URL (at least as a X-header).

Another way is to make the sender realize they are not just any e-mail messages but ones from their contact form. In other words, something like "subject: [example.com] {subject}".

But maybe a better (less spacious) approach is to put the site's no-reply address as FROM and the sender's address as REPLY-TO.

[Mantis Bugtracker #809](http://project.geeklog.net/tracking/view.php?id=809)

**Comment by mystralkk** [comment]
Related to #295

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 4 Feb 2009 15:55**

That certainly makes more sense than bug #0000808 ...

Maybe add a footer / signature?

**Comment by mystralkk** [comment]
**Comment posted by lwc on 5 Feb 2009 09:16**

No, because that&#039;s only after you already open the message. Why not FROM/REPLY-TO?

And what about the referrer?

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 5 Sep 2009 19:32**

How about:

  Subject: [Site Name] Actual Subject

I don&#039;t see a use for the referrer since it would always be the contact page&#039;s URL.

**Comment by mystralkk** [comment]
**Comment posted by lwc on 6 Sep 2009 07:33**

No way, [Site Name] could be a whole line by itself. I think FROM/REPLY-TO is the way to go.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 6 Sep 2009 09:42**

The Reply-To: is not a good idea. It hides the sender&#039;s email address (most email clients will only display the From: address by default).

I see two possible useful options:

- add a signature (see comment 0000514)
- add the site name in the subject (see comment 0000937)

Pick one ...

**Comment by mystralkk** [comment]
**Comment posted by lwc on 6 Sep 2009 13:42**

Well, that&#039;s the whole idea. That&#039;s how you&#039;ll know it came from the site. I bet most users wouldn&#039;t think twice about clicking reply even though it came from the site. The admin could also tell in advance it&#039;s ok to just press reply.

But whatever the solution is, I really hope to notice it before opening the message. If anything, I prefer site&#039;s url over site&#039;s name. Site URLs are much more likely to be short enough not to hide the rest of the subject. Especially if you took off the protocol and www (if www is used). Google the phrase &quot;powered by geeklog&quot; -site:geeklog.net and you&#039;ll see what I mean.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 6 Sep 2009 15:02**

I don&#039;t understand the reasoning: The idea of a contact form is to, well, get into contact. Why would you want to make it any harder / more complicated to reply to such a request for contact?

I do get the occasional odd email were only careful examination of the email headers reveals that it was sent through the contact form on one of my websites. I can therefore understand the wish to make it more obvious where such an email is coming from.

Personally, I would prefer a signature, as that wouldn&#039;t mess with the headers and subject when replying. But I guess people are sort of used to seeing [words-in-square-brackets] in email subjects by now.

**Comment by mystralkk** [comment]
**Comment posted by lwc on 6 Sep 2009 15:29**

I just think one needs to be aware that a message actually came from a site and not directly from a person. One reason could be measuring the success of your site&#039;s forms. Another could be to separate the original message from replies (if there&#039;s a communication problem between servers, at least you&#039;d know the arrival of the original message proves nothing). There are probably even more reasons. For example, some users may like to use filters to send site form&#039;s messages into a special folder (or in Gmail&#039;s lingo: tag them).

I say to either make it site&#039;s URL (without protocol and www) or signature. I prefer the former, but the latter would still be cool.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
