### ISSUE TITLE
[Feature Requests] Options on cancelling edit of an item

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#297]
**Reported by euan on 6 Feb 2009 03:00**

**Version:** 1.5.1

**Description:**
When cancelling an edit, the user is sent back to the main admin screen of the plugin or stories etc.

I would like to have a config option to send the user back to either the top page, the admin screen, the plugin public page, or the plugin admin page, or the public page of the item that was being edited (if relevant). This is particularly useful for novice users, who get confused when they don't recognise their surroundings.

**Additional Information:**
I implement this with one plugin as follows:

in the plugin admin/index.php:

``` PHP
} else { // 'cancel' or no mode at all
    if ($_NE_CONF['aftercancel'] == 'plugin') {
        $display = COM_refresh($_CONF['site_url'] . '/news/index.php');
    } else if ($_NE_CONF['aftercancel'] == 'admin') {
        $display = COM_refresh($_CONF['site_admin_url'] . '/moderation.php');
    } else if ($_NE_CONF['aftercancel'] == 'home') {
        $display = COM_refresh($_CONF['site_url']);
    } else {
        $display .= COM_siteHeader ('menu', $LANG_BL_ADMIN[11]);
        if (isset ($_REQUEST['msg'])) {
            $msg = COM_applyFilter ($_REQUEST['msg'], true);
            if ($msg > 0) {
                $display .= COM_showMessage ($msg, 'blog');
            }
        }
        $display .= list_news();
        $display .= COM_siteFooter ();
    }
}
```

with config options in install_defaults.php:

``` PHP
/** What to show after a News item edit has been cancelled? Possible choices:
 * 'list' -> display the admin-list of Blog
 * 'plugin' -> display the public homepage of the Blog plugin
 * 'home' -> display the site homepage
 * 'admin' -> display the site admin homepage
 */
$_NE_DEFAULT['aftercancel'] = 'list';

        $c->add('aftercancel', $_BL_DEFAULT['aftercancel'], 'select',
                0, 1, 10, 130, true, 'news');

language strings:

    'aftercancel' => 'After cancelling edit',

    10 => array('Display Admin List' => 'list', 'Display Public List' => 'plugin', 'Display Home' => 'home', 'Display Admin' => 'admin'),
```

And that's it.

This solution requires however that the link to the admin screen in moderation.php is altered with a ?mode=list or something - otherwise, you will shut everyone out of the admin screen totally when not redirecting there.

[Mantis Bugtracker #810](http://project.geeklog.net/tracking/view.php?id=810)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 6 Feb 2009 09:18**

&quot;Cancel&quot; is a button like any other, so I&#039;m sure we can recognize when it has been clicked. That would get rid of the need of adding ?mode=list for the default case.

Also, would it make sense to use the &quot;aftersave&quot; option for cancel, too?

**Comment by mystralkk** [comment]
**Comment posted by euan on 6 Feb 2009 12:14**

I can imagine wanting to go to the item saved &quot;aftersave&quot;, and perhaps the admin list &quot;aftercancel&quot;. So I think they need to be separate settings.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
