### ISSUE TITLE
[Feature Requests] Display mode of block

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#300]
**Reported by @ivywe on 9 Feb 2009 08:30**

**Version:** 1.5.1

**Description:**
I want [display mode of block]

Now
 pulldown: all/Homepage only/each topics ...

after
 pulldown: all/Homepage only/each topics .../outside Homepage/match string/
 text input: match string[ ]

Then we can display block flexibly.

If [/staticpages/abc] is set in match string text area, the block displayd in only /staticpage/abc??? pages.

[Mantis Bugtracker #813](http://project.geeklog.net/tracking/view.php?id=813)

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 4 Mar 2009 12:51**

This is not so important.
I think better to use autotags plugin.
ex)
[addstaticpage:string1 string2]
 string1: included string
 string2: staticpage id

function phpautotags_addstaticpage($p1, $p2, $fulltag)
{
    $display =&#039;&#039;;
    $pageurl = $_SERVER[&quot;REQUEST_URI&quot;];

    if( strpos($pageurl, $p1) !== FALSE ){
        $display .= CUSTOM_getStaticpage( $p2 ); //display staticpage content
    }
    return $display;
}

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 5 Sep 2009 19:20**

I can see where this is aiming at - sometimes you want to display a block on a specific page, but the Topic dropdown is not flexible enough.

However, I don&#039;t like the suggested interface. Isn&#039;t this something that could be solved with the Dynamic Blocks API? And then maybe create a plugin for that?

see http://wiki.geeklog.net/index.php/Dynamic_Blocks

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 6 Sep 2009 03:16**

Thank you for your suggestion.

But I want to control blocks per one staticpage.
I should create plugin for that?

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
