### ISSUE TITLE
[Feature Requests] Mentioning the license of template.class.php

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#301]
**Reported by lwc on 14 Apr 2010 07:20**

**Version:** 1.7.0b1

[Mantis Bugtracker #1128](http://project.geeklog.net/tracking/view.php?id=1128)

**Comment by mystralkk** [comment]
**Comment posted by nj on 17 Apr 2010 18:05**

Added a patch with the LGPL V2 license as the header to template.class.php

**Comment by mystralkk** [comment]
**Comment posted by lwc on 17 Apr 2010 21:20**

1) You&#039;ve ended up accidentally mentioning GPL instead of LGPL.
2) As much as I like the words &quot;or later&quot;, they don&#039;t exist in the original package. But do double check it, because it would be better with those words.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 5 Sep 2010 08:48**

The COPYING file from PHPLIB does say LGPLv2 &quot;or any later version&quot;, so that should be fine, see http://phplib.cvs.sourceforge.net/viewvc/phplib/php-lib/

Geeklog&#039;s readme already states that the template engine is from PHPLIB.

Given that we modified the code quite a bit by now, I think we should adopt the template engine. I.e. drop the current header (which lists all sorts of changes that are of no interest since they&#039;ve _always_ been part of Geeklog). Instead, use a proper LGPLv2 header, acknowledge the original authors and where it came from and add the names of our contributors.

The header&#039;s been in the current state for the past 10 years now, so I think it can easily wait for another release - pushing this to 1.8.0.

**Comment by mystralkk** [comment]
**Comment posted by lwc on 5 Sep 2010 22:33**

No, COPYING - as the name implies - is just a copy of the full license. Like it says, each file is supposed to have a notice with either a &quot;this file uses license X&quot; or &quot;this file uses license X or later&quot; statement. But PHPLIB has neither.

And please don&#039;t forget 1).

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 6 Sep 2010 05:55**

What do you mean by &quot;No&quot;? In the absence of licensing information in the actual file, the COPYING file is the next best reference for the intended license.

In other words: PHPLIB was obviously released under the LGPLv2 (with the &quot;or any later version&quot; addition). Our (to-be-done) updated header in template.class.php should say just that.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 1 Nov 2010 15:54**

Done.

@nj: Sorry, I didn&#039;t use your patch.

**Comment by nj** [comment]
@mystralkk Wrong person, as I'm not the same nj as in your bugtracker.

**Comment by mystralkk** [comment]
Sorry, @nj.  I imported issues from MantisBT and there happened to be a person with the same name as yours.
