### ISSUE TITLE
[Patches] In Story Editor to create New Story, under the Archive Options, cannot deselect Auto Delete radio button once selected

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#303]
**Reported by nj on 17 Apr 2010 18:17**

**Version:** 1.6.1

**Description:**
In the Story Editor to create New Story, under the Archive Options there is the Enable checkbox and the Auto Delete radio button. Once I enable the checkbox, and then if I click the Auto Delete radio, I cannot then deselect the Auto Delete radio button, without Unchecking the Enable checkbox.

[Mantis Bugtracker #1131](http://project.geeklog.net/tracking/view.php?id=1131)

**Comment by mystralkk** [comment]
Related to #294

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 21 Apr 2010 18:12**

You can uncheck the &quot;Enabled&quot; checkbox and it will also disable the auto delete (though not the radio button).

I agree, the UI could be improved here. &quot;Auto Delete&quot; is a radio button since there can also be an &quot;Auto Archive&quot; option - but that will only show up if you have defined an Archive topic. So I guess in this case Auto Delete should be a checkbox.

**Comment by mystralkk** [comment]
**Comment posted by erisco on 22 Apr 2010 02:43**

The patch I attached will now present the Auto Delete option as a checkbox if no archive topic exists.

A template file was modified to make this change.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
