### ISSUE TITLE
[Patches] In Story Editor, the Enabled word before the check box is confusing - removing it would make things clearer

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#304]
**Reported by nj on 17 Apr 2010 18:33**

**Version:** 1.6.1

**Description:**
In the story editor, the Enabled checkbox comes in 2 occasions:
1. Archive Options: Option: Enabled: [checkbox]
2. Disable Comments: Enabled: [checkbox]

IMHO, it would be clearer if the Enabled word was removed in 2 and Options:Enabled is removed in 1. Thus these would look like:
1. Archive Options: [checkbox]
2. Disable Comments: [checkbox]

I think this is much more understandable.

[Mantis Bugtracker #1132](http://project.geeklog.net/tracking/view.php?id=1132)

**Comment by mystralkk** [comment]
**Comment posted by nj on 17 Apr 2010 18:46**

Attached patch which removes Option: Enabled and Enabled in 1 and 2 above. Looks a bit less confusing, but maybe that is just me and I&#039;m usually easily confused.
Anyways, still haven&#039;t figured out a way to get rid of the &#039;:&#039;

**Comment by mystralkk** [comment]
**Comment posted by erisco on 17 Apr 2010 19:32**

There is no patch attached =O

**Comment by mystralkk** [comment]
**Comment posted by nj on 18 Apr 2010 05:40**

Oops. Sorry - patch attached

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
