### ISSUE TITLE
[Patches] Adding comment_limit to the comment toolbar

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#305]
**Reported by lwc on 18 Apr 2010 14:05**

**Version:** 1.7.0b1

**Description:**
Currently comment_limit is only a GUI option, and the toolbar just contains 
comment_mode and commentorder. But if all three are in user settings, maybe all three should be in the toolbar.

[Mantis Bugtracker #1133](http://project.geeklog.net/tracking/view.php?id=1133)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 21 Apr 2010 18:32**

Hmm. I&#039;m a bit worried about making the UI more confusing.

Users can change that setting under My Account. How often have you had the need to change it temporarily?

**Comment by mystralkk** [comment]
**Comment posted by lwc on 21 Apr 2010 22:28**

To anonymous users it&#039;s temporarily or nothing.

**Comment by mystralkk** [comment]
**Comment posted by erisco on 22 Apr 2010 02:19**

The patch I attached should resolve this issue.

I had to modify a template file. There are a couple B/C API changes too.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 16 Jan 2011 16:46**

Still not convinced that this is a good idea. But somebody could try out the patch and report back ...

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
