### ISSUE TITLE
[Feature Requests] RTL/LTR selection box for all post modes' textareas

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#308]
**Reported by lwc on 19 Apr 2010 16:24**

**Version:** 1.7.0b1

**Description:**
Now that all post modes, including FCKEditor (0000175), start in the default direction, it would be awesome to be able to change that during writing and only during writing.

While 0001136 deals with hardcoding the content's direction, this ticket deals with cases when you just want easier editing without hardcoding anything. Since the direction is not saved here anyway, it would also support text mode.

Here's how to do it:

Add this to the PHP:

``` PHP
$changedirection_ltr = $LANG2?[??]; // Left to right
$changedirection_rtl = $LANG2?[??]; // Right to left
$...templates->set_var('changedirection_mode1', $LANG_DIRECTION);
if ($LANG_DIRECTION=='ltr') {
    $...templates->set_var('changedirection_text1', $changedirection_ltr);
    $...templates->set_var('changedirection_text2', $changedirection_rtl);
    $...templates->set_var('changedirection_mode2', 'rtl');
} else {
    $...templates->set_var('changedirection_text1', $changedirection_rtl);
    $...templates->set_var('changedirection_text2', $changedirection_ltr);
    $...templates->set_var('changedirection_mode2', 'ltr');
}
```

Add this to the templates:

``` HTML
<input type="button" value="{changedirection_text1}" onclick="changedirection('changedirection_mode1', new Array('introtext', 'bodytext'))" {XHTML}>
<input type="button" value="{changedirection_text2}" onclick="changedirection('changedirection_mode2', new Array('introtext', 'bodytext'))" {XHTML}>
```

Add this to the JS:

``` JAVASCRIPT
function changedirection(command, fields) {
  for (i in fields)
    if (document.getElementById(fields[i]).style.direction == "" || document.getElementById(fields[i]).style.direction != command)
      document.getElementById(fields[i]).style.direction = command
}
```

**Additional Information:**
You could make it work just in multilingual sites, but it also helps those that use different languages in one story, etc.

[Mantis Bugtracker #1137](http://project.geeklog.net/tracking/view.php?id=1137)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
