### ISSUE TITLE
[Feature Requests] admin_block at Configuration Manager

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#309]
**Reported by @tsuchi000 on 20 Apr 2010 06:54**

**Version:** 1.7.0b1

**Description:**
My request is admin_block at Configuration Manager

For example

config.class.php

``` PHP
    function get_ui($grp, $sg='0', $change_result=null)
        :
        $display = COM_siteHeader('none', $LANG_CONFIG['title']);

        $blocks[]= ('admin_block');
        $display = COM_siteHeader(array('custom_showBlocks',$blocks), $LANG_CONFIG['title']);
```
# I'm sorry in my poor English

[Mantis Bugtracker #1138](http://project.geeklog.net/tracking/view.php?id=1138)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 21 Apr 2010 18:41**

Sorry, I don&#039;t understand this request (or the code). Can you try to clarify, please?

**Comment by mystralkk** [comment]
**Comment posted by kobab on 22 Apr 2010 05:25**

Wish admin block (admin menu) appears on configuration manager, upper or lower or elsewhere is OK. This is her request.

Current status is link to admin menu alone appears on configuration manager. I also have some experience like; after changing configuration and check its result of a staticpage, and if failed go back to configuration and change values again, and wish to check its effect at an staticpage..again and again... at such case, I wondered if admin block appears at configuration manager, less click step helps me a lot.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
