### ISSUE TITLE
[Feature Requests] Configration - story: add mode Enable for Login Required Message

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#319]
**Reported by @ivywe on 7 May 2010 07:16**

**Version:** 1.7.0rc1

**Description:**
Configuration - story: add mode Enable for Login Required Message

example)
mail login required URL.

**Additional Information:**
Static Page Plugin can choose mode 'Enable for Login Required Message'.

Exit Type: Enable for Login Required Message. Leave unchecked for normal security check and message.

[Mantis Bugtracker #1150](http://project.geeklog.net/tracking/view.php?id=1150)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
