### ISSUE TITLE
[Feature Requests] The logo's width and height in header.thtml

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#321]
**Reported by lwc on 10 May 2010 09:53**

**Version:** 1.7.0

**Description:**
The Professional theme is dynamic. There is therefore no need to force the logo to be in a certain width and height. Please remove the width/height and accept any given logo. If it's too big or too small, let the admin worry about it.

Alternatively, put the width/height in the GUI. But that seems like an real overkill for something that should be automatic.

Thanks!

[Mantis Bugtracker #1152](http://project.geeklog.net/tracking/view.php?id=1152)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 10 May 2010 18:15**

I remember that it was a recommendation to always use width and height attributes so that the browser&#039;s rendering engine would know how much room to reserve for an image, even if it wasn&#039;t loaded yet. This was one of those tips to create more responsive websites. Not sure how relevant it still is these days, though.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
