### ISSUE TITLE
[Bugs] Year 2038 problem

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#322]
**Reported by @ivywe on 11 May 2010 04:02**

**Version:** 1.7.0

**Description:**
Year 2038 problem
http://en.wikipedia.org/wiki/Year_2038_problem

[Mantis Bugtracker #1153](http://project.geeklog.net/tracking/view.php?id=1153)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
