### ISSUE TITLE
[Bugs] error on user.php page (openid)

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#328]
**Reported by urbn on 27 May 2010 04:14**

**Version:** 1.7.0

**Description:**
from error_log:

```
 2 - file_exists() [<a href='function.file-exists'>function.file-exists</a>]: open_basedir restriction in effect. File(../loginform_openid.thtml) is not wit$
Wed 26 May 2010 08:18:29 PM PDT - 
```

**Steps To Reproduce:**
1. Enable openid/facebook logins
2. Goto users.php?mode=logdiksadkfasdhsdhn
2. White page with an error message is displayed.

**Additional Information:**
To fix:

Edit system/lib-security.php. search for ../loginform_openid.shtml. Remove ../ and it works.

[Mantis Bugtracker #1160](http://project.geeklog.net/tracking/view.php?id=1160)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 30 May 2010 08:03**

The ../ is needed so that the OpenID login can be displayed on example.com/users.php

I see the problem, but we need some other solution.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 19 Jun 2011 15:50**

We could modify the filename() function in the template class such that it doesn&#039;t try to call file_exists(&quot;../loginform_openid.thtml&quot;) right away. Instead, if could first check for any &quot;..&quot; in the template file name and remove the corresponding number of directory levels from $this-&gt;root, concatenate the result and only then call file_exists(). Requires some fiddling but would be cleaner than the current way ...

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
