### ISSUE TITLE
[Bugs] COM_highlightQuery() set into alt tag

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#329]
**Reported by @ivywe on 28 May 2010 05:32**

**Version:** 1.7.0

**Description:**
COM_highlightQuery() replace searchword to <span class="highlight">searchword</span>

ex)

&lt;img alt="**&lt;span class="highlight"&gt;searchword&lt;/span&gt;**" src="/images/library/Image/**.png" /&gt;

[Mantis Bugtracker #1161](http://project.geeklog.net/tracking/view.php?id=1161)

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 13 Feb 2011 06:37**

If keyword is in &#039;alt&#039;, image is not displayed correctry.
ex)
http://www.geeklog.jp/article.php/lbi_seminar_20110225?query=%E4%BB%8A%E9%A7%92%E5%93%B2%E5%AD%90%E5%86%99%E7%9C%9F

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
