### ISSUE TITLE
[Feature Requests] staticpage manager: Wish to have ID column again.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#330]
**Reported by @ivywe on 28 May 2010 14:58**

**Version:** 1.7.0

**Description:**
At GL1.7.0, ID column was disappeared at staticpage manager.
Wish to have ID column again at 1.7.1.

[Mantis Bugtracker #1162](http://project.geeklog.net/tracking/view.php?id=1162)

**Comment by mystralkk** [comment]
Related to #331

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
