### ISSUE TITLE
[Feature Requests] story manager: Wish to have ID column.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#331]
**Reported by @ivywe on 28 May 2010 15:01**

**Version:** 1.7.0

**Description:**
ID column is disappeared at story manager.
Wish to have ID column.

[Mantis Bugtracker #1163](http://project.geeklog.net/tracking/view.php?id=1163)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 29 Oct 2010 09:47**

Hmm. Some of the lists are already getting cramped. Maybe it&#039;s time to think about how to make the list columns configurable?

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
