### ISSUE TITLE
[Bugs] format ignored with $_CONF['left_blocks_in_footer'] = 1

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#338]
**Reported by suprsidr on 19 Jun 2010 14:19**

**Version:** 1.7.0

**Description:**
With $_CONF['left_blocks_in_footer'] = 1; geeklog ignores sp_format = noblocks

[Mantis Bugtracker #1172](http://project.geeklog.net/tracking/view.php?id=1172)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
