### ISSUE TITLE
[Feature Requests] add topic descriptions

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#340]
**Reported by tms on 25 Jun 2010 13:36**

**Description:**
please add topic descriptions - so we can have some introduction text at the top of a topic page - html would be good!

[Mantis Bugtracker #1174](http://project.geeklog.net/tracking/view.php?id=1174)

**Comment by mystralkk** [comment]
Related to #324

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 25 Jun 2010 14:10**

I&#039;ve thought about something like this before, but wasn&#039;t sure where to display the text ...

For now, you can use a Static Page in a center block. See http://www.geeklog.net/index.php?topic=Geeklog2 for an example.

**Comment by mystralkk** [comment]
**Comment posted by tms on 23 Aug 2010 23:32**

can you display the text using a tag - {topic_description} ? Then it can be enabled for some sites and disabled for others.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 29 Oct 2010 18:34**

Found some old notes about this idea. I was wondering if we could overwrite the {site_slogan} or provide a new variable, e.g. {site_slogan_or_topic_description} for header.thtml.

Btw, we already use the meta description of a topic for a title attribute in the Topics block. Should we extend on that or introduce a separate topic description (i.e. do you need both)?

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
