### ISSUE TITLE
[Bugs] Error occurred while upgrading from v1.6.1 or older to v1.7.0

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#344]
**Reported by @mystralkk on 6 Jul 2010 13:43**

**Version:** 1.7.0

**Description:**
When some of my friends were upgrading from 1.6.1 to 1.7.0 with "What's new" being displayed, an SQL error occurred:

```
An error has occurred:

(This text is only displayed to users in the group 'Root')

256 - An SQL error has occurred. Please see error.log for details. @
/***/system/databases/mysql.class.php line 260

array(3) {
  ["sql"]=>
  string(260) "SELECT sp_id, sp_title 
        FROM gl_staticpage 
        WHERE sp_content IS NOT NULL AND (draft_flag = 0) AND (created >=
(DATE_SUB(NOW(), INTERVAL SECOND))) 
         AND sp_centerblock = 0 AND sp_php = 0 

        ORDER BY created DESC LIMIT 15"
  ["ignore_errors"]=>
  int(0)
  ["result"]=>
  bool(false)
}
```

Since the error message includes the "created" field of static pages plugin, this error may have happened in this scenario:
1. You have uploaded new files to the server.
2. However, you haven't started the upgrading process yet.
3. Meanwhile, somebody views your site and plugin_getwhatsnew_staticpages() function is called.

[Mantis Bugtracker #1178](http://project.geeklog.net/tracking/view.php?id=1178)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 6 Jul 2010 20:17**

So this is not a problem with the upgrade as such?

The scenario you describe is not new - in fact, it has always been that way. We don&#039;t really have a way to disable the site for visitors during an upgrade.

There are two parts to this problem:
- While uploading the new files, you have a mixture of old and new files. During that phase, errors are pretty much unavoidable.
- Once all the new files have been uploaded and before the install script has been run in upgrade mode, it would be nice to be able to block visitors from the site while letting admins through (so they can perform the upgrade). That&#039;s not impossible but tricky (e.g. the site admin would probably have to log in before uploading the new files).

In any case, this is a temporary problem - I don&#039;t really see it as a &quot;major&quot; issue.

**Comment by mystralkk** [comment]
**Comment posted by mystral_kk on 7 Jul 2010 10:41**

Yes, this problem in itself is not with the upgrade.  However, once this happens during the upgrade, it is hard for users to deal with, since they have to disable the static page plugin manually from outside of Geeklog.

How about disabling plugins temporarily during the upgrade process or introducing the &quot;maintenance mode&quot; in which only the site admin(s) are allowed to access the site?

**Comment by mystralkk** [comment]
**Comment posted by jmucchiello on 9 Jul 2010 03:17**

Grab the last calender plugin I uploaded 2 years ago for how to avoid this. The function.inc that comes with each plugin needs modification to handle this. But it makes sense to avoid errors like this one. The same method used in the plugin could be used to disable the website.

Basically, the plugin does this:

if (CURRENT_VERSION != DB_getItem($_TABLES[&#039;plugins&#039;], &#039;pi_version&#039;, &quot;pi_name = &#039;$pi_name&#039;&quot;))
   include &#039;autoinstall.php&#039;; // to allow the plugin to upgrade
} else {
// rest of function.inc
}

I did this in calendar because I didn&#039;t want any errors to occur while I was doing my upgrades.

The same concept could be in lib-common.php using the gl_vars table.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
