### ISSUE TITLE
[Feature Requests] Hardcoded float in header-navigation-container ul/li

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#345]
**Reported by lwc on 11 Jul 2010 12:59**

**Version:** 1.7.0

**Description:**
It makes it look unnatural. The ul's "float:right;" makes the whole line appear on the right in LTR sites like Geeklog.net itself.

**Additional Information:**
Natural web expection from users is to find the menu in the left in LTR sites, and in the right in RTL sites.

[Mantis Bugtracker #1179](http://project.geeklog.net/tracking/view.php?id=1179)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
