### ISSUE TITLE
[Feature Requests] links plugin autotag: return number of links

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#350]
**Reported by @ivywe on 23 Aug 2010 17:42**

**Version:** 1.7.0

**Description:**
links plugin autotag :How many links are registered.

[links_count:] ... number of all links

[Mantis Bugtracker #1185](http://project.geeklog.net/tracking/view.php?id=1185)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
