### ISSUE TITLE
[Feature Requests] Static Page plugin: autotag [staticpage_content:]  deny_msg

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#352]
**Reported by @ivywe on 23 Aug 2010 20:43**

**Version:** 1.7.0

**Description:**

``` PHP
function service_get_staticpages()
...
                    $output .= COM_startBlock($LANG_ACCESS['accessdenied'], '',
                                COM_getBlockTemplate('_msg_block', 'header'));
                    $output .= $LANG_STATIC['deny_msg'];
                    $output .= COM_endBlock(COM_getBlockTemplate('_msg_block',
                                                                 'footer'));
...
```

I often comment out.

By the staticpage's access rights, the content display or not.

[Mantis Bugtracker #1187](http://project.geeklog.net/tracking/view.php?id=1187)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
