### ISSUE TITLE
[Bugs] Links' show_top10 fails when there are root links

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#362]
**Reported by lwc on 21 Sep 2010 11:59**

**Version:** 1.7.0

**Description:**
I had to open a new category and move root links in there. Until I did so, show_top10 refused to work.

It also fails with linkcols=0.

[Mantis Bugtracker #1197](http://project.geeklog.net/tracking/view.php?id=1197)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
