### ISSUE TITLE
[Feature Requests] Links' show_category_descriptions in categories' pages

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#363]
**Reported by lwc on 21 Sep 2010 12:02**

**Version:** 1.7.0

**Description:**
show_category_descriptions is currently only used for lists. Please consider using it in the category itself (maybe under "You are here: Root > Specific category").

[Mantis Bugtracker #1198](http://project.geeklog.net/tracking/view.php?id=1198)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
