### ISSUE TITLE
[Feature Requests] Make default $ttl for SEC_createToken configurable

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#366]
**Reported by @ivywe on 1 Oct 2010 16:07**

**Version:** 1.7.0

**Description:**
$ttl is now set 1200. (20 minutes.)
I hope $ttl is set on configuration panel.

lib-security.php now...

``` PHP
* @param int $ttl Time to live for token in seconds. Default is 20 minutes.
* @return string Generated token, it'll be an MD5 hash (32chars)
* @see SEC_checkToken
*
*/
function SEC_createToken($ttl = 1200)
```

[Mantis Bugtracker #1201](http://project.geeklog.net/tracking/view.php?id=1201)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
