### ISSUE TITLE
[Feature Requests] External introtext/bodytext-only autotags (a-la the built-in [page_break])

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#370]
**Reported by lwc on 10 Oct 2010 20:49**

**Version:** 1.7.0

**Description:**
[page_break] is the only possible introtext/bodytext-only autotag in Geeklog. This is because it's built-in and gets a manual treatment.

But every plugin out there could be like that too if $item was passed to PLG_replaceTags in function DisplayElements in system/classes/story.class.php

``` php
        case 'introtext':
...
            $return = PLG_replaceTags($this->_displayEscape($return), '', 'introtext');
...
        case 'bodytext':
...
            $return = PLG_replaceTags($return, '', 'bodytext');
```

**Steps To Reproduce:**
Then change system/lib-plugins.php from:

``` PHP
function PLG_replaceTags($content, $plugin = '')
...
                $content = $function('parse', $content, $autotag);
```

to:

``` PHP
function PLG_replaceTags($content, $plugin = '', $item = '')
...
                $content = $function('parse', $content, $autotag, $item);
```

**Additional Information:**
And finally change each plugin's functions.inc from:

``` PHP
function plugin_autotags_X($op, $content = '', $autotag = '')
```

to:

``` PHP
function plugin_autotags_X($op, $content = '', $autotag = '', $item = '')
```

[Mantis Bugtracker #1205](http://project.geeklog.net/tracking/view.php?id=1205)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
