### ISSUE TITLE
[Bugs] Display with users theme when Geeklog Configuration is saved. - Allow User Themes : False

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#377]
**Reported by @ivywe on 27 Oct 2010 12:54**

**Version:** 1.7.1rc1

**Description:**
Geeklog Configuration:
1. Users and Submissions
2. Allow User Themes : True
3. Theme: A
4. Save Changes

My Account : 
5. Theme B
6. Save Information

Geeklog Configuration:
7. Users and Submissions
8. Allow User Themes : False

Geeklog Configuration
9. Save Changes
10. Theme: B dislay.
11. any click, return to Theme A

[Mantis Bugtracker #1212](http://project.geeklog.net/tracking/view.php?id=1212)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
