### ISSUE TITLE
[Feature Requests] Make Geeklog sites identifiable for link and update checks?

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#378]
**Reported by @dhaun on 28 Oct 2010 21:12**

**Description:**
We briefly discussed this with someone from Midgard (I think): If a Geeklog site would send out something machine-readable, it would be possible
- for our list of Geeklog sites to automatically check if a site is really running Geeklog
- to check which version a site is running, for update warnings and statistics

We could add an X-Powered-By HTTP header, for example. Maybe only on certain URLs.

**Additional Information:**
We removed the version number from the default theme to make it not too obvious which version a site is running on. However, that's really only "security by obscurity" and the version number can still be figured out by other means, if only indirectly and with a level of uncertainty.

So the question is: Do we want to change our position on how this should be handled?

[Mantis Bugtracker #1213](http://project.geeklog.net/tracking/view.php?id=1213)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
