### ISSUE TITLE
[Bugs] Progress bar during SQL import doesn't move?

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#380]
**Reported by @dhaun on 29 Oct 2010 16:22**

**Version:** 1.7.1rc1

**Description:**
I've noticed this before but forgot to report it:

When doing a Migration (in the install script), the progress bar during the SQL import doesn't seem to move - at least not for big imports.

Not sure if this is a generic problem or if it's specific to Firefox ...

**Steps To Reproduce:**
- run the install script in "Migrate" mode
- use a large .sql file (I typically use a backup of geeklog.net, which is just under 100 MB)

[Mantis Bugtracker #1215](http://project.geeklog.net/tracking/view.php?id=1215)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
