### ISSUE TITLE
[Feature Requests] Multi Cron Schedule

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#387]
**Reported by @ivywe on 14 Nov 2010 07:21**

**Version:** 1.7.1

**Description:**
Cron Schedule is now only one.
Multi Cron Schedule is useful, I think.

[Mantis Bugtracker #1223](http://project.geeklog.net/tracking/view.php?id=1223)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
