### ISSUE TITLE
[Bugs] On core upgrade plugins are autoinstall

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#388]
**Reported by cordiste (@hostellerie) on 14 Nov 2010 11:25**

**Version:** 1.7.1

**Description:**
On core upgrade new plugins are autoinstall. Could it be an option?

[Mantis Bugtracker #1224](http://project.geeklog.net/tracking/view.php?id=1224)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
