### ISSUE TITLE
[Feature Requests] Hide only main page navigation

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#389]
**Reported by cordiste (@hostellerie) on 14 Nov 2010 15:44**

**Version:** 1.7.1

**Description:**
Can we have an option to hide the "Google paging" navigation from main page but keep it on topic pages.

[Mantis Bugtracker #1225](http://project.geeklog.net/tracking/view.php?id=1225)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
