### ISSUE TITLE
[Feature Requests] RSS feeds for more built-in plugins

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#391]
**Reported by lwc on 23 Nov 2010 12:22**

**Version:** 1.7.1

**Description:**
RSS feeds are currently only available for articles, links and calendar items.

How about also adding them for polls and staticpages?

[Mantis Bugtracker #1228](http://project.geeklog.net/tracking/view.php?id=1228)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
