### ISSUE TITLE
[Feature Requests] Accepting a query in [staticpage:] and [staticpage_content:]

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#392]
**Reported by lwc on 23 Nov 2010 13:43**

**Version:** 1.7.1

**Description:**
PHP staticpages can accept query parameters. It would therefore be great to get them from autotags, and present different results based on the passed query.

For example, [staticpage:demo query:foo=bar&geek=log normal description]

[Mantis Bugtracker #1229](http://project.geeklog.net/tracking/view.php?id=1229)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
