### ISSUE TITLE
[Bugs] The Plugin Autoinstall may not use the proper tablename when creating tables.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#396]
**Reported by @eSilverStrike  on 27 Nov 2010 17:17**

**Version:** 1.7.1

**Description:**
The plugin autoinstall seems to use the name of the element in the $_TABLES[] array to create tables (ie the 'autotags' in $_TABLES['autotags']) instead of what it actually equals.

In my case 

$_TABLES['autotags'] = 'gl_autotags_plg'

the table name 'gl_autotags" was created during the autoinstall instead of 'gl_autotags_plg'.

The uninstall process should also be double checked.

[Mantis Bugtracker #1233](http://project.geeklog.net/tracking/view.php?id=1233)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
