### ISSUE TITLE
[Feature Requests] Static Page plugin: Wiki-style format support.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#397]
**Reported by @ivywe on 29 Nov 2010 17:41**

**Version:** 1.7.1

**Description:**
Static Page plugin: Wiki-style format support.

[Mantis Bugtracker #1234](http://project.geeklog.net/tracking/view.php?id=1234)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
