### ISSUE TITLE
[Patches] Missing field issue on block creation

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#399]
**Reported by cordiste (@hostellerie) on 17 Dec 2010 14:03**

**Version:** 1.7.1

**Description:**
When creating a new block, the block name is now require. Maybe we can inform users there is a required field here.

If this field is missing, on submission the block form is reload without the data from the previous form (block title, block content...).

[Mantis Bugtracker #1237](http://project.geeklog.net/tracking/view.php?id=1237)

[patch.zip](https://github.com/Geeklog-Core/geeklog/files/88719/patch.zip)

**Comment by mystralkk** [comment]
Related to #144

**Comment by mystralkk** [comment]
Related to #126

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
