### ISSUE TITLE
[Feature Requests] Autotag story_content and topic_content

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#403]
**Reported by cordiste (@hostellerie) on 7 Jan 2011 11:06**

**Version:** 1.7.1

**Description:**
It could be usefull to display story content or topic content in a static page.

Param 2 could be "intro" for intro only or "full" for story intro + body.

[story_content:welcome full]
[topic_content:General intro]

[Mantis Bugtracker #1241](http://project.geeklog.net/tracking/view.php?id=1241)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
