### ISSUE TITLE
[Feature Requests] Delete All Cookies option

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#404]
**Reported by @dhaun on 8 Jan 2011 22:12**

**Version:** 1.7.1

**Description:**
Saw this on a phpBB (I think) forum: An option to "delete all board cookies".

Not sure if there's a good place in Geeklog to offer this as a generic option. However, if a user decides to delete their account, we should also (automatically) delete all the cookies related to the site.

Note that this should NOT go into USER_deleteAccount() since that function is called from a number of places.

[Mantis Bugtracker #1242](http://project.geeklog.net/tracking/view.php?id=1242)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
