### ISSUE TITLE
[Bugs] calendar event hour issue

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#412]
**Reported by cordiste (@hostellerie) on 20 Jan 2011 15:38**

**Version:** 1.7.1

**Description:**
On event view the "When" information display end hour instead start hour.

[Mantis Bugtracker #1250](http://project.geeklog.net/tracking/view.php?id=1250)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
