### ISSUE TITLE
[Feature Requests] Comment Field like Wordpress

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#415]
**Reported by Bludie on 21 Jan 2011 16:05**

**Version:** 1.7.1

**Description:**
Geeklog to use as a blog, I'd like a comment box that is made as similar as the comments by Wordpress with the name field and email field Url field (dofollow / nofollow)

[Mantis Bugtracker #1253](http://project.geeklog.net/tracking/view.php?id=1253)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
