### ISSUE TITLE
[Feature Requests] Article Directory Columns and Page Navigation

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#421]
**Reported by @eSilverStrike  on 29 Jan 2011 15:22**

**Version:** 1.7.1

**Description:**
In the configuration allow Admin to control if the left or right columns are displayed for the Article Directory (like Page Format in the Staticpage editor). Also lets use the same page navigation as we do everywhere else on the site.

[Mantis Bugtracker #1261](http://project.geeklog.net/tracking/view.php?id=1261)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
