### ISSUE TITLE
[Bugs] Autotags aren't expanded with query highlighting

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#431]
**Reported by lwc on 8 Feb 2011 00:44**

**Version:** 1.7.1

**Description:**
As mentioned in 0000887#c744, autotags aren't expanded with query highlighting.

[Mantis Bugtracker #1273](http://project.geeklog.net/tracking/view.php?id=1273)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
