### ISSUE TITLE
[Feature Requests] Profile setting: Subscribing to comment notifications by default

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#445]
**Reported by cordiste (@hostellerie) on 17 Mar 2011 08:37**

**Version:** 1.7.2

**Description:**
Registered users can get an email notifying them of direct replies to comments they left. 

Can users have a setting under the profile to allow receving comment notifications to all new comment they will make.

[Mantis Bugtracker #1290](http://project.geeklog.net/tracking/view.php?id=1290)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
