### ISSUE TITLE
[Bugs] wiki-style url rather be able to detect it, can trackback Pingbacks are also not available

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#446]
**Reported by hiroron on 19 Mar 2011 02:39**

**Version:** 1.7.2

**Description:**
style to create a wiki article does not create a list of links to related information can also create an external link to the article.

Trackbacks can also Pingback "no link" is not available and out.

[Mantis Bugtracker #1291](http://project.geeklog.net/tracking/view.php?id=1291)

[lib-story.php.zip](https://github.com/Geeklog-Core/geeklog/files/88697/lib-story.php.zip)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
