### ISSUE TITLE
[Bugs] When the article contribution is done by the wiki style, the image tag cannot be used.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#449]
**Reported by hiroron on 24 Mar 2011 09:09**

**Version:** 1.7.2

**Description:**
The article contribution is done by the wiki style.
The image specificationsed [ImageX], [ImageX_left], and [ImageX_right].

As a result, the images not correctly displayed.

[Mantis Bugtracker #1294](http://project.geeklog.net/tracking/view.php?id=1294)

[story.class.php.zip](https://github.com/Geeklog-Core/geeklog/files/88689/story.class.php.zip)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
