### ISSUE TITLE
[Feature Requests] Consistency in tabs design

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#450]
**Reported by Roccivic on 26 Mar 2011 12:27**

**Version:** 1.8.0

**Description:**
The new configuration GUI brings us tabs, but they are different from what is used in, say, "my account". Those new tabs look much nicer than the old ones, so I guess it would be nice have more of them :)

[Mantis Bugtracker #1295](http://project.geeklog.net/tracking/view.php?id=1295)

![screenshot](https://cloud.githubusercontent.com/assets/2015377/12291271/9d181c90-ba29-11e5-88c6-43147a4e6853.png)

**Comment by eSilverStrike** [comment]
My Account uses UIKit tabs and the configuration uses jQuery tabs I believe...

As of Geeklog 2.1.2 there are not a huge amount of differences between the tabs now.

For jQuery we currently use the Redmond theme. Not sure why that theme was picked but jQuery does have a bunch of new ones now. We could try picking a theme that is closer to the UIkit one used.

http://jqueryui.com/themeroller/

or just update the jquery-ui.geeklog.css file

**Comment by mystralkk** [comment]
As of Geeklog 2.1.3, tabs design seems consistent enough to me even when using the Modern Curve theme, to say nothing of the Denim theme.  Why don't we close this issue without making any further change?

**Comment by eSilverStrike** [comment]
Sounds good.
