### ISSUE TITLE
[Bugs] Autotag tooltip is sometime outside the viewport

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#457]
**Reported by cordiste (@hostellerie) on 4 Apr 2011 12:47**

**Version:** 1.8.0b1

**Description:**
The on hover tooltip for autotag can partialy outside the viewport and user can not read the information. See picture attached.

[Mantis Bugtracker #1304](http://project.geeklog.net/tracking/view.php?id=1304)

![tooltip](https://cloud.githubusercontent.com/assets/2015377/12291230/6d01b9a8-ba29-11e5-99b6-4ee4800cc030.jpg)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
