### ISSUE TITLE
[Feature Requests] Internationalise  the version checker

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#470]
**Reported by Roccivic on 14 Apr 2011 17:45**

**Version:** 1.8.0b1

**Description:**
The version checker is pretty much all hardcoded in English, but it would nice if it could pick up the locale from the user of the site that requested the check and display itself in the appropriate language.

**Steps To Reproduce:**
1. Switch language in geeklog to something other than English
2. Perform a version check
3. The result is displayed in English

**Additional Information:**
My bad for not thinking about this earlier while implementing the functionality, lol.

[Mantis Bugtracker #1319](http://project.geeklog.net/tracking/view.php?id=1319)

**Comment by mystralkk** [comment]
**Comment posted by Roccivic on 14 Apr 2011 17:48**

By the way, the repository for the version checker is here: http://project.geeklog.net/cgi-bin/hgwebdir.cgi/tools/

**Comment by mystralkk** [comment]
I have updated the version checker at https://github.com/Geeklog-Core/tools/tree/master/versionchecker .  Would you please FTP the code to geeklog.net, @eSilverStrike ?

**Comment by eSilverStrike** [comment]
Geeklog.net has now been updated. Looks good but I will let you close incase you wanted to test anything else.

**Comment by mystralkk** [comment]
Thanks, @eSilverStrike .  Now versionchecker looks like this:

<img width="960" alt="スクリーンショット 2020-02-03 05 44 26" src="https://user-images.githubusercontent.com/2015377/73615114-81f30b00-4648-11ea-9d3d-3c53191aedd1.png">
<img width="960" alt="スクリーンショット 2020-02-03 05 43 59" src="https://user-images.githubusercontent.com/2015377/73615115-81f30b00-4648-11ea-8d78-87aa73afa1a4.png">
