### ISSUE TITLE
[Feature Requests] Rework viewing and editing of Plugin Profile Variables

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#471]
**Reported by @eSilverStrike  on 14 Apr 2011 20:26**

**Description:**
For plugins to add profile variables for viewing and editing they must use the following functions:

plugin_profileextrassave_foo 
plugin_profilevariablesedit_foo
plugin_profilevariablesdisplay_foo

While it does appear to work it can become confusing since admins must manually add in the profile variables to the appropriate templates (usually profile.thtml under users and preference directory) to make everything work. 

I propose adding a single common template variable that plugins can use to add their information to the profile view and edit forms. The plugin would need to supply their own template which would then be parsed with the template variable. Each plugin would get a turn based on the plugin order. This may require a few new functions to do this.

It would also be nice if the plugins could add a new tab to My Account if they need too.

See this post for more details:
http://www.geeklog.net/forum/viewtopic.php?showtopic=87955&mode=&show=5&page=4

[Mantis Bugtracker #1320](http://project.geeklog.net/tracking/view.php?id=1320)

**Comment by mystralkk** [comment]
Related to #273

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 22 Apr 2011 13:44**

Just to confirm the current Geeklog API for this is not broken. I have it working fine in the new version of the forum plugin. Though as I mentioned before we need to make things easier by using template varibles and extra templates files so stuff is displayed and can be edited automatically.

In users/profile.html (the preview) I see 3 extra template variables needed. 1 for the &quot;Your Public Profile&quot;, 1 for the &quot;Last 10 xxxx for User xxxx&quot; and then 1 for &quot;Posting statistics for user xxx&quot;

In preferences/profile.html (editor) we should allow plugins to add extra fields to any tab (5 variables) and also allow a plugin to add an extra tab if needed.

I was also thinking it would be nice if the plugins had an option to add a tab when viewing information instead of a plugin putting the information at the bottom of the page with the function plugin_profileblocksdisplay_foo.

And if we are going to do all this then we might as well convert the tabs to the jQuery tabs ... but that is another feature request

**Comment by eSilverStrike** [comment]
@dengen For the denim and modern curve themes and for the user profile page can you  add the following css class (base it on storyrow class)
last10row

and remove the following css classes
commentrow
storyrow

**Comment by dengenxp** [comment]
I did with change set #c16ce2b.
