### ISSUE TITLE
[Feature Requests] Login button on comment form

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#477]
**Reported by cordiste (@hostellerie) on 23 Apr 2011 12:32**

**Version:** 1.8.0b1

**Description:**
There is only a "Create account" button on the comment form. Could we have also a login button, it will be very useful for users from twitter, facebook ...

[Mantis Bugtracker #1327](http://project.geeklog.net/tracking/view.php?id=1327)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 23 Apr 2011 20:01**

This probably dates back to Geeklog&#039;s early days and assumes that the login is always visible to the left of the comment form. Time to reconsider some of the forms (I&#039;m sure you&#039;ll see similar elsewhere, e.g. in the story submission form).

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
