### ISSUE TITLE
[Feature Requests] Allow user to change authentication option

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#481]
**Reported by @dhaun on 24 Apr 2011 07:15**

**Version:** 1.8.0

**Description:**
Users should have a way to select the authentication for their account, i.e. switch to another login method.

This is already a minor issue when you created an account with a Geeklog site and now want to use OpenID. It will become more prevalent with the introduction of Twitter and Facebook OAuth logins in Geeklog 1.8.0.

[Mantis Bugtracker #1331](http://project.geeklog.net/tracking/view.php?id=1331)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 24 Apr 2011 14:26**

At first I was thinking we could just have a dropdown in the User Profile with the list of available authentications. When the user selects a different authentication we could then display &quot;are you sure?&quot; dialogue and if they say yes then attempt to authenticate them under their new selection. If it fails we would then leave it as the original. I would&#039;t see a need to resynch the user data at this point (except for getting the remote user name).

The problem with this solution is it would only work with OAuth. OpenID, etc.. would require additonal information so additional step/page would be required.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
