### ISSUE TITLE
[Feature Requests] Merge accounts option

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#482]
**Reported by @dhaun on 24 Apr 2011 07:17**

**Version:** 1.8.0

**Description:**
We should have an option - at least for admins, but possibly also for normal users - to merge two accounts into one.

This was only a minor issue until now, in case someone forgot that they already had an account with the site and created a new one. This will probably become more common with Geeklog 1.8.0 when users start using Twitter or Facebook OAuth to log into a site and don't realize that it would create a new account.

[Mantis Bugtracker #1332](http://project.geeklog.net/tracking/view.php?id=1332)

**Comment by mystralkk** [comment]
Related to #481

**Comment by mystralkk** [comment]
**Comment posted by Roccivic on 24 Apr 2011 11:45**

I&#039;m thinking that soft-linking accounts could be more desirable than actually merging them. I&#039;m thinking that several accounts could be linked and then one of them marked as a master and every other account as a auxiliary. The auxiliary accounts are only used for authentication, and once the user is logged in, the profile from the master account is used. But this is probably too big of a request...

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 24 Apr 2011 14:17**

I think allowing users this option would be a headache. We would have to get the user to log into both accounts to confirm that they own it to initiate the merge.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
