### ISSUE TITLE
[Bugs] Content lost during OAuth login

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#488]
**Reported by Roccivic on 30 Apr 2011 16:05**

**Version:** 1.8.0b2

**Description:**
I've just tried to post a message on the forum while logged in as an anonymous user and after realising that I was not logged in I clicked on "Login with Facebook". I was redirected to the main page on geeklog.net and the action that I was carrying out was lost. This does not happen with 'normal' login. For example, after logging in with my regular account I'm redirected back to the page that I was viewing (the forum post).
Steps To Reproduce  1. Start composing a message at the forum as anonymous
2. Click "Login with {some OAuth provider}"
3. You are not redirected back to the forum

[Mantis Bugtracker #1338](http://project.geeklog.net/tracking/view.php?id=1338)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 1 May 2011 14:29**

This probably has to do with the fact that the OAuth authentication is done off site and gets redirected back to Geeklog.  We would have to store the previous location of the user somewhere and then retrieve it once the login happened. OpenID would suffer from this as well.

**Comment by mystralkk** [comment]
> We would have to store the previous location of the user somewhere and then retrieve it once the login happened. 

To do this, we would need a true session manager using PHP's native $_SESSION adn session_* functions.

**Comment by mystralkk** [comment]
About the content being lost while editing, we could use JavaScript's localStorage feature.

**Comment by eSilverStrike** [comment]
Relates to #828

**Comment by eSilverStrike** [comment]
Moving this to 2.3.0 for now when we plan to add PHP Sessions. Once this is done we can then work on allowing OAuth and OpenID to re-authenticate on saving if token expired

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
