### ISSUE TITLE
[Bugs] Staticpage Services doesn't execute PHP in pages

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#490]
**Reported by @eSilverStrike  on 15 May 2011 18:13**

**Version:** 1.8.0rc1

**Description:**
I am not sure fully about this one.

I use PLG_invokeService to return a staticpages content for a few plugins like so:

```
    $retval = '';
    $mode = '';
    $args = array(
                'sp_id' => $id,
                'mode' => $mode,
                'gl_svc' => ''
                 );
    $svc_msg = array(); 
    if (PLG_invokeService('staticpages', 'get', $args, $retval, $svc_msg) == PLG_RET_OK) {
```

...

The problem is that the evaluation of PHP in a staticpage is done in SP_render_content so any php in a staticpage will be return not executed. This evaluation should be done in the Service get call.

[Mantis Bugtracker #1341](http://project.geeklog.net/tracking/view.php?id=1341)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
