### ISSUE TITLE
[Bugs] CMT_rebuildTree is called by moderation.php

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#492]
**Reported by vinny on 16 May 2011 01:10**

**Version:** 1.8.0

**Description:**
CMT_rebuildTree is called by moderation.php when a comment is approved for a story. This is a very inefficient, and unnecessary call. Before removing, CMT_approveModeration will need to be handled to correctly insert comments and update the comment count of the story.

**Steps To Reproduce:**
View Code

**Additional Information:**
Low priority because there haven't been any complaints. Will only really bite large sites with lots of comments that also use comment moderation, I imagine that is a pretty unusual combination.

[Mantis Bugtracker #1343](http://project.geeklog.net/tracking/view.php?id=1343)

**Comment by eSilverStrike** [comment]
Old issue so closing and not really a priority.
