### ISSUE TITLE
[Feature Requests] Better template for static page editor

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#495]
**Reported by cordiste (@hostellerie) on 17 May 2011 17:16**

**Version:** 1.8.0rc1

**Description:**
Could have a more user friendly template for static page editor? Its use is a little confusing the first time. There are indeed two titles to grasp and a lot of options before reaching the part that really interests the user base, ie the static page content itself.

Perhaps an organization with tabs, like the editor of the articles, would clarify the situation.

[Mantis Bugtracker #1346](http://project.geeklog.net/tracking/view.php?id=1346)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 17 May 2011 18:40**

We could also start incorporating tooltips into our editors to help explain the different options.

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 22 May 2011 14:01**

Before this feature happens we should discuss exactly how we want to present the information in an editor, how help information should be displayed, where jQuery should be use, etc... since if someone does end up working on this it could become the standard for other plugins.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
