### ISSUE TITLE
[Bugs] Config issue : Allow Hide Author

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#496]
**Reported by cordiste (@hostellerie) on 18 May 2011 08:23**

**Version:** 1.8.0rc1

**Description:**
If "Allow Hide Author" is set to false in the config, Hide author setting is display on the account information page of users.

Then if "Allow Hide Author" is set to true, Hide author setting is not display but the message on the right is confuse because there is no autheurs list :

Filter Story Content
Check the boxes for the topics and authors you don't want to see.

[Mantis Bugtracker #1347](http://project.geeklog.net/tracking/view.php?id=1347)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
