### ISSUE TITLE
[Feature Requests] Allow the Send Mail form to be displayed via an autotag

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#501]
**Reported by @eSilverStrike  on 28 May 2011 14:18**

**Description:**
It would be nice if the Send mail form could be displayed with an autotag. This way I could embed it in a staticpage or story which could include (for example) instructions about contacting the website.

[Mantis Bugtracker #1352](http://project.geeklog.net/tracking/view.php?id=1352)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
