### ISSUE TITLE
[Bugs] Enabling Image Library requires two steps

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#504]
**Reported by @dhaun on 30 May 2011 18:16**

**Version:** 1.8.0rc1

**Description:**
Configuration > Geeklog > Images > Image Library

Starting with no image library being selected yet and both path settings being disabled. Try enabling ImageMagick and entering the path to mogrify, then save changes. Geeklog won't let you, stating:

"You must set image library to imagemagick and fill this field with complete path to the mogrify executable"

... but you did just that.

[Mantis Bugtracker #1355](http://project.geeklog.net/tracking/view.php?id=1355)

![firefox081](https://cloud.githubusercontent.com/assets/2015377/12260215/e4a25796-b95d-11e5-858e-d3fbc29c2457.png)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 31 May 2011 14:18**

I was able to save the configuration. I set the image library to imagemagick and then put in the same path I did for geeklog log files and the configuration saved fine.

The actually location of the vailidation for this field is in the configuration.php in the admin directory under the function 

custom_validation_path_to_mogrify

it used the file_exists function to check the path. This does work for me (on my Windows server) but I did change it to is_dir since that is what it should be and is how the other paths are confirmed in the rest of the configuration.

Let me know if this works.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 2 Jun 2011 08:34**

Actually, file_exists was correct. &quot;mogrify&quot; is an exectuable. is_dir should be used for the Netpbm option (where the path is supposed to point to a directory with the Netpbm exectuables).

Either way, it still doesn&#039;t work for me to enable this option in one step:

- select ImageMagick from the dropdown
- enable Path to Mogrify option (which also resets the dropdown to None)
- enter path to mogrify exectuable, e.g. /usr/bin/mogrify (which exists)
- select ImageMagick from the dropdown again
- hit Save Changes
- won&#039;t save, see screenshot :(
- even hitting Save Changes again doesn&#039;t work
- in fact, I can&#039;t seem to get out of that dialog at all, other than switching to another page and losing the changes I made on the current one

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 2 Jun 2011 18:21**

I missed reading the title of the bug report &quot;Enabling Image Library requires two steps&quot;.  I thought it wasn&#039;t saving for you period. It takes 2 steps for me to save it as well.

So I guess we have a few options here.

1) Update the error message telling the user they must save Image Library before saving the path.

2) Remove the image library check from the path validation.

3) Update the validation code to support checking of unsaved config values.

Number 2 may make the most sense since that is how most other similar config options behave. For example you can set the syndication output folder even if feeds are disabled (same with pear, mysql dump, etc...)

Number 3 is possible as well with some code changes. We could pass in the changed array to the validation function which could then check the appropriate value. The programmer would just have to make sure that the value he is checking has already been through the validation process (values are processed in the order they appear). This could get a little messy though and could only be used by a custom validation function (and not a predefined one in the validator class).

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
