### ISSUE TITLE
[Bugs] clear class is missing  style.css

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#508]
**Reported by cordiste (@hostellerie) on 10 Jun 2011 07:49**

**Version:** 1.8.0rc2

**Description:**
On the submit event page the form use clear-left class but this class is missing in the style sheet.

[code]
/\* general alignment classes *************************************************_/
.alignleft {
  text-align:left;
}
.alignright {
  text-align:right;
}
.aligncenter {
  text-align:center;
}
.aligntop {
  vertical-align:top;
}
.floatright {
  float:right;
}
.floatleft {
  float:left;
}
.clearboth {
  clear:both;
}
/_ clear floats by applying the clearfix class to float-encasing block !*******/
.clearfix:after {
  content: ".";
  display: block;
  height: 0;
  clear: both;
  visibility: hidden;
}
.clearfix {
  display: inline-block;
}

/\* Hides from IE-mac */
- html .clearfix {height: 1%;}
  .clearfix {display: block;}
  /\* End hide from IE-mac */

[Mantis Bugtracker #1359](http://project.geeklog.net/tracking/view.php?id=1359)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
