### ISSUE TITLE
[Feature Requests] Add information tooltip for [code], [raw], [page_break]

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#510]
**Reported by cordiste (@hostellerie) on 13 Jun 2011 20:28**

**Version:** 1.8.0

**Description:**
There is no tooltip for [code], [raw] and [page_break]. It would be usefull to many users.

[Mantis Bugtracker #1361](http://project.geeklog.net/tracking/view.php?id=1361)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
