### ISSUE TITLE
[Feature Requests] Add information about Permissions[X]

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#513]
**Reported by cordiste (@hostellerie) on 14 Jun 2011 07:48**

**Version:** 1.8.0

**Description:**
On the configuration pages Permissions[0] to Permissions[3] are not very explicit for new users. Maybe a tooltip here could help.

[Mantis Bugtracker #1364](http://project.geeklog.net/tracking/view.php?id=1364)

**Comment by eSilverStrike** [comment]
Removed numeric check for config help which indicates a config option variable is an array. The only thing that uses config variables which are an array at the moment is Security Default Permissions for items like articles, dynamic blocks and autotags usage permissions.
