### ISSUE TITLE
[Feature Requests] Introduce a [script] tag

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#521]
**Reported by @dhaun on 30 Jul 2011 20:33**

**Version:** 1.8.0

**Description:**
Bug #517 demonstrated that we really need 3 different ways to encode / display content in posts, e.g. a story:
- "Normal" mode: The normal text of a story, obviously. You would also expect HTML to be interpreted if posting in HTML mode or to show up verbatim if posting in text mode. Any special characters should automatically be encoded such that they show up in the post (and not be interpreted or replaced). For example, dollar signs or curly braces would be replaced with HTML entities.
- [code] or [raw] sections: For code snippets, i.e. the text should show up exactly like the author entered it. HTML, for example, would show up verbatim and not be interpreted. The same should be true for JavaScript code (which was the problem in bug 0001368).
- (new) "script code", the text should be saved (but not displayed) as entered. This would be required, for example, to embed JavaScript code in stories. Dollar signs or curly braces would not be replaced but stored as-is.

Suggestion: Introduce a [script] tag for these sections. One new tag would be sufficient, unlike with the [code](block) and [raw](inline) tags - script code would be inline.

**Steps To Reproduce:**
See issue #517

[Mantis Bugtracker #1373](http://project.geeklog.net/tracking/view.php?id=1373)

**Comment by mystralkk** [comment]
Related to #517

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
