### ISSUE TITLE
[Feature Requests] add flag to force account email update

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#523]
**Reported by cchiapusio on 4 Aug 2011 14:13**

**Version:** 1.8.0

**Description:**
I have several user accounts that have invalidated emails (they bounce on story notifications) and would like to flag those accounts to notify the user to update their email address when they do log in again.

[Mantis Bugtracker #1375](http://project.geeklog.net/tracking/view.php?id=1375)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 7 Aug 2011 07:54**

That sounds like a good idea.

It would be nice if we had some sort of internal notification system so that we could display such a notice to the user the next time they log in. Would also be useful in other situations.

**Comment by eSilverStrike** [comment]
I have the similar issue with OAuth users that didn't return an email address.

**Comment by eSilverStrike** [comment]
Feature already added in v2.2.0 I believe along with user status feature request.
