### ISSUE TITLE
[Bugs] Visiting Users.php while logged in will present you with a login page

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#524]
**Reported by @eSilverStrike  on 7 Aug 2011 16:35**

**Version:** 1.8.0

**Description:**
While you are logged in and if you visit http://www.geeklog.net/users.php you will be presented with the login page with the title "Try Logging in Again"

I think we need 2 changes here.

1) If a user is not logged in the page title should read something other than "Try Logging in Again" if it is their first time visiting the page.

2) If the user is already logged in then maybe it should redirect to the My Account page???

[Mantis Bugtracker #1376](http://project.geeklog.net/tracking/view.php?id=1376)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 8 Aug 2011 18:15**

Good points (both).

users.php is sometimes used as a login page on sites that hide the login block from anonymous users. So while the &quot;again&quot; bit is obviously irritating and should be fixed, the overall text should still be such that the user is asked to log in here.

**Comment by eSilverStrike** [comment]
Fixed in some previous version of Geeklog.
