### ISSUE TITLE
[Bugs] Can't install Geeklog 1.8.0rc2

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#528]
**Reported by ragnar76 on 24 Aug 2011 14:42**

**Version:** 1.8.0rc2

**Description:**
Hi all,

i just wanted to install geeklog on my fresh installed debian server and i went into some trouble while doing this. I have enabled root debugging to see what happens and i get this error:

2 - array_merge(): Argument 0000001 is not an array @ /var/www/.geeklog/system/lib-plugins.php line 1553

The whole debugging output is in the attached file.

Versions of PHP and MySQL below:

PHP 5.3.6-13 with Suhosin-Patch (cli) (built: Jul 4 2011 12:42:46) 
Copyright (c) 1997-2011 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2011 Zend Technologies
    with XCache v1.3.2, Copyright (c) 2005-2011, by mOo
    with Suhosin v0.9.32.1, Copyright (c) 2007-2010, by SektionEins GmbH

mysql Ver 14.14 Distrib 5.1.58, for debian-linux-gnu (x86_64) using readline 6.2

bye
Bernd

[Mantis Bugtracker #1380](http://project.geeklog.net/tracking/view.php?id=1380)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 24 Aug 2011 14:49**

This probably won&#039;t help with your problem, but why are you installing a release candidate (rc2)? The final version has been out for a while now.

As for the error - this could very well be a bug. Did you choose to install Geeklog without any plugins? I.e. during the install process, did you uncheck all the bundled plugins?

**Comment by mystralkk** [comment]
**Comment posted by ragnar76 on 24 Aug 2011 18:32**

i&#039;m sorry. the rc2 was the last thing on my mind. i&#039;ve tried 1.8.0 and also the rc2 but no matter which version i use, i always get the same error from both versions.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 24 Aug 2011 18:56**

Yeah, I didn&#039;t really expect it to make a difference.

So, did you choose to install without any plugins? Or did anything else happen during the installation?

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 24 Aug 2011 19:59**

Okay, so we narrowed it down a bit on IRC: Apparently, only 2 of the 6 bundled plugins got installed, then something happened. The gl_plugins table only contains

(&#039;staticpages&#039;, &#039;1.6.4&#039;, &#039;1.8.0&#039;, 1, &#039;http://www.geeklog.net/&#039;, 10000),
(&#039;xmlsitemap&#039;, &#039;1.0.1&#039;, &#039;1.8.0&#039;, 1, &#039;http://www.geeklog.net/&#039;, 10000);

The order in which the plugins are installed isn&#039;t really predictable - we just loop over whatever&#039;s in the plugins directory and the sort order can vary between file systems.

Current theory: Maybe one of our plugins doesn&#039;t work with the Suhosin patch?

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 25 Aug 2011 20:14**

So looks like Rouslan was able to reproduce it, which is a start:
http://eight.pairlist.net/pipermail/geeklog-devel/2011-August/005643.html

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 27 Aug 2011 14:31**

So Rouslan is on vacation now and so far I had no luck trying to reproduce this with Ubuntu 11.04 (32 bit) and Debian squeeze (64 bit). Trying Debian wheezy next ...

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 27 Aug 2011 18:18**

So even though I am now running the _exact_ same versions of PHP and MySQL, I can still not reproduce the problem :-/

This is on Debian Wheezy, 64 bit
- used the original geeklog-1.8.0.tar.gz tarball from geeklog.net
- used 127.0.0.1 as the URL
- used UTF-8 as the character set
- installed Geeklog from /var/www/.geeklog, as in the original report (pointed the DocumenRoot to .geeklog/public_html - no vhost)

What am I doing &quot;wrong&quot;?

I&#039;m almost out of ideas now. Just these 2:

1) Did you create a new MySQL user? If so, which permissions did it have? (I&#039;m using &quot;root&quot;, since I&#039;m lazy)

2) Can you please try and edit public_html/admin/install/lib-install.php and change the error_reporting() call to simply: error_reporting(E_ALL);
Then try again. Any interesting error messages?

**Comment by mystralkk** [comment]
**Comment posted by ragnar76 on 27 Aug 2011 23:05**

Hi,

1.) nope, i use root as default too.

2.) I will on monday, i&#039;m a bit busy with the chaos computer club in dÃ¼sseldorf/germany. They got a new clubroom and i&#039;m electrician, so i help them with electricity.

**Comment by mystralkk** [comment]
**Comment posted by ragnar76 on 4 Sep 2011 10:59**

I&#039;m sorry for this delay, i had a lot of work this week :(

To the second point, there is no error message at all after changing to error_reporting(E_ALL); . Interessting thing is, error_reporting(); is defined with this &quot;options&quot; E_ERROR, E_WARNING, E_PARSE, E_COMPILE_ERROR, E_NOTICE.

I also tested it with my PowerMac G4 and Debian Linux again, same error there. I&#039;m about to install gentoo on the mac and test it there again but this takes some time to build gentoo. the ppc i have i not the fastest :(

**Comment by eSilverStrike** [comment]
Closing this issue as the install has changed a lot since 2011 and we have had no new reports of this problem.
