### ISSUE TITLE
[Feature Requests] Invalid Username Error Messages

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#530]
**Reported by @eSilverStrike  on 25 Aug 2011 13:36**

**Version:** 1.8.0

**Description:**
Everytime someone logs in with an invalid username a message is created in the error logs. I have notice on a number of sites (including Geeklog.net) that bots appear to be hitting our sites trying to login using random usernames. They get around the speedlimit by trying every few minutes.

Wed Aug 24 23:26:12 2011 - Error, invalid username: 'cibiatirl' 
Wed Aug 24 23:36:15 2011 - Error, invalid username: 'vegascompudoc' 
Wed Aug 24 23:39:51 2011 - Error, invalid username: 'cibiatirl' 
Wed Aug 24 23:49:02 2011 - Error, invalid username: 'coachtrm' 

I would like to at least update the error log to include the ip the request is coming from so I can go in and at least manually ban the ip in the ban plugin.

I also think we should put error messages in maybe when a speedlimit is hit so I would know if say someone is trying to crack the Admin password or something.

[Mantis Bugtracker #1382](http://project.geeklog.net/tracking/view.php?id=1382)

**Comment by mystralkk** [comment]
Related to #438

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
