### ISSUE TITLE
[Bugs] New User Registration

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#535]
**Reported by @Tsuchi000 on 14 Sep 2011 02:18**

**Version:** 1.8.0

**Description:**
PLG_userInfoChanged does not run when registering a new user

for example Modify the following
admin/user.php
576 if ($uid > 1) {
578 DB_query("UPDATE {$_TABLES['users']} SET status = $userstatus WHERE uid = $uid");
        $userChanged = true;//****adding
579 }

[Mantis Bugtracker #1389](http://project.geeklog.net/tracking/view.php?id=1389)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 17 Sep 2011 19:31**

Hmm, do you really need that? When a new user is created, PLG_createUser() is being called.

I guess it&#039;s up for interpretation whether creating a new user account is also &quot;changing&quot; the user&#039;s information ... But at least plugins already have a way of being informed.

**Comment by mystralkk** [comment]
**Comment posted by Tsuchi on 30 Sep 2011 02:01**

Because Plugins don&#039;t have new user group information.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
