### ISSUE TITLE
[Bugs] HTML comments munged by broken wordwrap and lf filtering

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#536]
**Reported by jb on 17 Sep 2011 23:32**

**Version:** 1.8.0

**Description:**
When a HTML format comment is posted, Geeklog incorrectly mungs it as follows:
1. All/Most CR and LF characters are replaced by nothing. HTML specs says to treat them as spaces except in &lt; pre &gt; tags etc. (where they should be kept). Thus the best thing to do is just not to remove them, the second best thing is to replace them with spaces.
2. Next the half-munged HTML (which is now one very long line) is forcibly word wrapped by a function which will arbitrarily insert line breaks in the middle of words or HTML tags. Because browsers do not mind receiving long lines, this step is unnecessary, even if fixed to never break up words.

**Steps To Reproduce:**
In a site powered by an affected version of Geeklog, and configured to allow HTML comments, post a HTML comment similar to the following:

&lt; p &gt;&lt; b &gt;Look,
a nice pattern!&lt; / b &gt;&lt; / p&gt;
&lt; p &gt;++++++++++++++++++++++++++++++++++++++++++++++++++++++++&lt; br &gt;
++++++++++++++++++++++++++++++++++++++++++++++++++++++++&lt; br &gt;
++++++++++++++++++++++++++++++++++++++++++++++++++++++++&lt; br &gt;
++++++++++++++++++++++++++++++++++++++++++++++++++++++++&lt; / p &gt;

Click Preview

Expected output:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Actual output:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++ +++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++ ++++++++++++++++++++

(Notice the extra spaces where Geeklog broke the source lines)

**Additional Information:** 
Note: I am reporting this as a user of a site running an unidentified version of Geeklog, as Geeklog does not report its version in its HTML output I cannot know the version affected, so the version number in this bug report is random guesswork!

[Mantis Bugtracker #1390](http://project.geeklog.net/tracking/view.php?id=1390)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 25 Sep 2011 07:55**

Looks like the linefeeds are removed by this line from COM_checkHTML():

    // Get rid of any newline characters
    $str = preg_replace( &quot;/\n/&quot;, &#039;&#039;, $str );

In addition to probably being wrong (as pointed out by jb), this is also using a regular expression where a simple string replace would be more efficient.

The forced addition of spaces is there to avoid people forcibly breaking the site layout by putting in loooo...ooong lines. There&#039;s probably no good compromise for those that will satisfy any use case. A solution (e.g. for ASCII art) could be to use the [code] and [raw] tags (need to double-check that they don&#039;t insert extra spaces either - they certainly shouldn&#039;t).

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
