### ISSUE TITLE
[Bugs] Censor Mode Exact Match not working properly

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#538]
**Reported by @eSilverStrike  on 23 Sep 2011 15:48**

**Version:** 1.8.0

**Description:**
These are the censor mode settings:

Censor submissions and comments (0 = Disabled, 1 = Enabled, exact matches, 2 = Enabled, match start of word, 3 = Enabled, match fragment)

Setting 1 (Exact Match) is not working as it is censoring the ass in Harassment (ie Har_censored_ment). I would think that is how setting 3 should work.

[Mantis Bugtracker #1392](http://project.geeklog.net/tracking/view.php?id=1392)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 3 Oct 2011 14:22**

Use to see how &quot;ass&quot; gets censored under the 3 options.

Censor Test

Individual Lines
Test
ass
Harassment 
assets
Geeklog

One Line
Test ass Harassment assets Geeklog

Punctuation
Test, ass, Harassment, assets, Geeklog

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 3 Oct 2011 14:42**

Censor submissions and comments (0 = Disabled, 1 = Enabled, exact matches, 2 = Enabled, match start of word, 3 = Enabled, match fragment)

Both censor mode 1 and 2 are now fixed. 

Mode 1 - Must be an exact match before censored
Mode 2 - Word must be exact match or begin with the text before censoring takes place
Mode 3 - Censoring takes place wherever word is found (includes Mode 1 and 2)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 8 Oct 2011 11:44**

Hmm, now when you put the offending word in &quot;quotes&quot; or (parens), it is no longer censored. Was that intended?

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 8 Oct 2011 14:57**

No that was not intended. I didn&#039;t think to test that situation though match fragment should censor this.

I guess exact match should censor something in quotes or at least starts with a quote.

What other punctuation, brackets, etc. should we worry about when dealing with exact match?

&quot;test&quot;
&#039;test&#039;
`test`
{test}
(test)
[test]
-test

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
