### ISSUE TITLE
[Feature Requests] topic.delete should be a separate right

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#54]
**Reported by hallomarkus on 11 Sep 2006 12:17**

**Description:**
topic.delete should be a separate right

**Additional Information:**
topic.delete should be a separate right

The right to delete a category / topic is very problematic as a non-tech user may not understand that he will also delete all stories. It would be more secure to be able to grant topic.edit rights to a user but not necessarily topic.delete

[Mantis Bugtracker #152](http://project.geeklog.net/tracking/view.php?id=152)

**Comment by mystralkk** [comment]
**Comment posted by hallomarkus on 9 May 2008 06:48**

geeklog 1

**Comment by eSilverStrike** [comment]
Old and outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
