### ISSUE TITLE
[Bugs] Advanced Search authors option selection list

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#544]
**Reported by Tsuchi on 4 Oct 2011 02:34**

**Description:**
The owner is the owner of the article(story) shows only.
For example, the owner of the static pages will not display.

[Mantis Bugtracker #1398](http://project.geeklog.net/tracking/view.php?id=1398)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 8 Oct 2011 11:23**

Yeah, this is something that hasn&#039;t been thought through properly but has always been this way: The list of authors is - and has always been - the list of *story* authors.

I guess we would need an API to get a list of &quot;authors&quot; from plugins.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
