### ISSUE TITLE
[Bugs] Authentication Required for Security Token has Expired

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#545]
**Reported by @eSilverStrike  on 6 Oct 2011 19:41**

**Version:** 1.8.0

**Description:**
I haven't fully tested this but if your security token has expired and you get the Authentication Required login form, this doesn't work with OAuth and probably the other user login methods.

With OAUTH, the save should either fail in this situation or we should query the OAUTH provider directly to reauthenticate the user.

[Mantis Bugtracker #1399](http://project.geeklog.net/tracking/view.php?id=1399)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 6 Oct 2011 19:54**

Yep, it doesn&#039;t work with OAuth, but should with the other methods. As stated on the wiki: http://wiki.geeklog.net/index.php/Re-Authentication_for_expired_Tokens#Known_Issues

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 7 Oct 2011 12:58**

Missed that :-)

Should we just fail the save then instead of showing the login screen if the user has logged through an OAUTH provider? (at least until we get the OAUTH part to work here)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 8 Oct 2011 11:24**

Can&#039;t remember the details, but I think it would be very hard to do a re-authentication with OAuth. So we should at least say that we can&#039;t do it ...

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
