### ISSUE TITLE
[Bugs] HTTP_OAuth_Consumer_Request lap and slow again.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#550]
**Reported by @ivywe on 10 Nov 2011 08:52**

**Version:** 1.8.1

**Description:**
Twitter OAuth:

Exception on tcp://api.tr.im:80
HTTP_Request2::request() HTTP_OAuth_Consumer_Request lap and slow again.
Because oauthhelper do nothing.

http://twitpic.com/7cfhtq

[Mantis Bugtracker #1406](http://project.geeklog.net/tracking/view.php?id=1406)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
