### ISSUE TITLE
[Bugs] FCKeditor doesn't work properly with IE9

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#564]
**Reported by @mystralkk on 1 Feb 2012 11:46**

**Version:** 1.8.1

*_Description::_
When you try to insert a link or an image with FCKeditor, a popup window opens and you enter necessary information. However, with Internet Explorer 9 (standard mode), after these windows open, they freeze and you can do nothing with them.

A workaround is to add the following line between the &lt;head&gt; and &lt;/head&gt; tags of "header.thtml"

&lt;meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8"{xhtml}&gt;

[Mantis Bugtracker #1420](http://project.geeklog.net/tracking/view.php?id=1420)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 1 Feb 2012 15:50**

I notice this issue as well.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 23 Feb 2013 18:08**

Not sure if it helps (can&#039;t test it), but there&#039;s an FCKeditor version 2.6.9 that notes fixes for IE10 (yes, I know - 10, not 9). Updated in the repository.

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 2 Mar 2013 17:05**

Tested and it didn&#039;t fix the issue.

**Comment by mystralkk** [comment]
**Comment posted by dengen on 10 Mar 2013 05:09**

I noticed FCKeditor version 2.6.9 doesn&#039;t work properly with IE10 on Windows8.
On the contrary, even Post Mode switcher:(

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 10 Mar 2013 14:34**

Ack... another reason to switch to to CKEditor I guess.  Did the older FCKeditor work on IE10?

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 10 Mar 2013 14:56**

FCKeditor 2.6.9 came out in December 2012, i.e. it&#039;s not that old. I&#039;m surprised it would be causing problems with IE 10.

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 11 Mar 2013 00:39**

It looks like it should work as it is IE10 is mentioned here:

http://ckeditor.com/forums/Announcements/FCKeditor-2.6.9-Released

Here is the full post:

We would like to inform you that an update to FCKeditor has just been released. This is a security release that contains a fix for two recently reported issues:
â¦(ASP) File Upload Protection Bypass - reported by Soroush Dalili (@irsdl), Mostafa Azizi
â¦XSS vulnerability in built-in file manager - reported by Soroush Dalili (SecProject.com)
 
Also in this version the detection of IE10 and Firefox17+ has been fixed.

Please note FCKeditor is a retired and no longer supported product. No further updates will be provided and it is highly recommended to upgrade to its successor, CKEditor, that is a far superior, feature-rich and mature product.

**Comment by mystralkk** [comment]
**Comment posted by dengen on 11 Mar 2013 14:31**

Maybe we should switch to CKEditor.
It seems there are no licensing problems.
We can use the CKEditor under the GPLv2.

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 12 Mar 2013 00:12**

Since the final release of Geeklog 2.0.0 is just a few weeks off and we are in a feature freeze we should wait.

If there are not licensing issues then we should plan to make the switch for Geeklog 2.0.1 (if not CKEditor then something else but to me it would be the logical choice).

This way we can also warn plugin developers that as of Geeklog 2.0.0 it will be the last release with the FCKEditor.

**Comment by mystralkk** [comment]
**Comment posted by mystralkk on 12 Mar 2013 06:34**

I would like to integrate CKEditor (licensed under GPL2) and Filemanager (licensed under MIT, https://github.com/simogeo/Filemanager ).  Besides, I hope to reorganize and improve JavaScript code, such as decreasing global variables.

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 12 Mar 2013 13:28**

That&#039;s good. Would the filemanger be for the CKEditor?  I know the Scripts class needs a few updates as well (http://project.geeklog.net/tracking/view.php?id=1459)

After Geeklog 2.0.0 is released I will probably continue to work on the forum to get the final out. One of the projects I want to work on after that is the session handler. Building the topic tree array on every page load is expensive and would be better if we could store it in a session variable.

We should continue this discussion on the developers mailing list so everyone sees it.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 12 Mar 2013 13:38**

I think the main reason why we didn&#039;t switch to CKeditor immediately was that back then there was no file manager with a compatible license. So if there is one now, I don&#039;t see why we shouldn&#039;t switch.

But that&#039;s going to be after the 2.0.0 release, as Tom said.

In the future, I&#039;d like to explore other options for editors, e.g. Aloha, but that&#039;s more of a research (or possibly GSoC) project.

So, I guess it&#039;s FCKeditor &quot;as is&quot; in 2.0.0, and CKeditor in 2.0.1

**Comment by mystralkk** [comment]
**Comment posted by dengen on 12 Mar 2013 14:25**

I get the point. I&#039;m looking forward to 2.0.1 with CKEditor and Filemanager.

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 16 Mar 2013 16:59**

I have search around the net and tried a few fixes to get it to work but beyond the initial suggestion of adding

&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=EmulateIE8&quot;{xhtml}&gt;

or turning on compatibility view in IE10 I can&#039;t get it to work. As Dengen mentioned switching post mode in IE 10 to Advance Editor in Stories doesn&#039;t work either. 

So I guess at this point when we release Geeklog 2.0.0 next week I will have to mention this issue and the work arounds.

Hopefully we can get the CKEditor integrated soon along with the updates to the scripts class. Once that is done I think we should go ahead and release Geeklog 2.0.1

**Comment by mystralkk** [comment]
**Comment posted by mystralkk on 30 Jan 2014 11:01**

I tested with the current changeset 263529fefbf7 and the result is this:

                        IE7  IE8  IE9  IE10  IE11
-------------------------------------------------
CKEditor                 X    O    O     O     O
CKEditor + Filemanager   X    O    O     O     O
FCKeditor                X    O    O     X     X
FCKeditor + Filemanager  X    O    X     X     X
Filemanager (from C&amp;C)   O    O    O     O     O
-------------------------------------------------

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 31 Jan 2014 12:04**

Hmmm... Where should we store this information wiki or doc? We should also include the version numbers of the components.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
