### ISSUE TITLE
[Feature Requests] Remote Service User Email Address and Deleting Account

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#565]
**Reported by Laugh on 1 Feb 2012 15:49**

**Version:** 1.8.1

**Description:**
Remote Service Users should re-authenticate when changing/adding email address or deleting account.

[Mantis Bugtracker #1421](http://project.geeklog.net/tracking/view.php?id=1421)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
