### ISSUE TITLE
[Feature Requests] A button on a story "subscribe this topic" for better usability 

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#57]
**Reported by hallomarkus on 26 Sep 2006 07:15**

**Description:**
A button on a story "subscribe this topic" for better usability

**Additional Information:**
One of the key features of GL over other blogs ist the possibility to subscribe topics. 
This is hardly visible to the user. Therefore it would be helpful to have a button on a story "subscribe this topic" next to "send to a friend" and "print version".
It would help improve the general usability of GL as discussed here: http://www.geeklog.net/forum/viewtopic.php?showtopic=66100
(Note that this thread above is less on "multiple categories per article" than on usability in general.)

[Mantis Bugtracker #154](http://project.geeklog.net/tracking/view.php?id=154)

**Comment by mystralkk** [comment]
**Comment posted by hallomarkus on 9 May 2008 06:49**

geeklog 1

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 29 Jun 2008 09:24**

Seems simple enough. Quick&#039;n&#039;dirty version:

        if ($_CONF[&#039;backend&#039;] == 1) {
            $tid = $story-&gt;displayElements(&#039;tid&#039;);
            $result = DB_query(&quot;SELECT filename, title FROM {$_TABLES[&#039;syndication&#039;]} WHERE type = &#039;geeklog&#039; AND topic = &#039;$tid&#039; AND is_enabled = 1&quot;);
            $feeds = DB_numRows($result);
            for ($i = 0; $i &lt; $feeds; $i++) {
                list($filename, $title) = DB_fetchArray($result);
                $feedUrl = SYND_getFeedUrl($filename);
                $feedTitle = &quot;Subscribe to &#039;&quot; . $title . &quot;&#039;&quot;;
                $story_options[] = COM_createLink($feedTitle, $feedUrl);          
            }
        }       

(to go into article.php in 1.5.0, after the &quot;if ($_CONF[&#039;pdf_enabled&#039;] == 1) ...&quot; block)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 4 Jul 2008 07:49**

The link should probably have a type attribute, e.g. type=&quot;application/rss+xml&quot;, just like the feed links in the site header.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 26 Jul 2008 16:26**

Implemented in CVS.

**Comment by mystralkk** [comment]
**Comment posted by hallomarkus on 9 Oct 2009 12:55**

Could this be reopened again? Meant was the possibility to subscribe topics by email.

Maybe there should be such a nice sign on the top of the topics like in the forum plugin &quot;subscribe this forum / thread&quot; -&gt; subscribe this topic.

**Comment by mystralkk** [comment]
**Comment posted by lwc on 9 Oct 2009 16:42**

To make such a common link possible, the second part of this request must be to put COM_emailUserTopics() by default in lib-custom.php&#039;s function CUSTOM_runScheduledTask() and put an on/off option in the GUI:

function CUSTOM_runScheduledTask() {
global $_CONF;
    if ($_CONF[&#039;emailUserTopics&#039;])
      COM_emailUserTopics();
}

Then again, I assume many would want a much less frequent interval for sending e-mail than the general one. Therefore, it might be better to add a unique scheduler for this in lib-common.php:

// Check and see if there are any new stories to send
if ($_CONF[&#039;emailUserTopics_schedule_interval&#039;] &gt; 0) { // 0 means off and &gt; 0 should probably be measured in days
    if ((DB_getItem($_TABLES[&#039;vars&#039;], &#039;value&#039;, &quot;name=&#039;emailUserTopics_scheduled_run&#039;&quot;)
            + $_CONF[&#039;emailUserTopics_schedule_interval&#039;]) &lt;= time()) {
        DB_query(&quot;UPDATE {$_TABLES[&#039;vars&#039;]} SET value=UNIX_TIMESTAMP() WHERE name=&#039;emailUserTopics_scheduled_run&#039;&quot;);
        COM_emailUserTopics();
    }
}

The latter solution would also not force admins to manually update their lib-custom.php file.

And let&#039;s not forget to fix the entire function in the first place: http://project.geeklog.net/tracking/view.php?id=997

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 29 Oct 2010 12:51**

There is some unused code in system/lib-user.php to subscribe/unsubscribe users to/from a topic, functions USER_subscribeToTopic + USER_unsubscribeFromTopic. The actual email would be delivered by the Daily Digest.

Missing: Add UI elements to allow the user to (un)subscribe. It&#039;s also a bit tricky to find a URL to redirect the user to when they click on such a UI element. There isn&#039;t really any room left in the URL scheme for article.php - so maybe redirect them to My Account (since the Daily Digest settings are also there)?

**Comment by eSilverStrike** [comment]
Outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
