### ISSUE TITLE
[Feature Requests] Support markdown as an input method for stories, comments, and other applicable locations

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#572]
**Reported by vinny on 17 Feb 2012 21:38**

**Version:** Future

**Description:**
Markdown is essentially a simplified version of some wiki formatting "languages". It's simple to use and its use is becoming more wide spread.

Information about markdown:
http://daringfireball.net/projects/markdown/
http://michelf.com/projects/php-markdown/

[Mantis Bugtracker #1428](http://project.geeklog.net/tracking/view.php?id=1428)

**Comment by eSilverStrike** [comment]
Outdated issue so closing.
