### ISSUE TITLE
[Bugs] Filemanagement incorrect handling of comments

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#603]
**Reported by remy on 1 Aug 2014 00:46**

**Version:** 2.1.0

**Description:**
Obviously one can disable comments for some download entries.
These entries show a link "create comment" (enabled) or none (disabled).
However, when the entry is browsed directly, the link "create comment" is always present and deadish.
This can be seen by clicking "geeklog" in the install page for bad behavior 2.
Steps To Reproduce  Look at http://bad-behavior.ioerror.us/support/installation/
Click geeklog
Redirects to https://www.geeklog.net/filemgmt/index.php/920

[Mantis Bugtracker #1775](http://project.geeklog.net/tracking/view.php?id=1775)

![comments](https://cloud.githubusercontent.com/assets/2015377/12219898/0e5c0d54-b79a-11e5-95ed-c06a4151a52b.png)

**Comment by eSilverStrike** [comment]
Issue doesn't belong here.
