### ISSUE TITLE
[Feature Requests] In order to make accessible, I want to add the role attributes.

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#609]
**Reported by milk54 on 2 Oct 2014 06:13**

**Description:**
In header part add role="banner". 
In navigation part add role="navigation".
In centerblocks part add role="main".
In footer part add role="contentinfo".

The file is header.html and footer.html.

[Mantis Bugtracker #1784](http://project.geeklog.net/tracking/view.php?id=1784)

**Comment by mystralkk** [comment]
**Comment posted by dengen on 24 Oct 2014 12:29**

I think this is a good opinion.
But HTML4.01 and XHTML1.0 doesn&#039;t support the role attributes.
In order to improve the Web accessibility of Geeklog, we need to migrate to HTML5.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
