### ISSUE TITLE
[Bugs] in the themes id's are mixed

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#610]
**Reported by remy on 10 Oct 2014 15:10**

**Version:** Future

**Description:**
The id 'text_editor' is used in 3 templates to identify a group.
The id 'advanced_editor' is used in 3 templates to identify a group.
The id 'advanced_editor' is used in 4 templates, one of them using the id for a input, the others to identify a group.
Whenever the templates will show in the same page, there is inconsistency.

These id's do not reference any css and their parent tags do have inline css.

**Additional Information:**
The templates: submitstory_advanced, storyeditor_advanced, commentform_advanced and displayblock.
The template 'editor' uses such id for a input field.

[Mantis Bugtracker #1785](http://project.geeklog.net/tracking/view.php?id=1785)

**Comment by mystralkk** [comment]
**Comment posted by dengen on 24 Oct 2014 13:48**

This is not a bug.
Among the multiple template files, it is possible to use the same id attribute name.
However, it is not permitted to use duplicate id attribute name, in one HTML document.

**Comment by mystralkk** [comment]
**Comment posted by remy on 14 Jan 2015 10:10**

Whenever the templates will show in the same page, there is inconsistency.
When it is not a bug, why is it true that you get fined with a faulty page?
Ex: a page to edit all comments in one go but submit individually.
Ex: a topic page with stories with the feature to pop a modal to edit one specific story.

**Comment by mystralkk** [comment]
**Comment posted by remy on 27 Mar 2015 11:07**

Dengen said: However, it is not permitted to use duplicate id attribute name, in one HTML document.

This must be read as: GL cannot combine mentioned core templates in a single HTML document.

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 27 Mar 2015 20:33**

True. 

The advanced editor has a bunch of common functions so multiple features can use it (like the comment submission form and the story editor). That is why these ids exist. 

You can&#039;t edit multiple items at once in Geeklog so these ids will never show up on the same html page.

**Comment by mystralkk** [comment]
**Comment posted by remy on 28 Mar 2015 00:31**

There is no necessity to promote form items with id&#039;s. 

Other problem id&#039;s are used in div&#039;s and are pointless. Making them a class is the way to go.

You can&#039;t edit multiple items at once but you can have multiple forms in one specific page, indeed.

**Comment by mystralkk** [comment]
**Comment posted by dengen on 28 Mar 2015 09:09**

remmy wrote:
&gt; You can&#039;t edit multiple items at once but you can have multiple forms in one specific page, indeed. 

If so, please present the specific case.

We always check the misuse of id for each page by using the W3C validation service (http://validator.w3.org/).
Also with respect to &#039;text_editor&#039; and &#039;advanced_editor&#039;, I couldn&#039;t find the duplicate use.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
