### ISSUE TITLE
[Bugs] Content Syndication - After you click, the changed sort order goes back to the initial state

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#614]
**Reported by @ivywe (Tsuchi) on 21 Nov 2014 05:18**

**Version:** 2.1.0

**Description:**
On the Content Syndication page, after you click, the sort order goes back to the initial selection.

The same applies to the following cases:
(2)Block Manager　ADMIN_getListField_blocks
(3)Trackback　ADMIN_getListField_trackback

**Steps To Reproduce:**
Content Syndication
1. "Type" Click
2. Change Type Decending Order 
3. Click on"Enabled" field
4. "Enabled field" change to "Unabled"
5. And the order change with titles descending

**Additional Information:**
For example, in system/lib_admin.php 
change $_GET['prevorder'] to $_REQUEST['prevorder'], $_GET['order'] to $_REQUEST['order']  and $_GET['direction'] to $_REQUEST['direction'] will fix this bug.

function ADMIN_list($component, $fieldfunction, $header_arr, $text_arr,
...
    if (isset ($_REQUEST['prevorder'])) { # what was the last sorting?
        $prevorder = COM_applyFilter ($_REQUEST['prevorder']);
    }

:
    if (!isset ($_REQUEST['order'])) {
        $order = $defsort_arr['field']; // no, get the default
    } else {
        $order_var = COM_applyFilter ($_REQUEST['order'], true);
...
    if (!isset ($_REQUEST['direction'])) { # get direction to sort after
        $direction = $defsort_arr['direction'];
    } else {
        $direction = COM_applyFilter ($_REQUEST['direction']);
    }

function ADMIN_getListField_blocks( 
...
        case 'is_enabled':
...
        $query_limit=COM_applyFilter($_REQUEST['query_limit']);
        $direction=COM_applyFilter($_REQUEST['direction']);
        $filter_val=COM_applyFilter($_REQUEST['filter_val']);
        $databoxlistpage=COM_applyFilter($_REQUEST['databoxlistpage']);
        $order=COM_applyFilter($_REQUEST['order'],true);
        $prevorder=COM_applyFilter($_REQUEST['prevorder']);
        $retval .= "<input type=\"hidden\" name=\"order\" value=\"$order\" />";
        $retval .= "<input type=\"hidden\" name=\"prevorder\" value=\"$prevorder\" />";
        $retval .= "<input type=\"hidden\" name=\"query_limit\" value=\"$query_limit\" />";
        $retval .= "<input type=\"hidden\" name=\"direction\" value=\"$direction\" />";
        $retval .= "<input type=\"hidden\" name=\"filter_val\" value=\"$filter_val\" />";
        $retval .= "<input type=\"hidden\" name=\"databoxlistpage\" value=\"$databoxlistpage\" />";
            }
            break;

[Mantis Bugtracker #1789](http://project.geeklog.net/tracking/view.php?id=1789)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
