### ISSUE TITLE
[Feature Requests] Static page and story: add ogp image

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#621]
**Reported by @ivywe on 14 Feb 2015 09:28**

**Version:** 2.1.1

**Description;**
meta tag ogp image in staticpage and story page is very important for SNS.

&lt;meta property="og:image" content="http://www.geeklog.jp/images/library/Image/logo/gmark.png" /&gt;

[Mantis Bugtracker #1798](http://project.geeklog.net/tracking/view.php?id=1798)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 14 Feb 2015 15:42**

I haven&#039;t really followed Open Graph.  Is it here to stay? I hate to implement something that goes away in a few years.

Plus should we implement other OG meta tags as well?

I am wonder if this would make a good plugin... 

We should create the ability in Geeklog to allow plugins to add their own fields to editors that support it (we could make the article editor, staticpage editor, etc.. support it)

We could add an api that allows a template variable to be populated in the editor template that would add any additional fields from plugins like this.  We would also have to include in the api the ability to: 

- Display the fields in editors for new and existing records
- check the fields for errors on preview and save (and back out of the save if need be
- Save/modify the fields
- Delete the fields
- Do something with the data from the fields when the actual item is displayed

I see this being useful for things like the tags plugin where instead of the user knowing how to deal with autotags, the tags plugin could just present the additional fields in the editor.

 
-

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
