### ISSUE TITLE
[Feature Requests] Static page: header and footer script

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#622]
**Reported by @ivywe on 14 Feb 2015 09:36**

**Version:** 2.1.1

**Description:**
staticpage set header {plg_headercode} footer {plg_footercode} per page.

admin pannel set 

id:
title:
meta description:
meta keyword:
meta og:image: <==== add
headercode: (any script text area) <==== add
footercode: (any script text area) <==== add

[Mantis Bugtracker #1799](http://project.geeklog.net/tracking/view.php?id=1799)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 14 Feb 2015 15:21**

For the header and footer code you could do this by adding php to the staticpage and accessing the scripts class.

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 14 Feb 2015 16:58**

Not all static pages.

for example:
http://takken-turumi.jp/staticpages/index.php/town
Only this page needs jQuery Datatables.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
