### ISSUE TITLE
[Bugs] Template if-logic not correct

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#624]
**Reported by remy on 20 Feb 2015 16:48**

**Description:**
When an {!!if logic is used, results show different results fir variables contain '0'.
Note the brackets in the if.

This works:

set_var('abc', '0')
{!!if {abc} > '0' !!}

But this don't:

set_var('abc', '0')
{!!if abc > '0' !!}

nor:

set_var('abc', '0')
{!!if abc > 0 !!}

[Mantis Bugtracker #1801](http://project.geeklog.net/tracking/view.php?id=1801)

**Comment by mystralkk** [comment]
Currently, Geeklog uses {!if } statemnet like {!if var} alone, not {!if some operation}.  How about moving the milestone of this issue to v2.2.0?

**Comment by eSilverStrike** [comment]
Is this really an issue? I understand it is a little confusing with the switch from requiring brackets for template variables in advanced action when compared to simple actions 

http://wiki.geeklog.net/Caching_Template_Library#Actions

Simple actions just contain the action and the variable so it is easy to determine the template variable.

With Advanced Actions template brackets are needed as we have no idea what is a template variable or not.

For example this line

{!!if abc > '0' !!}

abc could be either a global function that is being called or a global variable and not a template variable.
