### ISSUE TITLE
[Patches] Staticpages plugin template using UIkit

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#628]
**Reported by @ivywe on 8 Nov 2015 16:36**

**Version:** 2.1.1

**Description:**
Staticpages plugin template using UIkit

/templates/default/admin/editor.thtml, editor_advanced.thtml

[admin.zip](https://github.com/Geeklog-Core/geeklog/files/82713/admin.zip)
[admin20151115.zip](https://github.com/Geeklog-Core/geeklog/files/82711/admin20151115.zip)
[admin20151221.zip](https://github.com/Geeklog-Core/geeklog/files/82712/admin20151221.zip)
[templates_20160102.zip](https://github.com/Geeklog-Core/geeklog/files/82714/templates_20160102.zip)

[Mantis Bugtracker #1809](http://project.geeklog.net/tracking/view.php?id=1809)

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 2 Jan 2016 13:54**

sample style

.gl-edit:hover {
  backgraund: #e8e8e8 !important;
}
.gl-edit a.editlink img {
  filter: alpha(opacity=20);
  opacity: 0.2;
}
.gl-edit:hover a.editlink img {
  filter: alpha(opacity=100);
  opacity: 1.0;
}

**Comment by eSilverStrike** [comment]
Partially done already. Admin editor needs to be finished but should probably be done when all the core plugin editors are done to ensure uniformity. Reassigning to milestone 2.2.0

@dengen are you planning to update all the editors with a similar uikit styling for the denim theme? Or is this something you want me to do? (or someone else)

**Comment by eSilverStrike** [comment]
See #631

**Comment by dengenxp** [comment]
I'd like to apply UIkit styling more deeply to all Admin editors. Not with the Denim theme, but with the new Admin theme.
I want you to create a new git branch to develop the next version (version 2.1.2).

**Comment by eSilverStrike** [comment]
You should have permissions create the new git branch. Do we need one specifically for 2.2.0? Shouldn't you just do a new branch for the new admin interface?

You should write up a feature request in GitHub with your idea on the new admin so if anyone has any questions they can ask you. We could also take the small feature requests like this issue we are commenting on now and relate them to your new feature (if it makes sense to) and then close the small ones to clean things up a bit.

I plan on working on the blocks stuff in 2.2.0 (#706 and #707). I have to think on #707 for a bit to figure out how to best define one or more layouts for a theme. Once I have a better idea I will comment on the issue and ask for some feedback. I need to make sure things are backwards compatible.

**Comment by eSilverStrike** [comment]
Closed this issue and opened #845 regarding the separate Admin Theme idea.
