### ISSUE TITLE
[Feature Requests] Poll Plugin - Add Description, Multiple Answer Per Question, and Google Charts

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#629]
**Reported by @eSilverStrike  on 9 Nov 2015 14:12**

**Version:** 2.1.1

**Description:**
See Forum Post: https://www.geeklog.net/forum/viewtopic.php?showtopic=96100

Add @ivywe's hack on Polls plugin 2.1.5

https://bitbucket.org/tsuchi/polls_hack

 add description to theme and question.
 add multiple answer mode.

https://www.ossj.jp/polls/index.php?pid=programming2&aid=-1
 added Google Charts on theme.
 download:
 https://github.com/ivywe/geeklog-ivywe/
 add header.thtml

[Mantis Bugtracker #1810](http://project.geeklog.net/tracking/view.php?id=1810)

**Comment by mystralkk** [comment]
Implemented with charset fbbe804.  However, Google Charts is not easy to integrate into Geeklog, so it is not implemented so far.

**Comment by ivywe** [comment]
Thank you always for your hard work.
