### ISSUE TITLE
[Feature Requests] theme Denim

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#631]
**Reported by @ivywe on 12 Nov 2015 18:18**

**Version:** 2.1.1

**Description:**
use UIkit 

https://github.com/ivywe/Denim

functions.php
all js:
'footer' => true,

use uk-tooltip instead of gl-tooltip
use uk-pagination
use uk-form uk-form-horizontal

[Mantis Bugtracker #1812](http://project.geeklog.net/tracking/view.php?id=1812)

**Comment by eSilverStrike** [comment]
I agree regarding the frameworks in the footer. It's not good when you are seeing the site being built. There is a trade off for loading time and seeing content first but what's the point if what is visible is going to change when jquery is loaded.
