### ISSUE TITLE
Modify  theme Denim to make it easier for beginners to change logo, colors, and other features

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#632]
**Reported by @ivywe on 14 Nov 2015 18:10**

**Version:** 2.1.1

**Description:**
theme Denim add Off canvas and others

Denim theme:
https://github.com/ivywe/Denim/

demo:
http://demo.geeklog.jp/

[Mantis Bugtracker #1813](http://project.geeklog.net/tracking/view.php?id=1813)

**Comment by eSilverStrike** [comment]
Here are some things to think on when updating the denim theme in the future. 

These ideas would be nice to make modifying the theme easier to do (especially for beginners)

1) Changing the logo image. If the logo is the same size it is not a real problem but if the image dimensions are different it can be difficult to make sure it looks right in all viewports
2) Changing the base colors of the theme.

I also ended up adding  back in the touch interface for the blocks when viewing from certain devices (which keeps the block hidden except the title until the user clicks on the title).  I find this is really good for keeping the page from becoming to long when viewing from a device like the phone. For this it would also be great if we could use this feature for some blocks but not others (like the search or topics block for example).

Some of this will be hard to do with just style sheets.. maybe we will have to add some php code to Geeklog (or a plugin) to make it all work (and possibly work with other themes). If needed I can help you out on this when everyone gets some time. I added these points to feature request #632 so we have a place to discuss it further as needed.

**Comment by dengenxp** [comment]
@eSilverStrike About idea 1,2:
What kind of tool (or mechanism) are you thinking to modify the Denim theme for beginners? I can not imagine it.
If you can challenge to rebuild from the stylus source code, it is pretty easy. Just rebuild after replace the logo image file and slightly changing the config file.
I will be able to provide this method as a document in a bit more detail.

**Comment by eSilverStrike** [comment]
Documentation would help but I am thinking more of the average website admin who knows very little about html and how it all works. This tool would help them.

What I don't want to do is by adding things to make it easier for the end user, it makes it much harder for you to work on/upgrade the theme in the future.

I also don't know the best way to do this either. I haven't done much research. I currently see 2 options though:  

Option 1) We create a plugin or something that can update the custom.css file with changes to the base default styles of the theme. Hopefully this could be setup to used with other themes at some point.

Option 2) Use template variables to either insert predefined css classes or custom styles directly into the element. This could be setup either in the funcitons.php or as a separate plugin (or both). It would also be nice here if we could add more style functionality to blocks by allowing in the block editor to add id's to the block and extra css classes (these would be added by template variables as well). This functionality could be used by other themes as well if supported.

For both options obviously most themes have  a predefine set of common objects (header,footer, left blocks, right blocks). In a way you sort have already started this process with your options array (like the 'uikit_theme' option).

For example we could have options like:
Header Wrapper
- Background: (list of predefined Styles)
- Use custom background color: Yes/No
- Custom background color: color picker
- Content 100% width Yes/No

I like option 2 better and we could start small get the frame work in and add extra configurable options as we go. (like the logo, and maybe even layout options).

These are just ideas of mine and if anyone has a better solution I would love to hear it :-).

With the next version of Geeklog (2.2.0) we will be dropping support for COM_SiteHeader and COM_SiteFooter. This would be an ideal time to also update the way we handle blocks and their location on the page. It would be nice to either have more areas (ie Header, Footer, Left, Right) or better yet allow the theme to define their own locations. This is something separate from this feature request though as it will create it's own set of issues. I will add in it's own feature request for it.

**Comment by eSilverStrike** [comment]
See #631 as well which references other feature requests

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
