### ISSUE TITLE
[Bugs] Theme Denim Icon ... /fonts/ link error

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#634]
**Reported by @ivywe on 19 Nov 2015 13:44**

**Version:** 2.1.1

**Description:**
Icon does not display.

example:
<i class="uk-icon-file-archive-o">

../fonts/ link error from /layout/denim/style.css.php

[Mantis Bugtracker #1815](http://project.geeklog.net/tracking/view.php?id=1815)

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 19 Nov 2015 15:12**

Not sure where this is coming from...

I check both the forum and Geeklog. They only use:

uk-icon-file-text-0
uk-icon-file-0

Could this be an error from another plugin?

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 19 Nov 2015 15:45**

This is Denim UIkit error.

now functions.php set uikit.css

{site_url}/layout/denim/style.css.php link ../fonts/ 
but not exist.

realy exist
{site_url}/vendor/uikit/fonts/


idea:
remove uikit.gradient.css in functions.php
add uikit.gradient.css in header.thtml

or


uikit.gradient.css:

from:
@font-face {
  font-family: &#039;FontAwesome&#039;;
  src: url(&quot;../fonts/fontawesome-webfont.woff2&quot;) format(&#039;woff2&#039;), url(&quot;../fonts/fontawesome-webfont.woff&quot;) format(&quot;woff&quot;), url(&quot;../fonts/fontawesome-webfont.ttf&quot;) format(&quot;truetype&quot;);
  font-weight: normal;
  font-style: normal;
}
to:
@font-face {
  font-family: &#039;FontAwesome&#039;;
  src: url(&quot;/vendor/uikit/fonts/fontawesome-webfont.woff2&quot;) format(&#039;woff2&#039;), url(&quot;/vendor/uikit/fonts/fontawesome-webfont.woff&quot;) format(&quot;woff&quot;), url(&quot;/vendor/uikit/fonts/fontawesome-webfont.ttf&quot;) format(&quot;truetype&quot;);
  font-weight: normal;
  font-style: normal;
}

**Comment by mystralkk** [comment]
**Comment posted by Laugh on 23 Nov 2015 14:35**

Okay, I will let Dengen handle this. I sent him an email about it.

**Comment by mystralkk** [comment]
**Comment posted by dengen on 24 Nov 2015 13:23**

There was no problem with my test.

Originally, it doesn&#039;t exist style.css.php in the Denim theme directory.
I guess the problem was caused by your customizations.

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 24 Nov 2015 14:27**

Sorry.
It&#039;s my mistake.
Denim does not use style.css.php

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 13 Dec 2015 17:21**

When functions.php function theme_config_XXX() &#039;etag&#039; =&gt; true, and add style.css.php,
problem occurs in all theme.

**Comment by mystralkk** [comment]
**Comment posted by Ivy on 14 Dec 2015 11:25**

So this is caused by style.css.php.

Laugh, Feature request:
style.css.php change relative URL to absolute URL.

**Comment by dengenxp** [comment]
The ETag and style.css.php are now supported with the Denim (and Denim Curve) theme with changeset 829f268.
Dynamic conversion of URL is not cool. So I solved it by changing style.css.php and fonts placement.

**Comment by dengenxp** [comment]
It is true that an error occurs when using UIkit with the Modern Curve theme and its style.css.php.
But if you do it like the way in the Denim theme, you can solve it. I have the code that demonstrated this.

**Comment by eSilverStrike** [comment]
Was this fixed?

**Comment by dengenxp** [comment]
Only for Denim theme, this issue was fixed. That alone may have been enough to close this page.
