### ISSUE TITLE
[Feature Requests] style.css.php change relative URL to absolute URL and add Stylus to style.css.php

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#637]
**Reported by @ivywe on 14 Dec 2015 12:29**

**Version:** 2.1.2

**Description:**
style.css.php change relative URL to absolute URL.

example ../fonts/... -> /vendor/uikit/fonts/...

and add stylus

@dengenxp  use Stylus for denim theme.
1. Stylus can include css file.
2. Stylus can use SASS code.
   ...
   only use node.js

[Mantis Bugtracker #1818](http://project.geeklog.net/tracking/view.php?id=1818)

**Comment by mystralkk** [comment]
I don't think style.css.php is a good solution to make a final CSS file.  Combining CSS files into one and/or minifying the file should happen before Geeklog is shipped, with Grunt or Gulp on node.js. 

The first reason is what style.css.php does is minimal and is far inferior to things you can do with Grunt or Gulp.  Why not just use node.js for such tasks?

The second reason is there is no good Stylus-to-CSS compiler powered by PHP.  It is true that there are some such compilers like https://packagist.org/packages/neemzy/stylus , but these products cannot handle @dengenxp 's source files well.  Again, why not use node.js?

**Comment by eSilverStrike** [comment]
We should also try to include any css files from plugins as well so the site will load just 1 css file (which I don't think style.css.php does). This obviously has to be done at some point on the live site and be cached.

**Comment by dengenxp** [comment]
I think the effect of ETag and style.css.php is very small for the Denim theme. But I decided to support them. These were added with changeset 829f268.
