### ISSUE TITLE
[Feature Requests] Disable Search and Advanced Search Automatic Topic Selection

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#640]
**Reported by @eSilverStrike  on 20 Dec 2015 19:38**

**Version:** 2.1.1

**Description:**
If a user is in a topic (ie either viewing an article or staticpage assigned to the topic) and they then do a search (or advanced search), the search will automatically search only that topic (and sub topics). 

A lot of users are confused by this as they think they are searching the entire site.

Let's either disable this automatic search topic selection feature completely or make it a configurable option.

[Mantis Bugtracker #1822](http://project.geeklog.net/tracking/view.php?id=1822)

**Comment by eSilverStrike** [comment]
Added new config option search_use_topic to make this feature configurable.
