### ISSUE TITLE
[Feature Requests] Update UIkit from Version 2.24.0 to Version 2.26.2

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#641]
**Reported by @ivywe on 21 Dec 2015 03:12**

**Version:** 2.1.2

**Description:**
Update UIkit from Version 2.24.0 to Version 2.24.3

[Mantis Bugtracker #1823](http://project.geeklog.net/tracking/view.php?id=1823)

**Comment by eSilverStrike** [comment]
Actually updated to 2.26.2. Changed title.
