### ISSUE TITLE
[Feature Requests] add ogp:image url : Story, Staticpages

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#644]
**Reported by @ivywe on 31 Dec 2015 05:19**

**Version:** 2.1.2

**Description:**
add ogp:image url : Story, Staticpages

for thumbnail, ogp image for social site.

[Mantis Bugtracker #1826](http://project.geeklog.net/tracking/view.php?id=1826)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
