### ISSUE TITLE
[Bugs] Cannot delete topics with Postgresql 9.4.5 / Geeklog 2.1.1

### ISSUE THREAD

**Issue by dragontamer** [Geeklog-Core/geeklog#647]
I've installed "geeklog-2.1.1.tar.gz" and am running Postgres on a small Linode VPS. I plan to use this as my blogging engine.

My current version of PostgreSQL:

psql --version
psql (PostgreSQL) 9.4.5

Basically, when I tried to delete a topic, the following error comes up (http://imgur.com/2LLzth2). I fixed this issue by changing line 759 of public_html/admin/topic.php to:

        $sql = "SELECT {$object_tables_id[$object_table]}, ta.tdefault
            FROM $object_table, {$_TABLES['topic_assignments']} ta
            WHERE ta.type = '{$object_type[$object_table]}' AND ta.id = cast({$object_tables_id[$object_table]} as varchar) AND ta.tid = '$tid'";

The important tidbit is "cast({...} as varchar)", because PostgreSQL seems to be a bit more strict when it comes to types than MySQL.

Good luck, and thanks for the blogging software,

**Comment by eSilverStrike** [comment]
Thanks Dragontamer for the fix. None of the Geeklog Team has PostgreSQL installed (we all use MySQL) so you may come across some more sql errors. When you do please let us know along with the fix and we will include the fix in the next release.

**Comment by mystralkk** [comment]
Fixed with changeset 253a7c8.  Thanks!
