### ISSUE TITLE
[Bugs] Postgresql Issue in 'Batchdelete' causes crash in Geeklog 2.1.1

### ISSUE THREAD

**Issue by dragontamer** [Geeklog-Core/geeklog#648]
Hey again, reporting another Postgresql casting issue.

At the location: "admin/user.php?mode=batchdelete", the page fails to even load because of another "cast" issue. This time, it is on the "gl_userinfo.lastlogin" field.

lastlogin = 0

In essence, the "$filter_sql" variable of /public_html/admin/user.php needed to be tweaked with "cast(0 as varchar)", as described in issue #647. Specifically, the SQL value "lastLogin" is a varchar, and in Postgres gets a type-error when varchars are compared against integers (like 0). Here's my diff:

[diff.txt](https://github.com/Geeklog-Core/geeklog/files/91527/diff.txt)

I was able to batch-delete a bunch of spam users after I applied these fixes.

--Dragontamer

**Comment by mystralkk** [comment]
Fixed with changeset 013ce11.  Thanks!
