### ISSUE TITLE
[Bugs] Postgresql Issue in 'moderation.php' causes crash in Geeklog 2.1.1

### ISSUE THREAD

**Issue by dragontamer** [Geeklog-Core/geeklog#649]
Hey,

Sorry, no fix this time. I'll give it another whack maybe in a day or two. For now, here's the screenshot of my error.

![Error](https://cloud.githubusercontent.com/assets/3312438/12349276/520e6ff6-bb3c-11e5-9a78-dac764f42e7e.png)

This occurs in "http://site/admin/moderation.php"

--Dragontamer

**Comment by dragontamer** [comment]
Actually, I just "fixed" it with the dirtiest way possible.

I was trying to figure out where $A['id'] came from in "system/lib-admin.php", but I think I can trust your logic as working in MySQL. I'm assuming MySQL is just loose with types again, so I "fixed" this issue by casting cid into a varchar (so that it will be a string-comparison between the two values).

I dunno if the logic is still sound, but the moderation page actually pops up. I'm thinking yall will need a closer look to tell whether or not this fix is "legitimate" in the long term.

Line 1613 of "/system/lib-admin.php":

            $name = htmlspecialchars(COM_stripslashes(DB_getItem($_TABLES['commentsubmissions'], 'name', "cast(cid as varchar) = '{$A['id']}'")));

**Comment by eSilverStrike** [comment]
The moderation handles all types of submissions from articles, comments, users, ratings, etc... Some ids are automatically generated by the system (like comments and users) are usually numeric while others that can be changed by the user (like for stories) are varchar. I believe the moderation at one time handled only 1 object type but has grown to handle any (before my time). 

Your cast might be the best option but we will confirm when we take a closer look.

**Comment by mystralkk** [comment]
Fixed with changeset 4201ca5
