### ISSUE TITLE
[imageX] tags not expanded in RSS etc. feeds

### ISSUE THREAD

**Issue by dhaun** [Geeklog-Core/geeklog#651]
This is something that seems to have changed at some point between 1.8.2 and 2.1: Articles that use the [imageX] or [unscaledX] tags for images uploaded within Geeklog will show up with those tags verbatim (not expanded). So in an RSS reader, you would see something like [image1] instead of the image.

![feedly-screenshot001](https://cloud.githubusercontent.com/assets/16507691/12390787/58421cca-bde3-11e5-8aeb-ad5147436db0.png)

**Comment by eSilverStrike** [comment]
I took a look at this along with Geeklog 1.8.1 code and it looks like the images wouldn't have been returned in the feed back then either.

The syndication code pulls the story text right from the database applies the autotags and a few other things and then writes it to the file.

The only code that actually render's the images for stories is the story class. It looks like the syndication library file never used the story class.
