### ISSUE TITLE
[bug] Postgresql Issue when 'members' try to change password

### ISSUE THREAD

**Issue by dragontamer** [Geeklog-Core/geeklog#654]
I haven't had the time to investigate this one yet. So just reporting in on this issue. 

![untitled](https://cloud.githubusercontent.com/assets/3312438/12453786/d22135fa-bf62-11e5-9358-afd73f424232.png)

In this case, "40" is the uid of the 'test' user account that I made to investigate the issue.

This one looks a bit more serious: Postgres doesn't have a "proper" replacement to MySQL REPLACE INTO until Postgres 9.5. (My Debian machine only has Postgres9.4). The logic of system/databases/pgsql.class.php looks like it is trying to handle this case, but clearly there's something going on here specifically.

Strangely enough, the Admin user (uid=1) can change the password just fine. Its just the later users where the issue comes up in (in this case, "test" user is uid 40). I don't know if that is related.

I'll investigate more later.

**Comment by dragontamer** [comment]
The issue is line 469, where the following SQL statement is executed:

DELETE FROM gl_userindex WHERE uid='40' AND noboxes='0' AND maxstories='0';

The delete should really only be over uid='40', since uid is the only column that makes up the primary key. I think the statement on line 404 is buggy.

**Comment by dragontamer** [comment]
As expected, (one of the very many) SQL statements was buggy. By adding the line "AND pg_index.indisprimary", the SQL statement on line 403 through 409 uses PostgreSQL's reflection features to figure out which of the columns are an index (under the current implementation in 2.1.1).

I added a line for "pg_index.indisprimary" so that the SQL statement selects which columns are the primary key (which now more closely mimics the behavior of MySQL's REPLACE INTO statement). Overall, the general function is a hack-job, which will likely [done incorrectly](http://www.depesz.com/2012/06/10/why-is-upsert-so-complicated/).

In particular, I'm unsure if the current implementation handles the case where two different "dbsave" function calls happen in parallel over the same data. At least in this case (where a single user's password is changed), this is unlikely. In any case, the PostgreSQL 9.5 "Upsert" feature is the easiest solution, but requires PostgreSQL 9.5 or higher.

Here's my diff.

[diff.txt](https://github.com/Geeklog-Core/geeklog/files/104247/diff.txt)

**Comment by mystralkk** [comment]
Fixed with changeset 3c604ec
