### ISSUE TITLE
Drop Support for COM_siteHeader and COM_siteFooter

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#657]
It is time to remove the depreciated functions 

COM_siteHeader
COM_siteFooter

and make the COM_createHTMLDocument the required function for creating a Geeklog Page.

**Comment by mystralkk** [comment]
I replaced COM_siteHeader and COM_siteFooter in admin/install/success.php with COM_createHTMLDocument.

**Comment by mystralkk** [comment]
Removed both functions with changeset 58ab32c

**Comment by eSilverStrike** [comment]
I was going to ask if we wanted to do this still for 2.2.0. 

I guess we should figure out a list of incompatible plugins and get those fixed and released before Geeklog 2.2.0

If @Dengen is not around we may have to update his as well.

Ban
Gus
Searchrank
nettools
smiles
faq
Media Gallery
Downloads

**Comment by mystralkk** [comment]
It will be quite some time before 2.2.0 is out, so we could update incompatible plugins on https://github.com/Geeklog-Plugins .  By the way, when do you think you are going to bring out 2.2.0?

**Comment by eSilverStrike** [comment]
I am not sure, we have been rolling along with the changes right now which is great but with no news about Dengen means we are one less person. Hopefully Ivy will find out more.

Last year we released Geeklog 2.1.3 in June. I think that would be a good target for this year with some RC and betas released in the months before hand. What do you think?

I'll start a new Geeklog issue with a list of plugins we think we need to update. We can edit the list as the change has been made and the release for the plugin has happened

**Comment by mystralkk** [comment]
The due date on the top of 2.2.0 milestone page ( https://github.com/Geeklog-Core/geeklog/milestone/43 ) says December 31, 2017, so I thought 2.2.0 will have been out by February or March, 2017 and am focusing hard on fixing issues these days.

**Comment by eSilverStrike** [comment]
Okay that would be even better (I wasn't sure about your schedule). Let's try for early March then with some RC's in late Jan, and Feb.

Sound good?

**Comment by mystralkk** [comment]
Sounds good to me.
