### ISSUE TITLE
Make Editior Image library folder customisable

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Core/geeklog#660]
Previously the setting for FCKeditor library was made in the public_html/siteconfig.php file
$_CONF_FCK['imagelibrary'] = '/images/custom_folder/library';

Now this setting is not honored. See this post https://www.geeklog.net/forum/viewtopic.php?showtopic=96252

**Comment by mystralkk** [comment]
Implemented with changeset 52f150a
