### ISSUE TITLE
Postgresql Issue: Users can't post comment to some topics

### ISSUE THREAD

**Issue by dragontamer** [Geeklog-Core/geeklog#661]
Another Postgresql bug. Fortunately, I've been able to fix them approximately as quickly as I can find them. Today, I'm just gonna note the error.

![untitled](https://cloud.githubusercontent.com/assets/3312438/12634837/352b5e8a-c54b-11e5-8335-c313440607a4.png)

I should note that I added a few debugging print statements to pgsql.class.php, so don't expect the above line number (753) to line up with your code. The real issue seems to be in the pg_query which has the "SELECT NEXTVAL $sequence", inside of the function "dbInsertId". When I get rid of the at-sign (@) in front of pg_query, the following error pops up:

![untitled2](https://cloud.githubusercontent.com/assets/3312438/12634971/5bc6e0fe-c54c-11e5-900d-179c50829b24.png)

This suggests that there is some sort of "transaction" issue going on. The "system/lib-comment.php" has a "DB_lockTable" call and "DB_unlockTable" call, which differs in the following way:

* MySQL (ie: system/databases/mysqli.class.php), the "dbLockTable" function actually locks the table (LOCK TABLES $table WRITE), line 735.

* PostgreSQL, the function "dbLockTable" starts a transaction instead.

PostgreSQL can lock a table, just like MySQL. I'll experiment with some stuff and let you guys know if anything in particular works.

**Comment by mystralkk** [comment]
Fixed with changeset c0bfb9d
