### ISSUE TITLE
Admin Submissions Page  and Titles for Submissions

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#666]
When you view the admin submissions page If the title of a submission contains a valid html extension like :

"Staticpages.PHP Formmail"

then it will be converted to a clickable link.

For this bug I notice it with the downloads plugin submission and the above title which linked to 

"http://staticpages.php/"

I assume this will happen with other types of submissions and extensions like html, etc...

**Comment by eSilverStrike** [comment]
Just realized this is because of the Geeklog Config settings "Make URLs clickable?" (clickable_links)

It shouldn't be making .php file names clickable unless an actually link with a domain.

Maybe this is happening due to change in what Geeklog allows as a domain extension?

**Comment by dhaun** [comment]
And what if, one day, there was a .php top level domain?

But I thought COM_makeClickableLinks required things to start with http[s] or ftp[s] to make them clickable? Did that change recently?

**Comment by eSilverStrike** [comment]
I had wondered that as well re the .php domain.

Re COM_makeClickableLinks - not that I remember...

**Comment by mystralkk** [comment]
COM_makeClickableLinks DOES convert what looks like a doman.  From lines 6546-6554 of lib-common.php:

    // Matches anything containing a top level domain: xxx.com or xxx.yyy.net/stuff.php or xxx.yyy.zz
    // list taken from: http://en.wikipedia.org/wiki/List_of_Internet_TLDs
    $regex = '/(?<=^|[\n\r\t\s\(\)\[\]<>";])((?:[a-z0-9]+\.)*[a-z0-9-]+\.(?:[a-z]{2,}|xn--[0-9a-z]+)(?:[\/?#](?:[^\n\r\t\s\(\)\[\]<>"&]+(?:&amp;)?)*)?)(?=[\n\r\t\s\(\)\[\]<>"&]|$)/i';
    $replace = create_function(
        '$match',
        'return COM_makeClickableLinksCallback(\'http://\', $match[1]);'
    );

    $text = preg_replace_callback($regex, $replace, $text);

Should we remove this part of the code?

**Comment by eSilverStrike** [comment]
I think we should convert domains only if they start with http[s] or ftp[s] or, when someone lists a file name with an extension we are going to run into this problem.

**Comment by mystralkk** [comment]
Well, I will remove the part of the code in question.

**Comment by mystralkk** [comment]
Fixed with change set 5429a86
