### ISSUE TITLE
Can't use security features in theme ini

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Core/geeklog#667]
We can't use SEC_hasRights in theme ini (layout/mytheme/functions.php). 
$_RIGHTS are not yet available

**Comment by eSilverStrike** [comment]
It looks like loading the theme functions, etc... is done right before the user stuff. I don't see any reason not to switch the code around.

**Comment by hostellerie** [comment]
Yes, like this we can give theme features to VIP ;)
