### ISSUE TITLE
[Feature Requests] Allow the customisation of the events block name

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Core/geeklog#669]
Today the name of the events block is store in the language file. Make it possible to change the name in the calendar config would be a nice feature.

**Comment by eSilverStrike** [comment]
We could do that but it would override all language files.

It would be nice to figure out a way to have a general language override feature which would work for any specified language array and element and have it stored in the database.

**Comment by hostellerie** [comment]
What do you think about to give the opportunity to only override the site language if the name is not blanck in the calendar config?

**Comment by mystralkk** [comment]
I Implemented a generic language override feature with change set 8a6f70a.  It allows you to override any language item.
