### ISSUE TITLE
Title to id change when updating title

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Core/geeklog#670]
Maybe it is a feature maybe it is a bug. If it is a feature, I would like the ability to not change the title automaticaly when editing an article. I was using the attach script with  purepro theme in witch the story ID was checked to avoid this issue. 
[title2id.js.txt](https://github.com/Geeklog-Core/geeklog/files/170508/title2id.js.txt)

**Comment by eSilverStrike** [comment]
Yeah that is a bit if a pain. It should have changed the ID on a new article but after a save (ie you are now editing the article) it should not.

**Comment by mystralkk** [comment]
Fixed with change set d8b0e08
