### ISSUE TITLE
Feature: Email notification when a user updates his profile

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#674]
Add a config option which when enabled will notify the admin when any user updates their profile information. (similar message for a new user)

I am submitting this feature to help admins combat url spam where the only reason someone joins a website is to post their website.

**Comment by mystralkk** [comment]
I don't think a new config option is needed.  When $_CONF['notification'] includes 'user' in its value, just check for users updating their profiles as well?

**Comment by eSilverStrike** [comment]
Sounds good.

**Comment by mystralkk** [comment]
I implemented with change set c8c6a5c.  Have a look at it and close this issue if it looks fine.

**Comment by eSilverStrike** [comment]
Thanks! I added a small bug fix to the user link in the email and included a separate notification for it just incase some Geeklog Admins don't want to be notified. I added some more info to the notifications config option in the English config doc file. Can you update the Japanese version and close this issue?

**Comment by mystralkk** [comment]
Sure. Thanks!
