### ISSUE TITLE
Absolute urls for images with ckeditor and file manager

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Core/geeklog#676]
I'm looking for a solution. This should be on by default https://www.geeklog.net/forum/viewtopic.php?showtopic=96321

**Comment by mystralkk** [comment]
If Filemanager returns absolute URLs, then it will cause trouble when you migrate your site.  Instead, how about letting COM_emailUserTopics, which is responsible for sending daily digests, convert relative URLs to absolute ones?

**Comment by eSilverStrike** [comment]
The site migrator does search through articles (and staticpages I believe) and converts any old absolute urls to the new ones. Saying that I like mystralkk solution the best. The daily digest should check for these type of urls as they could be entered this way by the user manually or by some other means.

**Comment by mystralkk** [comment]
Fixed with changeset 73dbd58.  The Filemanager still returns relative URLs, but in the daily digest they are converted into absolute URLs.
