### ISSUE TITLE
Add 2 HTTP headers for better results in security checks

### ISSUE THREAD

**Issue by dhaun** [Geeklog-Core/geeklog#677]
These are two low-hanging fruits to improve the rating of Geeklog sites in security checks such as securityheaders.io

Simply add:

header('X-XSS-Protection: 1; mode=block');
header('X-Content-Type-Options: nosniff');

in all the 3(?) places where we send the X-FRAME-OPTIONS header (2x in lib-common.php, 1x in article.php). It's probably not even worth making them configurable.

We're currently getting an "E" at https://securityheaders.io/?q=https%3A%2F%2Fwww.geeklog.net%2F

The two headers are explained there if you run the test. Basically, they trigger certain security checks in some browsers to prevent some XSS and MIME type misuse.

**Comment by mystralkk** [comment]
Implemented with change set 74df5d3
