### ISSUE TITLE
Confirm Geeklog and Core Plugins Works on PHP 7

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#679]

**Comment by dhaun** [comment]
FWIW, I ran a local install of Geeklog on the public betas and release candidates of PHP 7 without any problems. Haven't done any systematic tests, though, and nearly nothing since the official release.

**Comment by ivywe** [comment]
Remove deprecated functionality in PHP 7
https://wiki.php.net/rfc/remove_deprecated_functionality_in_php7
mysql_***() 

install error occurred XAMPP.

**Comment by neclimdul** [comment]
Most errors (other then deprecated functionality) between 5.X and 7.x comes from this change:
http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect

**Comment by eSilverStrike** [comment]
The pear libraries will also need updating (as per Kenji)
