### ISSUE TITLE
Mobile Detect For Blocks

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#683]
Add a mobile detect class which would allow blocks to turn on or off depending on the enabled settings for the block. For example the block would be visible for desktop and tablets but not phones.

Possible PHP Class http://mobiledetect.net/

**Comment by eSilverStrike** [comment]
This obviously could be used for much more than blocks.

If implemented we will also have to update the cache to handle different views of all pages since information being displayed could be dependent on if it is a phone, tablet, or a desktop.

This will probably be best implemented as a global variable instead of allowing anything to directly access the class since we may want to change it out in the future. The users device should be checked first by lib-template.php and set when it is included in lib-common.

**Comment by dengenxp** [comment]
I noticed an issue that all of dynamic blocks do not display.

**Comment by eSilverStrike** [comment]
Okay thanks. I will check it out.

**Comment by eSilverStrike** [comment]
Fixed
