### ISSUE TITLE
Com_Email fails to send in certain cases under certain languages

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#684]
The Pear mail function errors out sometimes when an email gets sent in a different language. This usually happens when the forum try's to send a forum post notification who has their language set to Japanese or Spanish. It doesn't happen all the time since it depends what the forum title is.

An example of the  error happens when replying to this post (this is before I updated the COM_emailEscape function to skip some code)

https://www.geeklog.net/forum/viewtopic.php?showtopic=96350

This error seems to deal with the results of using the function iconv_mime_encode to escape strings with the utf-8 character set. This happens in COM_emailEscape.

Here is the error message (with identifying emails and ips changed)

`An error has occurred:
(This text is only displayed to users in the group 'Root')
E_WARNING(2) - mail() [function.mail]: Bad parameters to mail() function, mail not sent. @ /.........../system/pear/Mail/mail.php line 153

Call Stack # Function File Line
1 mail ......../system/pear/Mail/mail.php 151 
2 send ........../lib-common.php 4270 
3 COM_mail ........./forum/createtopic.php 1154 
4 gf_chknotifications ................og/forum/createtopic.php 375 
 array(7) {
  ["recipients"]=>
  string(17) "someguy@gmail.com"
  ["headers"]=>
  array(5) {
    ["From"]=>
    string(38) "Geeklog from@lists.geeklog.net"
    ["Date"]=>
    string(31) "Thu, 02 Jun 2016 15:08:54 -0400"
    ["Content-Type"]=>
    string(25) "text/plain; charset=utf-8"
    ["X-Mailer"]=>
    string(13) "Geeklog 2.1.1"
    ["X-Originating-IP"]=>
    string(12) "111.111.111.111"
  }
  ["body"]=>
  string(494) "Hola  name,

Hay una respuesta a la discusiÃ³n 'UIkit Framework' por name.

Este tÃ³pico lo iniciÃ³ alb3rt en el foro Geeklog. Puedes verlo en:
https://www.geeklog.net/forum/viewtopic.php?showtopic=96350&lastpost=true

Estas recibiendo este mensaje por que has elegido ser notificado cuando hubiera una respuesta a este tÃ³pico. Para dejar de recibir notificaciones en este tÃ³pico ve a https://www.geeklog.net/forum/notify.php para eliminarlas.

Â¡Que tengas un gran dÃ­a! 
Geeklog Admin
"
  ["result"]=>
  NULL
  ["subject"]=>
  string(100) "=?utf-8?Q?Geeklog=20-=20Notificaci?==?utf-8?Q?=C3=B3n=20de=20e?=
 =?utf-8?Q?nv=C3=ADo=20al=20foro?="
  ["headerElements"]=>
  array(2) {
    [0]=>
    string(28) "from@lists.geeklog.net"
    [1]=>
    string(177) "From: Geeklog from@lists.geeklog.net
Date: Thu, 02 Jun 2016 15:08:54 -0400
Content-Type: text/plain; charset=utf-8
X-Mailer: Geeklog 2.1.1
X-Originating-IP: 111.111.111.111"
  }
  ["text_headers"]=>
  string(177) "From: Geeklog from@lists.geeklog.net
Date: Thu, 02 Jun 2016 15:08:54 -0400
Content-Type: text/plain; charset=utf-8
X-Mailer: Geeklog 2.1.1
X-Originating-IP: 111.111.111.111"
}
`

**Comment by eSilverStrike** [comment]
Added temp fix so issue will not happen. Real solution should be found so leaving issue open until that happens.

**Comment by mystralkk** [comment]
@eSilverStrike , this issue should have been fixed by now.  How about trying to reproduce this issue on https://www.geeklog.net/ ?

**Comment by eSilverStrike** [comment]
The bug has a temporary fixed in COM_emailEscape function (see below). The function also now has been depreciated so I think it is safe to close. Reopen if you think otherwise.

```
        // Current hack to bypass the use of iconv_mime_encode until proper fix found
        // In some cases emails being sent fail when using COM_Mail when the email subject contain certain characters in another language (like Japanese)
        // This bug usually happens when the Geeklog forum sends out a notification email of a reply to a topic. 
        // For more info see https://github.com/Geeklog-Core/geeklog/issues/684
        if (false) {
            //if (function_exists('iconv_mime_encode')) {
            $mime_parameters = array(
                'input-charset'  => 'utf-8',
                'output-charset' => 'utf-8',
                // 'Q' encoding is more readable than 'B'
                'scheme'         => 'Q',
            );
            $string = substr(iconv_mime_encode('', $string, $mime_parameters), 2);
        } else {
            $string = '=?' . $charset . '?B?' . base64_encode($string) . '?=';
        }
```
