### ISSUE TITLE
[Feature Requests] Staticpages plugin - Sitemap flag

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#686]
I want sitemap registration flag per Static page.
Default sitemap flag mode at configuration, too.

**Comment by eSilverStrike** [comment]
This would be built into the staticpage plugin and it can just pass the staticpage info to the sitemap plugin that the user wants.

**Comment by ivywe** [comment]
Thanks.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
