### ISSUE TITLE
Comment Titles are showing html entities instead of '

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#691]
For an example see: https://www.geeklog.net/article.php/geeklog-s-next-release-and-the-php-version-requirement#comments

It also shows in the new comment editor as well.

**Comment by eSilverStrike** [comment]
Tested with current development version and comment titles are displaying properly if I use:

Geeklog's Next Release and the PHP Version Requirement

Maybe fixed with feature #700 ?

**Comment by mystralkk** [comment]
That may be the case.
