### ISSUE TITLE
Errors since moving to MySQL 5.7.15

### ISSUE THREAD

**Issue by jrmain** [Geeklog-Core/geeklog#692]
I'm moving my Geeklog site to a new server that runs MySQL 5.7.15. I started getting these in the Geeklog error log:
`1055: Expression #34 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gklg1.ta.tid' which is not functionally dependent on columns in GROUP BY clause; 
this is incompatible with sql_mode=only_full_group_by in xxx/geeklog/index.php:319. 
SQL in question: SELECT s.*, ta.tid, UNIX_TIMESTAMP(s.date) AS unixdate, UNIX_TIMESTAMP(s.expire) as expireunix, u.uid, u.username, u.fullname, u.photo, u.email, t.topic, t.imageurl FROM gl_stories AS s, gl_topic_assignments AS ta,gl_users AS u, gl_topics AS t WHERE (s.uid = u.uid) AND (ta.tid = t.tid) AND ta.type = 'article' AND ta.id = s.sid AND  (date <= NOW()) AND (draft_flag = 0) AND frontpage = 1 AND ta.tdefault = 1 AND (s.perm_anon >= 2) AND (ta.tid IN ('gamingblog','jdrgaming','tpu','Reviews','xbox360','miscellaneous','tpubf2','minecraft','xboxone')) GROUP BY s.sid ORDER BY featured DESC, date DESC LIMIT 0, 10` 

`E_USER_ERROR(256) - An SQL error has occurred. Please see error.log for details.  @ xxx/gl-private/system/databases/mysqli.class.php line 279`

In order to get past this error, I had to change the global MySQL setting for sql-mode, from its MySQL 5.7.15 default of `ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION` to `STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

The site now works, but I would prefer to find another way around this issue, or at least find a way to change the sql-mode for the Geeklog site only (not globally).

Anyone else seeing this?

**Comment by Trinity93** [comment]
You should be able to set this option per database in mysql. Im assuming
your only using one database per site?

**Comment by jrmain** [comment]
One database per site, yes. As for setting sql-mode for an individual database, the MySQL docs say this: "A mode is not linked to a particular database. Modes can be set locally to the session (connection), or globally for the server." Assuming that's correct, then it looks like I can set it globally in my.cnf (which I have done for now), or programmatically. Presumably that would mean adding code to Geeklog somewhere, but a) I don't know where to do that, and b) I'm not sure a transient solution like that is advisable. Any more ideas?

**Comment by eSilverStrike** [comment]
Related to issue #694
