### ISSUE TITLE
Please Remove role:"presentation" in jquery.ui.tabs.min.js.

### ISSUE THREAD

**Issue by milk54** [Geeklog-Core/geeklog#693]
According to the ARIA in HTML (https://www.w3.org/TR/html-aria/), The a element with a href can to use ARIA roles is button, checkbox, menuitem, menuitemcheckbox, menuitemradio, radio, tab, switch or treeitem.
So, The a element can't to use role="presentation". (invalid)
Please, Remove role:"presentation" in geeklog/public_html/javascript/jquery_ui/jquery.ui.tabs.min.js.
https://github.com/Geeklog-Core/geeklog/blob/master/public_html/javascript/jquery_ui/jquery.ui.tabs.min.js
(Please change to attr({tabIndex:-1}) form attr({role:"presentation",tabIndex:-1}).)

Because, It has been reported in bug by jQuery UI, but It has been laid aside for two year.
https://bugs.jqueryui.com/ticket/10122

**Comment by eSilverStrike** [comment]
Just a note before this is done jQuery and UI need to be updated to the newer version before release.

**Comment by mystralkk** [comment]
This bug will be fixed with jQuery UI v1.12.2, but I fixed the wrong code in the repository (v1.12.1) with changeset b8d607e.
