### ISSUE TITLE
Geeklog does Not Work with MySQL 5.7+ Default Settings

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#694]
Looks like Geeklog 2.1.1 requires special settings to work properly with MySQL 5.7+. Specifically, sql-mode has to be set globally, removing both ONLY_FULL_GROUP_BY and NO_ZERO_DATE from what is otherwise the default (MySQL) setting.

Geeklog should probably work with the default settings of MySQL. Also noted that NO_ZERO_DATE is being depreciated.

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

ONLY_FULL_GROUP_BY 

Reject queries for which the select list, HAVING condition, or ORDER BY list refer to nonaggregated columns that are neither named in the GROUP BY clause nor are functionally dependent on (uniquely determined by) GROUP BY columns. 

As of MySQL 5.7.5, the default SQL mode includes ONLY_FULL_GROUP_BY. (Before 5.7.5, MySQL does not detect functional dependency and ONLY_FULL_GROUP_BY is not enabled by default. For a description of pre-5.7.5 behavior, see the MySQL 5.6 Reference Manual.) 

A MySQL extension to standard SQL permits references in the HAVING clause to aliased expressions in the select list. Before MySQL 5.7.5, enabling ONLY_FULL_GROUP_BY disables this extension, thus requiring the HAVING clause to be written using unaliased expressions. As of MySQL 5.7.5, this restriction is lifted so that the HAVING clause can refer to aliases regardless of whether ONLY_FULL_GROUP_BY is enabled. 

NO_ZERO_DATE 

The NO_ZERO_DATE mode affects whether the server permits '0000-00-00' as a valid date. Its effect also depends on whether strict SQL mode is enabled. 

◾ If this mode is not enabled, '0000-00-00' is permitted and inserts produce no warning. 
◾ If this mode is enabled, '0000-00-00' is permitted and inserts produce a warning. 
◾ If this mode and strict mode are enabled, '0000-00-00' is not permitted and inserts produce an error, unless IGNORE is given as well. For INSERT IGNORE and UPDATE IGNORE, '0000-00-00' is permitted and inserts produce a warning. 

As of MySQL 5.7.4, NO_ZERO_DATE is deprecated. In MySQL 5.7.4 through 5.7.7, NO_ZERO_DATE does nothing when named explicitly. Instead, its effect is included in the effects of strict SQL mode. In MySQL 5.7.8 and later, NO_ZERO_DATE does have an effect when named explicitly and is not part of strict mode, as before MySQL 5.7.4. However, it should be used in conjunction with strict mode and is enabled by default. A warning occurs if NO_ZERO_DATE is enabled without also enabling strict mode or vice versa. For additional discussion, see SQL Mode Changes in MySQL 5.7. 

Because NO_ZERO_DATE is deprecated, it will be removed in a future MySQL release as a separate mode name and its effect included in the effects of strict SQL mode.

**Comment by eSilverStrike** [comment]
I did notice that NO_ZERO_DATE setting is being depreciated as well. I haven't read enough but I assume this mean eventual '0000-00-00' dates will not be allowed at all. So I guess we will have to use NULL dates then.

**Comment by Trinity93** [comment]
Does any one know if this effects Mariadb as well? Lots of people are using
that instead of MySQL due to it being a "unrestricted" fork

**Comment by eSilverStrike** [comment]
Related to issue #692
