### ISSUE TITLE
The 😁  from Phones cause errors when saving content in Geeklog

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#698]
This issue was first reported in the Geeklog forum by Ben. Geeklog has issues saving the emoji icons that people can insert usually by their phones (in this case the iPhone). Copying the emoji here in this post below and pasting it into Geeklog and saving will produce this error. It doesn't seem to matter what your saving (comment, story, plugin item like a forum post) since it all uses Geeklog filters and database class.

It behaves differently depending on which Geeklog version you are using. When saving a comment or story in Geeklog 2.1.1 with the text:

Hello 😁 world

becomes

Hello

Everything after the emoji is missing.

In Geeklog 2.1.2 it triggers an error for me in the mysqli class:

E_USER_ERROR(256) - 1366: Incorrect string value: '\xF0\x9F\x98\x81 w...' for column 'comment' at row 1 @ \geeklog\system\databases\mysqli.class.php line 352

I assume we could filtering out the emoji but then most people actually want it in their post so a better option would be probably be allowing Geeklog to save it. (or maybe not depending on the circumstance?)

We should also make sure title's and ids, etc.. can handle this. I know the story title, id and the javascript used to automatically create the id from story title cannot.

**Comment by mystralkk** [comment]
Fixed with changeset b6bfe49

**Comment by mystralkk** [comment]
This bug happens when MySQL charset is utf8_xxx_ci, not utf8mb4_xxx_ci with Geeklog prior to v2.1.2.  

The emoji icons are 4-byte characters, so you have to choose utf8mb4_xxx_ci (for example, utf8mb4_general_ci) as default charset.  I have modified Geeklog database classes so they can handle the emoji icons.
