### ISSUE TITLE
Add easy way to add uikit Components to Scripts Class

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#699]
I added the uikit lightbox to one of my sites and I had to link directly to the javascript for it

Maybe the Scripts class should offer an easier way to add uikit components like the light box and slider.

Maybe based in part on how the denim theme does it now (see it's funcitons.php file)?

**Comment by mystralkk** [comment]
Implemented with change set fe13211.  $_SCRIPTS->setJavaScriptLibrary() method now accepts $name parameter such as 'uikit.accordinon' or 'uikit.slideshow'.
