### ISSUE TITLE
Update Geeklog to use Input Class instead of Com_applyFilters 

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#700]
Switch from Com_applyFilters to using input class for Geeklog Core and Core plugins.

**Comment by mystralkk** [comment]
There are tAoo many places I have to rewrite code, so I set the milestone to 2.2.0.

**Comment by eSilverStrike** [comment]
Sounds good.

**Comment by mystralkk** [comment]
Replaced almost all $_GET, $_POST and $_REQUEST variables with their counterparts in the Input class (38c7d1c)

**Comment by eSilverStrike** [comment]
Should we depreciation  COM_applyFilter, etc...? (not for a long time say like 3.0) Maybe add a log message like was done for COM_siteHeader except maybe have the log message trigger only when rootdebug is set to true so they don't fill up the error.log?

**Comment by eSilverStrike** [comment]
I created a COM_deprecateLog function and updated the functions already deprecated. What else do we need to deprecate?

COM_applyFilter
COM_stripslashes
COM_applyBasicFilter

???

**Comment by mystralkk** [comment]
PLG_install since GL-1.6.0
SEC_hasConfigAcess since 2.0.0
Plugin::setExpandedSearchSupport since ?
Plugin::supportsExpandedSearch since ?
timerobj::setPercision since 1.6.0

By the way, we shoudln't deprecate COM_applyFilter, COM_stripslashes and COM_applyBasicFilter.  They are still used in not a few places.

**Comment by mystralkk** [comment]
and 

CUSTOM_user_create since 2.1.2
Template::get_undefined since ?

**Comment by eSilverStrike** [comment]
Checked the repository for:

Plugin::setExpandedSearchSupport
Plugin::supportsExpandedSearch

and changes were done in July, 2009 so I marked them as version 1.6.0. I also added the log to the rest of those functions listed.
