### ISSUE TITLE
Sending Email Message to User Doesn't Display Succcess Message

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#705]
For some reason after clicking Send Message button to the user Geeklog doesn't display the 

"Message successfully sent." message and returns to the user profile. Instead it goes to the home page.

The email does get sent.

**Comment by mystralkk** [comment]
Fixed with changeset 9ca1e46.  In fact, this was a bug with COM_refresh, which didn't work properly when given a URL including '&amp;'.
