### ISSUE TITLE
In Block Editor add ability to add id and css classes to a Block

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#706]
It would also be nice if we could add more style functionality to blocks by allowing in the block editor to optionally  add id's to the block and extra css classes. These could be added using template variables to the appropriate block element in the theme files.

This functionally would not be theme specific.

Also should consider how this affects Dynamic Blocks.

**Comment by mystralkk** [comment]
Implemented with change set 8418fb3
