### ISSUE TITLE
E_ERROR(1) - Invalid cookie: 'wordpress_test_cookie=WP Cookie check' @

### ISSUE THREAD

**Issue by AlexL777** [Geeklog-Core/geeklog#708]
Hello developer team,

I have an error problem with the new version 2.1.2 Beta 1. I have made an upgrade of 2.1.1 and if I want to authenticate again after saving the article, this error is displayed to me.

`E_ERROR(1) - Invalid cookie: 'wordpress_test_cookie=WP Cookie check' @ /xxxxxxx/geeklog/system/vendor/pear/http_request2/HTTP/Request2.php line 560`

Can you check this again and fixed if necessary.

Thanks in advance.

**Comment by eSilverStrike** [comment]
Thanks for positng your issue.

How ware you authenticating?

It looks like you might be using OAuth... Is it Facebook, Microsoft, GitHub,...?

**Comment by AlexL777** [comment]
Very happy because of the issue. It ran like this.

I created a new blog post in the backend and after saving, I was redirected and had to log again. It is a normal glfusion login and nothing else.

After entering the login data, this error message appears.

**Comment by eSilverStrike** [comment]
We will have to look into this. What is confusing me is your cookie name referring to a Wordpress test cookie.

**Comment by AlexL777** [comment]
Perhaps it has to do with that in my root directory Wordpress is installed. Geeklog is installed at http://wpzweinull.ch/geeklog

**Comment by mystralkk** [comment]
I think this issue has nothing to do with Geeklog.  It is just that WordPress issued an invalid cookie.

**Comment by eSilverStrike** [comment]
That is probably the case but why would Geeklog attempt to retrieve that cookie though and generate the error?

**Comment by mystralkk** [comment]
Maybe the cookie path of WordPress or Geeklog is not properly set.

**Comment by AlexL777** [comment]
Hello,

It is hard for me to say what it is. My Worpdress blog in the root directory works very well and is on the latest version. Now in Geeklog I can test it again, but there is the danger that I can lose the blog post.

It was also so that I only went back in the browser and saw the post again. Otherwise it could not be saved. Is it perhaps on the Wordpress plugin named Wordfence? It is installed in the Wordpress blog.

**Comment by mystralkk** [comment]
Fixed with change set 45da3e5.
