### ISSUE TITLE
Denim Theme - Fix Article Structured Data on page

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#710]
Running the Google Testing tool for Article structure data several errors and warnings are received.

https://developers.google.com/structured-data/testing-tool/

We should probably add values for at least the errors:

headline - A value for the headline field is required.
image - A value for the image field is required.
publisher - A value for the publisher field is required.

**Comment by dengenxp** [comment]
Fixed with change set b2ade45. Was it in a good way or bad?
