### ISSUE TITLE
Comment Admin form errors out with non core plugin comments

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#713]
The following error is reported with comments from a third party plugin (both existing and submitted)

ADMIN_getListField_comments: unknown type "rating" was given @ path_to_geeklog\public_html\admin\comment.php line 102

**Comment by mystralkk** [comment]
What plugin are you using?

**Comment by eSilverStrike** [comment]
A rating plugin. 

```
    if (!in_array($A['type'], array('article', 'staticpages', 'polls'))) {
        throw new Exception(__FUNCTION__ . ': unknown type "' . $A['type'] . '" was given');
    }
```

It looks like it is suppose to create an error for an unrecognized type for some reason.

The rating plugin does have a plugin_getiteminfo_rating function so we should be able to pull the right information (which is title and url of the parent item the comment is for). If a plugin doesn't have this function maybe we should start requiring it for plugins that use the comment system? At the very least we should have a fallback that just doesn't include the link and title of the parent item since we can retrieve everything else needed to display the comments in the list.

**Comment by eSilverStrike** [comment]
We should also trim the comment text in the list. Looking at my dev website it seems to display the entire comment.

**Comment by mystralkk** [comment]
I dropped the check for core plugins and added the trimming of the comment text with changeset 81f5791.  If you would check if things go well, please close this issue.
