### ISSUE TITLE
FileManager shows opens in a new window but just shows the loading icon

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#716]
FileManager shows opens in a new window but just shows the loading icon. Nothing ever loads.

**Comment by mystralkk** [comment]
What system are you using?  I have made sure I can use the Filemanager with Windows 10, PHP-7.1.0 and Chrome 55.0, Firefox 50.1.0, Edge and IE11.

**Comment by eSilverStrike** [comment]
It worked with Geeklog 2.1.1 and not 2.2.2 (accessing with Edge and Firefox)

On my Dev web server I am using PHP 7 and on production PHP 5.6.22 (both IIS and specs haven't changed between the 2 versions).

I see the following error being reported in the browser:

06:55:54.740 TypeError: d.options is undefined 1 filemanager.min.js:9:400
	<anonymous> http://192.168.1.200/filemanager/scripts/filemanager.min.js:9:400
	<anonymous> http://192.168.1.200/filemanager/scripts/filemanager.min.js:7:2


I know filemanager.config.json also gets written to as it shows up as modified in Git but I haven't looked into anything further.

**Comment by mystralkk** [comment]
Have a look at this page by the developers of Filemanager.  Anything helpful?

https://github.com/simogeo/Filemanager/issues/493

**Comment by eSilverStrike** [comment]
Okay I solved the issue but it took me a little bit to figure out.

Turning on the filemanager logging didn't produce a log file so I then had filemanager use the non minified version of filemanger.js

And got this error:

"TypeError: config.options is undefined"

I figured maybe the config file wasn't loading and I hardcoded the urls into the filemanger.js script file. In the debugger I saw that they were getting 404 errors (with the correct url).

This made me realize that the mime types might not have the .json extension setup in IIS which was the case for both of my servers. Once I added the extension everything worked

**Comment by eSilverStrike** [comment]
I wonder if we should add a list of mime types that need to be set on the server for Geeklog somewhere in the docs?

**Comment by mystralkk** [comment]
I agree.  I didn't even think about the MIME types for this issue.

**Comment by eSilverStrike** [comment]
Neither did I :-) .The server's original install was in 2012 and I guess json file extension wasn't a big thing back then.

What file type extensions need to be accessible via the web for Geeklog?

Need:
.html, .php
.css
.js, .json
.rss

Ones that I am not sure we need:
.txt (don't think we need it), .cache (for the etag?)

Have I forgotten any?

**Comment by mystralkk** [comment]
Maybe .xml and .atom for AtomSyndication fomrat?  .txt and .cache could contain some secret information, so we shouldn't allow accessing them via Geeklog
