### ISSUE TITLE
Default of COM_errorLog variable changed from writing to error log to displaying on screen

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#719]
```
function COM_errorLog($logEntry, $actionId = '')
```

was changed to

```
function COM_errorLog($logEntry, $actionId = 2)
```

which results in the default behavior of writing to the error log changed to displaying on screen.

Not sure if this is a good idea as in a few spots (like the oauth class (which is now fixed but other areas are not)) rely on this default behaviour of writing to the error log. Especially since if  COM_errorLog is not set to anything and wasn't planned to be display on the screen.

We should either change it back or double check all of the COM_errorlog calls in core and the plugins to be on the safe side (and this may still cause problems in 3rd party plugins).

**Comment by mystralkk** [comment]
This is my mistake.  While I was refactoring lib-common.php, I somehow changed the default value.  I'll revert the change.

**Comment by eSilverStrike** [comment]
Thanks, I wasn't sure if it was done on purpose for some other reason. I think I will update any COM_errorLog calls that rely on the default setting as I see them anyways as it generates both user content and a line in the error log. (unless the display is being used)

**Comment by eSilverStrike** [comment]
@mystralkk  I know you reworked the COM_redirect a bit because of this issue. A see a number of these type of errors. Most of the IPs seem to be from search engines.
```
12/29/16 17:39:18 - 207.46.13.192 - COM_redirect failed to redirect to "http://www.example.com/index.php".  Headers were already sent at line 0 of "".
```

**Comment by mystralkk** [comment]
Well, how about NOT writing into error.log errors that occurred COM_redirect tried to redirect to EXTERNAL sites in vain?

**Comment by eSilverStrike** [comment]
Sorry example.com is actually the geeklog site (internal link). I haven't had a chance to look at where/why it is happening yet.

**Comment by eSilverStrike** [comment]
Looks like a lot of the reported redirect errors are happening from comments (but I see reported errors from users as well). As far as I can tell no real errors are happening

For example this is the log I have after adding a comment
```
Fri Dec 30 10:12:47 2016 - 192.168.1.224 - COM_redirect failed to redirect to "http://192.168.1.200/".  Headers were already sent at line 0 of "". 
Fri Dec 30 10:13:05 2016 - 192.168.1.224 - COM_redirect failed to redirect to "http://192.168.1.200/article.php?story=20161209101435526".  Headers were already sent at line 0 of "". 
```

In COM_redirect shouldn't we have an exit call after the header call or it will always reach the com_errorlog call?

**Comment by mystralkk** [comment]
I added conditional logging (only when $_CONF['rootdebug'] is set) with chanse set b12d6bc.
