### ISSUE TITLE
In comment library replace COM_redirect with COM_handle404 on incorrect url

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#723]
For some reason the search engines have found the link on my site and keep visiting this type of url:

http://www.example.com/comment.php?pid=4450&type=staticpages

The comment id does exist but the url is incorrect. I am not sure if Geeklog generated this link or what. (can't find it myself)

The comment library with incorrect urls just redirects the page to the homepage. We should be using COM_handle404 in these spots instead of doing a soft redirect according to the Google guidelines.

**Comment by mystralkk** [comment]
Fixed with change set bdcf7ef
