### ISSUE TITLE
Admin Configuration Missing Tabs

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#724]
For both Denim and Modern Curve themes 2 Geeklog sections are missing tabs. This is most likely a jQuery and javascript issue when the tabs are built. Probably related to issue #722 which deals with configuration search.

Section: Geeklog -> Users and Submissions
Missing Tabs: Submission Settings, Comments

Section: Geeklog -> Miscellaneous
Missing Tabs: Censoring, IP Lookup, Permissions, Webservices, Topics
(also usually has a "More" tab with dropdown to some of these missing tabs)

**Comment by mystralkk** [comment]
Fixed with change set d63c0ef.
