### ISSUE TITLE
New CSS and JS processor to Minify and combine files

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#725]
We should make a class to handle CSS files used by Geeklog core functions as well as CSS files from plugins  so the site will load just one CSS file.  This will be done on the fly and be cached.  Related to #637.

**Comment by eSilverStrike** [comment]
Hey @mystralkk I updated the title a bit as I think we should do this with javascript files as well. I have been looking for classes to do this for us and haven't had much luck as a lot of the classes don't seem to be maintained anymore:

https://github.com/Schepp/CSS-JS-Booster
- This one looked good except it hasn't been updated in 6 years

https://gist.github.com/tovic/d7b310dea3b33e4732c0
- Class that will minify HTML, CSS, and JS
- Does not combine files
- Might have some code we can use

https://github.com/matthiasmullie/minify
- Another option

**Comment by hostellerie** [comment]
Kenji and Tom you can also try https://github.com/mrclay/minify

**Comment by mystralkk** [comment]
Partially implemented with change set 6207a2c.  I added JSMin ( https://github.com/mrclay/minify ) @hostellerie had suggested but couldn't find a suitable CSS minifier.  So, CSS code is just concatenated for the present.

**Comment by eSilverStrike** [comment]
I am excited about this feature, thanks for working on it @mystralkk. I haven't tested it yet but can it handle extra css or js files that get added in for certain pages. I know some plugins and autotags may add in css only when in use. This could also be an issue when dealing with mobile devices since Geeklog can display content for just mobile or desktop devices (like with blocks or in staticpages)

**Comment by eSilverStrike** [comment]
Hey @mystralkk I've had a chance to do some testing. 

I notice that the Advance Editors do not display for articles or comments. (For actual users and anonymous users)

Do you think we should clear the resource cache when we "clear cache" in the Geeklog Admin? I think it should maybe extended to this as well.

Also you mention that the "CSS code is just concatenated" Looking at the source of a page I still see all the separate css files. Are the files suppose to be added together?

I also have a test staticpage that I used to test the scripts class which is set to execute php and load a jquery dialog box. I notice it was not working now either. I can't display the staticpage code for an example I am using as it doesn't display properly in this comment. I can email it to you if you want?

**Comment by mystralkk** [comment]
I fixed bugs about Advanced Editors and CSS not being concatenated.  As for clearing resource cache, I already added CACHE::clear() method to admin/clearctl.php.  Could you send me the staticpage code?

**Comment by eSilverStrike** [comment]
Email Sent.

While I was testing something I also notice that changing the theme in user settings results in a blank page. Haven't had time to check to see if it is the result of this or something else.

**Comment by eSilverStrike** [comment]
After changing the theme as a user under My Account I get a blank page.

Also notice that I can't delete a plugin any more from the Plugin List. It seems that the javascript doesn't like the &amp; entity and can't read the url variables. I am not sure why this is happening... is it something to do with the javascript being minified?

Would it be easy to add a config option to disable the resource cache just to make some testing easier?

**Comment by mystralkk** [comment]
What theme are you using?  To disable resource caching, you just have to Cache::disable();  However, it is easy to make a config option about resource caching.

**Comment by mystralkk** [comment]
> Also notice that I can't delete a plugin any more from the Plugin List.

This is caused the change I made to lib-common.php.  I fixed it a short time ago.

**Comment by eSilverStrike** [comment]
Ok that fix fixed both of my issues. I also just added the config option to disable the cache. One thing,

Cache::disable();

Seems to only disable the javascript resource process but not the CSS process, I assume this is a bug of some sort. I checked out the code a bit but didn't see anything. I figured you could find the bug easier being more familiar with the code.

**Comment by mystralkk** [comment]
Changeset 419e471 fixed this issue.

**Comment by eSilverStrike** [comment]
> but couldn't find a suitable CSS minifier. So, CSS code is just concatenated for the present.

It looks like a few minifications are done with minifyCSS in Resource.php. Did the Minify_CSS component from https://github.com/mrclay/minify/wiki/Component-Classes not work out?

**Comment by mystralkk** [comment]
No, it doesn't handle url() well.

**Comment by eSilverStrike** [comment]
So should we close this or leave it open in case we come up with another idea?

**Comment by mystralkk** [comment]
I closed this issue for the present.

**Comment by eSilverStrike** [comment]
For the modern curve theme I notice it has trouble loading images that are set in css files like so.

background: transparent url('./images/css/bg_header.png') repeat-x 0 0;
background: transparent url('./images/css/search-{right}.png') no-repeat 0 0;

This is true if minify is turned on or not. For example these are the URLs created which do not work:

http://www.example.com/layout/modern_curve/css/images/css/bg_header.png

it should really be 

http://www.example.com/layout/modern_curve/images/css/bg_header.png

To fix this I  updated the url and added an extra period

url('../images/css/bg_header.png')

This now works both when the resource class is turned on or not for images.

The other thing I notice is that the resource class is a replacement for the scripts.class.php file. We should probably remove this at some point if it is not needed anymore??

In the getheader function of the scripts.class.php file it uses the etag and the style.css.php file.

The etag has settings in the denim, denim3, denim_curve themes and is required in the modern curve theme as style.css.php is needed to fill in the css file template variables {left} and {right} (when the resource class is disabled only).

Obviously the etag is not needed anymore if people are using the resouce class. The only time I disable the resource class is when I debugging css file issues.

@mystralkk @dengenxp I believe we might as well remove the etag code from the other themes but what should we do about the modern curve theme as it needs the style.css.php file for the css file template variables? Should we add this back into the resource class or is there a better way to handle this?

**Comment by dengenxp** [comment]
I knew that the Modern_Curve theme was not displayed correctly. I tried to fix it, but now I prioritized work on the Denim 3 theme.

Since Etag is supported by the Resource.php, Denim, Denim_Curve and Denim_Three (this theme is my Denim 3 under development) uses the Resource.php now. For these themes, code that uses style.css.php is still left, but this code is positioned as deprecated code.

The Resource class also contains code to convert the css file template variables {left} and {right}.

It would be ideal if we could modify the Resource.php so that the Modern_Curve theme and its cognate theme works fine. Or I want a mechanism that uses Resource.php and scripts.class.php properly.
There is also a way to discard backward compatibility and move to Resource.php with Geeklog 2.2.

**Comment by eSilverStrike** [comment]
@dengenxp Of course continue to work on Denim_Three. I have reopened this just so we don't forget about etag, the old scripts class, and modern_curve and the current issues it has.

Should we continue to support etags? I don't think it really makes much sense to do so with the new resource script but then I don't really keep up on theme development. @mystralkk  what do you think?

Currently the modern_curve theme requires processing on the css files to replace the {left} and {right}.  I propose just creating 2 new css files for the theme (one for ltr and one for rtl languages) combining all of the small css files into one large file with the {left} and {right} already filled in. This way no pre processing is required on the css files and we can remove the bit of code that is modern_curve specific from the resource class. 

This is just an idea and I am open to other better suggestions 😊

**Comment by dengenxp** [comment]
I fixed about URLs in the css files with changeset 2e5bf12.
Currently the theme with style.css.php will work correctly without rewriting URLs.

I think this is not a problem to solve by modifying the Modern Curve theme. We still need to include special code in Resource.php in order to support themes compatible with Modern Curve theme.

**Comment by eSilverStrike** [comment]
Great. It is a much better solution than mine. 

I added a small update to the docs to explain the config option cache_resource will always be enabled for themes that use style.css.php.
