### ISSUE TITLE
Mail Notifications with Incorrect URL

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#726]
Maybe 1 in every 20 email notifications I get from Geeklog has a messed up url that is located in the message. It has been happening for core notifications like for new users (email included below) and other plugins like the forum for new posts notifications. The only difference is and extra period next to the one in the domain either with the ".com" (like below) or at the "www." so the url either looks like:

http://www..example.com/index.php

or

http://www.example..com/index.php

```
Username: testuser
Email: testuser@example.com
Reg. Date: Sunday, January 01 2017 @ 01:05 AM

Profile <http://www.example..com/users.php?mode=profile&uid=17546>


------------------------------

End of Message

------------------------------
```

**Comment by eSilverStrike** [comment]
Just got another one (and this is with the latest build from yesterday which including some mail class changes). It is the first time I have seen the php file contain a double period. Before it has always been the domain.

http://www.example.com/users..php?mode=profile&uid=17557

Nothing really special about the user except the email does have a period in it as well like: 

george.smith@example.com

I cannot reproduce the error creating test users.

**Comment by eSilverStrike** [comment]
Okay I figured out how to reproduce the bug. The first part of the email address  of the new user has to have a period in it AND the part after that period needs to be only 3 characters long (like a file extension). For example:

test.123@example.com

Creating a user with this email address will result in the email notification to include an incorrect link to the user:

http://www.example.com/users..php?mode=profile&uid=17557

**Comment by eSilverStrike** [comment]
Okay it has happened again but with an email address that doesn't fit the pattern above. Also it is the .com in the url that has the double period again. I can reproduce the error with the username and email address that the person used but I don't see the pattern and can't reproduce it with another email address. I am not going to post the info as it is someone's real email address.

**Comment by eSilverStrike** [comment]
@mystralkk Hey do you have time to look at this? I am not sure why it is happening. The body of the email reaches the mail class correctly but the error seems to happen when setbody is set.

**Comment by mystralkk** [comment]
"Double dots in mail body" issue seems to be happening with SqiftMailer under certain conditions.  I submitted a trial fix for this issue (by changing encoder from Quoted Printable to Base64).

**Comment by eSilverStrike** [comment]
Okay I applied the fix. I will see what happens in the next few days.

I also have a few of these errors in the error.log file in the last 3 days 

01/05/17 01:01:10 - 0.0.0.0 - E_WARNING(2) - array_map() expects parameter 1 to be a valid callback, function '\Geeklog\Mail\stripControlCharacters' not found or invalid function name @ \system\classes\Mail.php line 23 

I haven't had a chance to look into this yet.

**Comment by mystralkk** [comment]
OK, I changed a bit.

**Comment by eSilverStrike** [comment]
I haven't got the double period error anymore which is good but I still get the stripControlCharacters' error. I got one in the last 24 hours but the site has probably sent out 40 or so emails. 

I wonder if we should have an internal config option to include the call stack in the log with these type of errors. It would make it easier to debug with more information.

**Comment by mystralkk** [comment]
Okay, I finally fixed stripControlCharacters' error.  It was my mistake.  As for the config option of whether to include the call stack in the log, how about using $_CONF['developer_mode'] variable, which was added with v2.1.1?

**Comment by eSilverStrike** [comment]
I forgot about developer mode. Thanks.
