### ISSUE TITLE
Database Admin Tables to Backup can only save a certain number of tables

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#727]
Under the config options in Database Admin you can select which tables to backup. You can only select to backup a certain number of tables before the config screen will not work. 

The reason is the tables being saved are stored in the geeklog vars table.  The value column in this table can only hold 128 characters. 

We should either change this column to a text or save this information somewhere else.

**Comment by mystralkk** [comment]
I'll vote for changing the colum to a text.  It is not secure to save this information elsewhere (except in $_SESSION variable).

**Comment by mystralkk** [comment]
Fixed with change set 0342cf4.
