### ISSUE TITLE
Database Administration Success Modal shows cancel button 

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#728]
When the operation is finished (backup, optimizing tables, Convert to ...) a success uikit modal is shown. This modal has an okay and cancel button. It should only have an okay button as there is nothing to cancel since the operation is finished.

**Comment by dengenxp** [comment]
Fixed with change set f2f4e7c.

**Comment by eSilverStrike** [comment]
The fix works with Database backups but not converting or optimizing tables.

Also see #754 where Database Backup Okay button doesn't return to Database Admin Page

**Comment by dengenxp** [comment]
Oops! I was short of attention.
Fixed with change set cd7f2b0.
