### ISSUE TITLE
Replace SLV Module in Spam-x Plugin

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#733]
The SLV module uses http://linksleeve.org/ to validate a link as spam. Linksleeve is not well maintained so we should replace the module with something else.

It should be replaced with either another link verification service (suggestions are welcome) or maybe a module that scans the whole content being submitted. A few suggestions by @mystralkk are

https://akismet.com/ or https://www.mollom.com/

**Comment by mystralkk** [comment]
Mollom is going to be discontinued on 2 April 2018 ( https://www.mollom.com/eol ).  ZB Block doesn't seem to be actively maintained now ( http://www.spambotsecurity.com/zbblock.php ).  We have no choice but to use Akismet.

**Comment by mystralkk** [comment]
Added Akismet module for the Spam-X plugin with change set a173327.

**Comment by eSilverStrike** [comment]
Hey @mystralkk I was removing hard coded HTML from spam-x and ran across 2 issues related to Akismet.

"Mass Delete Spam Comments" (see MassDelete.Admin.class.php) and "Mass Delete Trackback Spam" (see MassDelTrackback.Admin.class.php) when executed only sends text (or the comment) for checking against the "*.Examine.class.php" classes and not the $permanentLink which seems to be required as of Geeklog 2.2.0. None of the other new fields are required. Is there a reason for this? 

I also notice that PLG_checkForSpam function in lib-plugins.php sets the $permanentLink to null if not passed. (for backwards compatibility with older plugins)

I am a little confused what $permanentLink is. I see in some cases where PLG_checkForSpam is called that for example the link to the Geeklog Article or Comment is passed but in other cases like with the links plugin the link that the user submitted is passed and in the Calendar the link that the user supplied for the event is passed and not the link to the event on Geeklog. What should $permanentLink be and why does Akismet need it? (is it required).

The easy fix is to set $permanentLink to null if not included in the execute function of the examine classes but I wasn't sure since I am not really sure what $permanentLink is suppose to be (the link to where the content exists on a Geeklog site or a link supplied by the user)

**Comment by eSilverStrike** [comment]
Okay I have read over https://akismet.com/development/api/ and have made a few small changes. Hopefully I have understood the exact meaning of the API. If anything I mention below looks incorrect please comment. I don't think we will know how things will actually play out until we have had some real world tests. Here are the changes I made:

If $permanentLink is not passed it is now set to null. (this fixes the mass delete spam issue)

According to the docs the $permanentLink is "the full permanent URL of the entry the comment was submitted to". This means for things like **submitted events** (can appear in multiple locations like day, week, and month views), **new blog posts** (it is not being added to anything other than 1 or more topics), **links plugin** (same issue as events), **emails** (it is a message being sent out and not saved to any item on the website) there is no real or just one permanentlink so I did not pass one. 

For things like comments and trackbacks their are (the article, staticpage, poll, etc...) so one is passed.

With trackbacks, the url of the trackback was being passed as the author url. I removed this since in most cases when an item contains a url (like a trackback, calender event, links submission) we actual add the url to the comment message itself in the code before we call PLG_checkForSpam.

The comment_author_url is confusing as it is described as "URL submitted with comment." but the name suggests the url of the author. So since we do combine any urls from separate fields into the comment message I choose mainly to just use comment_author_url as the users homepage if it exists.

I also added code where it made sense to include the author name, email and url (homepage) to PLG_checkForSpam for any logged in user that is submitting content where PLG_checkForSpam is called.
