### ISSUE TITLE
Topic URL Rewrite does not work

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#736]
Not sure why but Topic url rewrite does not work and just loads the homepage. Article URL rewrite does work.

URL Routing is disabled.

**Comment by eSilverStrike** [comment]
@mystralkk I looked into this a bit more and can't seem to figure out the issue. Can you?

It also looks like the docs only mention 

"This feature is supported for URLs to stories, static pages, the article directory, and links. "

so we should add topics to the list as well.

**Comment by mystralkk** [comment]
Fixed with change set a8dddf9
