### ISSUE TITLE
If current default theme doesn't exist Geeklog doesn't find an alternative

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#739]
If the default theme is professional (or some other non existent theme) after an install Geeklog 2.1.2 doesn't seem to find an alternate and attempts to display using the professional theme which doesn't exist (so you get a lot of file not found errors if logged in as admin).

We should at least attempt to switch to denim or modern_curve since they are included with the install and will most likely be available.

**Comment by mystralkk** [comment]
Fixed with change set ec9b97e
