### ISSUE TITLE
H2 Heading and Underlining do not work

### ISSUE THREAD

**Issue by AlexL777** [Geeklog-Core/geeklog#741]
Hello Developers,

Unfortunately, the H2-Headings and the underline in Beta 2 do not work. I have just blogged with me in the Geeklog Portal and I noticed that. 

Can you check this again with you?

Thanks in advance.

P.S. In the editor I can insert headings, but in the frontend in the portal is not formatted. This also applies to the underline.

**Comment by eSilverStrike** [comment]
I tested on my development server and the story editor seems to work fine in the backend and displays properly on the frontend (using the denim theme).

What theme are you using?

Are you talking about stories/articles?

When you look at the source of the page in the front end does it have the proper html to display the formatting like this below from my test article:

```
<p>This is a test</p>

<h2>Here is a header Title</h2>

<p>Here is an <u>underline test</u>.</p>

<hr />
<p>Now a line above.</p>
```

**Comment by AlexL777** [comment]
I have now figured out what was the point. I had to set the option to "Yes" in the configuration and then in the HTML filtering. In the process, HTML is no longer filtered and I could then test it.

H2 headings can now be inserted again and displayed in the front end.

You can now close this issue because the problem has been solved :)

**Comment by eSilverStrike** [comment]
Glad it was figured out (and not a bug). Should have thought about the filter.
