### ISSUE TITLE
Add Ban Plugin Support to Admin Comments Manager

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#742]
Use Ban API to add ban IP support to Geeklogs Comment Manager. 

See forum plugin for code example.

Obviously still keep SPAM-X ban IP support but maybe make an API for it (in SPAM-X) so other plugins can add/delete IP's to SPAM-X Ban IP table.

**Comment by mystralkk** [comment]
Implemented with change set 7d7b939.  IP addresses banned by the Spam-X plugin are now shown in red.  I added the following functions to spamx/functions.inc:

- SPAMX_isIPBanned($ipToCheck)
- SPAMX_getBannedIPs()
- SPAMX_registerBannedIPs($ips)
- SPAMX_deleteBannedIPs($ips)

**Comment by eSilverStrike** [comment]
I'm going to open this just so I can add BAN plugin support as well. This way the user can ban the user from posting via spam-x or ban the user outright from visiting the site via the ban plugin

**Comment by eSilverStrike** [comment]
User names also now are in red if user is banned.
