### ISSUE TITLE
Allow Help Files to support Multiple Languages

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#743]
The help files located in public_html/help/ can only be in one language.

These are mainly used in admin forms (See submissions), Submit Forms (like Event, Link, Article) and Advanced Search. Directory can also be used by staticpages and blocks.

We should allow the ability to support multiple languages. 

Maybe modeled after how the Geeklog docs does it with each language in a different directory??? If the language doesn't exist it then defaults to one that does.

**Comment by mystralkk** [comment]
Implemented with change set e3b8daa
