### ISSUE TITLE
Poll Question Description Cannot have a ' in it

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#744]
If this is a production website you must disable this option once you have resolved any issues you are investigating.
You will receive the following error if you add a ' to the poll description. We should make sure other fields in the poll can also use a ' if needed.

E_USER_ERROR(256) - 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 't car just pick one!')' at line 1 @ \geeklog\system\databases\mysqli.class.php line 459
Call Stack
#	Function	File	Line
1	trigger_error	\geeklog\system\databases\mysqli.class.php	459
2	dbQuery	\geeklog\system\databases\mysqli.class.php	502
3	dbSave	\geeklog\system\lib-database.php	234
4	DB_save	\geeklog\public_html\admin\plugins\polls\index.php	285
5	savepoll	\geeklog\public_html\admin\plugins\polls\index.php	678

array(3) {
  ["sql"]=>
  string(169) "REPLACE INTO gl_pollquestions (qid, pid, question,allow_multipleanswers,description) VALUES ('2', 'test-poll-features', 'Last Question','0','I don't care just pick one!')"
  ["ignore_errors"]=>
  int(0)
  ["result"]=>
  bool(false)
}

**Comment by mystralkk** [comment]
Fixed with change set b5c3c22
