### ISSUE TITLE
Allow Autotags and HTML on User BIO and Signature

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#749]
It would be nice if we could allow HTML and autotags for certain user groups for the user bio and signature. It should use the Geeklog HTML Filtering.

- Maybe it should be a group's access permission called user.html 
- Should we use the advanced editor here then?
- Drop down to switch between plain text and html?

**Comment by mystralkk** [comment]
Implemented with change set e833fa3.
