### ISSUE TITLE
Geeklog Installer "Use UTF-8" can have confusing results

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#751]
The default collation of my MySQL database is utf8mb4_general_ci

If I select "Use UTF-8" it creates the tables using the collation utf8_general_ci

If I don't select "Use UTF-8" then the tables get created with utf8mb4_general_ci but the config default_charset for geeklog is set to
```
$_CONF['default_charset'] = 'iso-8859-1';
```
As of MySQL 5.5.3 I believe the preferred setting for a database collation is utf8mb4_general_ci. If the MySQL server that Geeklog is being installed is this version or greater should we default the collation to utf8mb4_general_ci if "Use UTF-8" is selected?

Also should we change the database default collation to whatever is decided so future tables created by plugins, etc. match the collation of the rest of the geeklog tables?

I am not sure how this would change if the user is using PostgreSQL...

**Comment by mystralkk** [comment]
I can't reproduce the bug you reported.  On a fresh install of v2.1.2, if you set "Use UTF-8" and MySQL version is 5.5.3 or later, $_DB_charset (which is introduced in v2.1.2) will be set to "utf8mb4".  If MySQL version is lower than 5.5.3 or you're going to upgrade or migrate, $_DB_charset will be set to "utf8".  If you don't set "Use UTF-8", then $_DB_charset will be left empty.

**Comment by eSilverStrike** [comment]
I will try again and debug when I get a chance this week.  I know it happened as I did check it twice at the time of writing the issue. Maybe it is an IIS thing...

**Comment by eSilverStrike** [comment]
Okay I found the issue which was my mistake because the db-config.php file I was using was missing the following line
```
$_DB_charset = '';
```
so the line could never be updated with the correct information (which is utf8mb4) during the install when the version of MySQL was checked.
