### ISSUE TITLE
Geeklog Emergency Rescue Tool doesn't realize when Geeklog is not installed

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#752]
If I try and use the Geeklog Emergency Rescue Tool when Geeklog has not been installed on the DB it does not work properly and can error out. We should disable the options section of the page if Geeklog has not been installed. Instead we should display a message stating that it looks like that Geeklog has not been installed yet.

Maybe we can assume it is installed if the database_version is found in the gl_vars table?

**Comment by mystralkk** [comment]
I wonder if it is necessary to show a link to the Emergency Rescue Tool in the installer.

**Comment by eSilverStrike** [comment]
Fixed but Japanese language file needs updating for install. When you have a chance @mystralkk or @dengenxp?

**Comment by dengenxp** [comment]
Updated Japanese language file with change set 510e0c2
