### ISSUE TITLE
Old reference to 'HTTP/Request.php' found in Pingback and Links Plugin

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#755]
I notice this error in the log files.

Thu  2 Feb 07:52:59 2017 - 0.0.0.0 - E_WARNING(2) - require_once(HTTP/Request.php): failed to open stream: No such file or directory @ /pingback.php line 67  

Which comes from this line in the pingback.php:
```
    require_once 'HTTP/Request.php';
```

Looks like this call needs to be updated to use the upgraded libraries.

I also notice that this reference is the functions.inc file of the links plugin.

**Comment by mystralkk** [comment]
Fixed with change set 9ac7007
