### ISSUE TITLE
group permission editor bug

### ISSUE THREAD

**Issue by IamNaN2** [Geeklog-Core/geeklog#756]
I have used GL for a while - for mainly the static pages with PHP - but decided to upgrade to newest version as a replaced a computer that exploded. Did only this (but repeated it a couple of times on 2.1.2-b2)

Fresh install, 
Change password for Admin.
Go to the Static Page Admin group and try to give it PHP rights. Click Save.
Things look strange in the Admin column (link to static pages is gone), so I open the group editor again for this group. It now has not rights at all.
Try to add PHP rights to the other groups same thing happens - all rights lost.

**Comment by mystralkk** [comment]
Fixed with change set bd3e7e2
