### ISSUE TITLE
E_WARNING(2) - array_key_exists() expects parameter 2 to be array, null given @

### ISSUE THREAD

**Issue by AlexL777** [Geeklog-Core/geeklog#758]
Hello Developers,

I have unfortunately a problem after upgrade to Geeklog 2.1.2 RC1. If I am in the backend and want to call up settings, this error is displayed to me.

`E_WARNING(2) - array_key_exists() expects parameter 2 to be array, null given @ /xxxxxxxxxxxxxxxxxxxxxxxxx/geeklog/system/classes/config.class.php line 2141`
```
Call Stack
#	Function	File	Line
1	array_key_exists	/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/geeklog/system/classes/config.class.php	2141
2	_UI_autocomplete_data	/xxxxxxxxxxxxxxxxxxxxxx/geeklog/system/classes/config.class.php	908
3	get_ui	/xxxxxxxxxxxxxxxxxxxxxx/geeklog/admin/configuration.php	615
```

I have my Geeklog installation in the subdirectory and whether it can have something to do with it, I do not know.

Thanks in advance.

**Comment by eSilverStrike** [comment]
Looking for a bit more information...

Do you only have errors in the Geeklog Admin Configuration? Does the rest of the website work fine?

You mentioned you upgraded. What version of Geeklog did you upgrade from?

Do you have any extra plugins installed?

**Comment by AlexL777** [comment]
The error is displayed only under /admin/configuration.php. Previously I had Geeklog 2.1.2 b2 and made an update on RC1.

I do not have plugins installed today.

But there are even more problems with this problem.

I wanted to change my Geeklog website under http://wpzweinull.ch/geeklog to SSL, but this shot me the front end.

I have made adjustments with "site_url" in the MySQL database and also set "securecookies" in the database to the value "1".

But in the frontend of the website everything was mixed and not a proper design.

So what to do? I then deactivated SSL again, all changes undoed and now under /admin/configuration.php this error.

I had to reinstall Geeklog and now use the old database. Everything has worked so far, but the German umlauts is not displayed correctly.

As you can see a very big problem.

**Comment by eSilverStrike** [comment]
So Geeklog 2.1.2 b2 worked find then and you didn't have any errors? The admin section really didn't change from Beta 2 to Release Candidate 1. You just copied over the files correct for the upgrade? (there is no need to run the install)

Lets figure out the first issues and then look at SSL afterwards. For that you have to change the Site URL, Admin URL, and the securecookies. If you are changing the values right in the database you have to make sure you increase the number in the value as that refers to the length of the value. So the site url

```
s:22:"http://www.geeklog.net";
```
would become
```
s:23:"https://www.geeklog.net";
```
when you change it to https.

The best option would be to use the migration part of the install but I see that it does not allow you to update the secure cookies config value.  I will add a bug report for this.
