### ISSUE TITLE
Fatal error: Cannot redeclare class GL_Input in - Geeklog 2.1.2 RC 1

### ISSUE THREAD

**Issue by AlexL777** [Geeklog-Core/geeklog#759]
Hello Developers,

To me this time, I have noticed this error.

```Fatal error: Cannot redeclare class GL_Input in /xxxxxxxxxxxxxxxxx/system/classes/input.class.php on line 37```

No matter what I create, edit or add in the backend, this error appears in the frontend. Also the search in the portal does not work and the same error appears.

I have some plugins installed >> DokuWiki, Forum 2.9.2, Contact, GUS, Classifieds, PayPal Shop and others and I do not know if it can be because of it.

Can you please see this again.

Thanks in advance.

**Comment by eSilverStrike** [comment]
Is this a new website or one that has been upgraded?

Can you disable the non core plugins (you can use the rescue tool found in the install) just so we can rule them out at the moment. The core plugins are the ones that come with Geeklog like staticpages, calendar, links, spam-x, polls

**Comment by AlexL777** [comment]
I can solve the problem for myself. I installed a fresh software with Geeklog 2.1.1 and still no errors somewhere.

I know that with the many plugins can be very delicate, especially some plugins from the years 2014/15 and there they may need new plugin updates.

I would now rather wait until Geeklog 2.1.2 Finalversion appears.

But now I can work for the first time and reinstate all third-party plugins. If I get problems still, I turn to the developers here.

Thank you for taking the time.

**Comment by eSilverStrike** [comment]
Are you able to install Geeklog 2.1.2rc2 on your server without any problems? (a fresh install with no 3rd party plugins)

**Comment by AlexL777** [comment]
I installed b2 version first and then upgraded to RC2. Since my database was first with the character set of UTF8mb4, I could not install some plugins.

It is said on the Ubuntu Managed Server that this character set is taken as the standard. But I have converted the database again, but as far as I can remember, the plugin installation of some third-party plugins was not possible.

This is the present state of affairs with me.

**Comment by eSilverStrike** [comment]
Okay so Geeklog 2.1.2 RC2 should work then it is just some of the third party plugins when the database is set to UTF8mb4. I will be fixing the Gus one soon (https://github.com/Geeklog-Plugins/gus/issues/4).

I am going to close this issue then.
