### ISSUE TITLE
Checkboxes with the rights can not be activated - Geeklog 2.1.2 Beta 2

### ISSUE THREAD

**Issue by AlexL777** [Geeklog-Core/geeklog#760]
Hello Developers,

I had today under http://internetblogger.at for the plugin "Classifieds" create a new "default group". I also did that. I also have classifieds.publish rights.

Unfortunately checkboxes can not be activated. I click with the mouse on the checkbox, but when I call again the group, the checkbox is not activated.

In the frontend under Classifieds, I have as an admin no permission to create classifieds.

Can you please check this again. I've been sitting at the checkboxes for hours, but no success in sight.

Thanks in advance.

I am using Geeklog 2.1.2 Beta 2.

**Comment by mystralkk** [comment]
Group permissions editor had a bug as of 2.1.2 beta2, but it was fixed in release candidate 1.  Please use RC1 instead.
