### ISSUE TITLE
Update Docs to either include list of changed files or not since last release

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#762]
This file geeklog-2.1.2/public_html/docs/english/changes.html

claims that there is a "file docs/changed-files has a list of files that have been changed since the last release."

It does not seem to exist. 

We should either include the change file list or not and remove the text above from the docs. 

A way to get a list of changed files between commits is 

```git diff --name-only <commit1> <commit2>```

From this we would need to  remove any files (like from build directory) from this list that are not included in the actual install.

@mystralkk Is there a way we can automate this process when the install is built by Phing and create the file?

**Comment by dhaun** [comment]
This file used to be created by the old mkdist.sh shell script and effectively is done with a "diff" run over the current and previous release files:

diff -b -B --brief --recursive -N $OLDVERSION $NEWVERSION | grep -v 'system.pear' | cut -f 4 -d' ' >changed-files

So I guess the git diff could do the same. The old script removed non-shipping files and only compared actual release directories.

**Comment by eSilverStrike** [comment]
@mystralkk Can Phing handle this when the install is built?

**Comment by mystralkk** [comment]
I created a custom task for the "changed-files" file.  Implemented with change set 8562d94
