### ISSUE TITLE
Option for Developer Mode to to disable logging Call Trace or Depreciated errors

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#763]
It would also be nice in developer mode to disable depreciate error messages as they can get in the way of things when you are trying to figure out an error.

**Comment by mystralkk** [comment]
You seem to have implemented this feature in COM_deprecatedLog.

**Comment by eSilverStrike** [comment]
I think my plan was to be able to disable the depreciated error messages in developer mode if the developer wanted as when I was working on something I had to keep filtering through all the depreciation messages which was not relevant to the bug I was working on at the time.

It could work something like this (not pretty) in siteconfig.php 

$_CONF['developer_mode'] = true;
$_CONF['developer_mode']['log']['depreciated'] = false;

I was also thinking it would be a good way to add in other logging which exists in geeklog but all have to be activated separately like the template detailed logging system, database detailed error logging, etc...

$_CONF['developer_mode']['log']['template'] = false;
$_CONF['developer_mode']['log']['database'] = false;

**Comment by mystralkk** [comment]
I tried implementing this feature with change set 17e9064.  Currently, $_CONF['developer_mode_php']['error_reporting'], $_CONF['developer_mode_log']['database'], $_CONF['developer_mode_log']['deprecated'], $_CONF['developer_mode_log']['security'], $_CONF['developer_mode_log']['session'], $_CONF['developer_mode_log']['template'], $_CONF['developer_mode_log']['topic'] are supported.

**Comment by eSilverStrike** [comment]
Tried to test the Geeklog install (upgrading to 2.2.20) and the mysqli class has an issue when the COM_errorlog function is set for the error as the install doesn't have access to the function 

Fatal error: Uncaught InvalidArgumentException: function "COM_errorLog" is not callable in \geeklog\system\databases\mysqli.class.php:397

**Comment by mystralkk** [comment]
Fixed with change set 224ad7a
