### ISSUE TITLE
Add a Demo mode for Geeklog

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#765]
Add a demo mode that can be used on demo.geeklog.net.

The demo mode should hide certain configuration options and other features to protect the install.

Plugins should be able to hide config options and features in demo mode if needed.

**Comment by eSilverStrike** [comment]
I know there was a feature request for this before but I am not sure what happen to it. I didn't find it in a search.

Things to disable for demo mode include
- sending emails
- file manager

**Comment by eSilverStrike** [comment]
@mystralkk I've added the following config options to disable during the geeklog demo mode
`
                    'site_url','site_admin_url'
                    ,'url_routing'
                    
                    ,'path_html','path_log','path_language','backup_path','path_data','path_data','path_themes','path_images','path_editors','rdf_file'
                    
                    ,'path_to_mogrify', 'path_to_netpbm', 'image_lib'
                    
                    ,'custom_registration','user_login_method'
                    
                    ,'mail_cc_enabled','mail_cc_default'
                    
                    ,'facebook_login','facebook_consumer_key','facebook_consumer_secret'
                    ,'linkedin_login','linkedin_consumer_key','linkedin_consumer_secret'
                    ,'twitter_login','twitter_consumer_key','twitter_consumer_secret'
                    ,'google_login','google_consumer_key','google_consumer_secret'
                    ,'microsoft_login','microsoft_consumer_key','microsoft_consumer_secret'
                    ,'yahoo_login','yahoo_consumer_key','yahoo_consumer_secret'
                    ,'github_login','github_consumer_secret','github_consumer_key'
                    
                    ,'filemanager_upload_restrictions','filemanager_images_ext','filemanager_videos_ext','filemanager_audios_ext'
`

**Comment by eSilverStrike** [comment]
@mystralkk Should we disable emails in demo mode? Someone could spam email addresses by creating user accounts with other people's email address. Of course the demo site will be reset every hour but it is possible for someone to do this (or should we not worry about this)

If we disable emails then I guess we should include a on site message when emails are sent that they are disabled and maybe include the email in this on site message so testers can still log into new user accounts etc...

**Comment by mystralkk** [comment]
We should disable emails in demo mode for the very reason you said.

**Comment by eSilverStrike** [comment]
Hmmm.... In demo mode I was hoping to just store the email message in a global variable and then display it in the system message when it displays (like the one notifying new users that their password has been emailed). Problem is most of the time after an email is sent a redirect is used which obviously makes using a global variable no good. I really don't want to add to the user sessions table just for the demo mode to store the last mail message. Do you have any other ideas?

Maybe at some point we should switch to the PHP built in session management.

**Comment by mystralkk** [comment]
Using $_SESSION variable is the only solution.  So, we should switch to it in the near future.

**Comment by eSilverStrike** [comment]
Okay. I guess I will leave this open for now and as is (in most cases emails will be sent out).

I added feature request #828  regarding $_SESSION and set it to future. Do we want to try and fit this into v2.2.0?

If we decide to add/When we do add $_SESSION to disable emails in the demo mode we just need to add a check to COM_Mail for the demo mode and then save the email message to a session variable.

We then need to modify COM_showMessageText with something like below to then display the email if the session variable is found and then clear the variable.

```
function COM_showMessageText($message, $title = '')
{
    global $_CONF, $MESSAGE, $_IMAGE_TYPE;

    $retval = '';

    if (!empty($message)) {
        if (empty($title)) {
            $title = $MESSAGE[40];
        }
        list($timestamp,) = COM_getUserDateTimeFormat(time(), 'daytime');
        $retval .= COM_startBlock($title . ' - ' . $timestamp, '',
                COM_getBlockTemplate('_msg_block', 'header'))
            . '<p class="sysmessage"><img src="' . $_CONF['layout_url']
            . '/images/sysmessage.' . $_IMAGE_TYPE . '" alt="" ' . XHTML
            . '>' . $message . '</p>';
            
        if (isset($_CONF['demo_mode']) && $_CONF['demo_mode']) {
            if (!empty($_SESSION['LAST_EMAIL'])) {
                $retval .= '<p>Please note sending emails is disabled in Demo mode. The last email which would have been sent was:</p>' . $_SESSION['LAST_EMAIL'];
                $_SESSION['LAST_EMAIL'] = '';
            }
        }
        $retval .= COM_endBlock(COM_getBlockTemplate('_msg_block', 'footer'));
    }

    return $retval;
}
```

**Comment by eSilverStrike** [comment]
I am closing this feature since it mostly complete. Displaying Emails instead of sending them has been added as a new feature request (#843) to be done once we switch over to PHP's own Session management.
