### ISSUE TITLE
Links Plugin Category links are not working when URL Rewrite Enabled

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#766]
As reported in the forum: https://www.geeklog.net/forum/viewtopic.php?showtopic=96472

Links Plugin Category links are not working when URL Rewrite is enabled. Should double check when URL Routing is enabled as well.

Example URL Routing Link:

https://www.geeklog.net/links/index.php/Community

Normal link:
https://www.geeklog.net/links/index.php?category=Community

**Comment by mystralkk** [comment]
Fixed with change set db2a2ec
