### ISSUE TITLE
Install Oauth class and with Composer

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#769]
OAuth Class
https://www.phpclasses.org/package/7700-PHP-Authorize-and-access-APIs-using-OAuth.html

HTTP Protocol Client (required by OAuth class)
https://www.phpclasses.org/package/3-PHP-HTTP-client-to-access-Web-site-pages.html#download

**Comment by mystralkk** [comment]
Implemented with change set cda452d
