### ISSUE TITLE
for Google Apps SMTPS mail

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#773]
now I can't use with Google APPS email, because SSL mode is not set.

configuration please add  backend mode 'smtps' : 

'smtp'
'sendmail'
'mail'
and
'smtps' <===

/private/system/classes/Mail.php 
line 71:

```
            case 'smtp':
                $transport = \Swift_SmtpTransport::newInstance($_CONF['mail_settings']['host'], $_CONF['mail_settings']['port']);

                if (!empty($_CONF['mail_settings']['auth'])) {
                    $transport->setUsername($_CONF['mail_settings']['username']);
                    $transport->setPassword($_CONF['mail_settings']['password']);
                }

                break;
```

to:
```
            case 'smtp':

                $transport = \Swift_SmtpTransport::newInstance($_CONF['mail_settings']['host'], $_CONF['mail_settings']['port']);

                if (!empty($_CONF['mail_settings']['auth'])) {
                    $transport->setUsername($_CONF['mail_settings']['username']);
                    $transport->setPassword($_CONF['mail_settings']['password']);
                }

                break;

            case 'smtps':
                $transport = \Swift_SmtpTransport::newInstance($_CONF['mail_settings']['host'], $_CONF['mail_settings']['port'], 'ssl');

                if (!empty($_CONF['mail_settings']['auth'])) {
                    $transport->setUsername($_CONF['mail_settings']['username']);
                    $transport->setPassword($_CONF['mail_settings']['password']);
                }

                break;
```

**Comment by eSilverStrike** [comment]
I have added the feature and double checked the calls so it should work (http://swiftmailer.org/docs/sending.html) but it remains untested (since I don't have a way to test). Also the Japanese language and config.html file  still needs updated so I will leave this issue open.

**Comment by eSilverStrike** [comment]
SwiftMail using SMTPS also requires OpenSSL so I have added a note to the English language files about this for the Admin Environmental Check. This should be added to the Japanese language files as well.

**Comment by eSilverStrike** [comment]
@mystralkk or @dengenxp when you have time can you update the Japanese language files for 'openssl_ok'  and 'openssl_not_found' . See English changes for changeset ed6f18a. Japanese config file should also be updated: public_html/docs/japanese/config.html 

Once done this issue can be closed.

**Comment by dengenxp** [comment]
Updated Japanese language and config file with change set 510e0c2
