### ISSUE TITLE
Comment Submission Tooltips will show HTML Entities

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#775]
Comment Submissions tooltip for "Parent or Comment" column will show html entities (at least for comments on staticpages) if the comment has a quote in it. For example the tooltip should show
```
This is a "test'.
```
instead it shows
```
This is a &quot;test&quot;.
```
The tooltips are just the title of the link. Maybe we can also make these actual geeklog tooltips?

**Comment by dengenxp** [comment]
Fixed with change set 87bc2fc
