### ISSUE TITLE
Add color version of UTF8mb4 icons

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#787]
UTF-8mb4 Icons/emoji's can be displayed in colors like 😁, ❤ and 😊.

We need to update the fonts that the themes denim and modern curve are using (below may need changing I am not sure what the other fonts we are using)

```
body, h1, h2, h3, h4, h5, h6 {
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

**Comment by eSilverStrike** [comment]
Added changes to custom LTR css custom file only as per @dengenxp instructions. Changes still need to be added to the css source files.

Once that has been done and the css changes have been complied from the source this feature can be closed.

**Comment by mystralkk** [comment]
Modified a Stylus file and compiled into CSS files with changeset 3c2ae63.
