### ISSUE TITLE
Prevent Search Engines from visiting certain pages by adding noFollow or using robots.txt

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#789]
I notice a number areas that need to be double checked:

- User Profile Send Email Links
- Links to Print Pages (Story (icon link doesn't have one) and Staticpage)
- Post Comment Links (seems to be good) but post comment buttons can be followed (maybe add them to robots.txt file)
- Calendar future and past dates. Need threshold values in config to nofollow. See #262 for more info

**Comment by mystralkk** [comment]
Implemented with change set c40485a.  No addition to robots.txt is required.
