### ISSUE TITLE
Allow pages in the Staticpage Plugin to have a previous and next page

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#792]
Allow to specify  previous and next page in plugin (another staticpage so can make use of Geeklog Page Navigation for staticpages.

This means <link rel="prev" ... and <link rel="next" would also be set for search engine purposes.

**Comment by mystralkk** [comment]
Implemented with change set fa66c28.  I also bumped up the version of the staticpage plugin to 1.7.0.

**Comment by eSilverStrike** [comment]
What is parent id used for? 

It too bad we could not have an option to enable or disable page navigation for the static page but COM_printPageNavigation is not written to handle each page that has a unique id (which is not a sequential number).

**Comment by mystralkk** [comment]
Currently, parent id is not used.  I am thinking of making a tree-like menu system using staticpages, where we'll need parent-child relations between menu items.

**Comment by eSilverStrike** [comment]
I always thought an advanced menu system was needed in Geeklog and had one time though of including the Geeklog Menu plugin in to core: https://github.com/Geeklog-Plugins/menu

It's been a while since I have looked at it but wouldn't something like that be better for a menu system since you cannot only add staticpages but other items like articles?
