### ISSUE TITLE
$_CONF['cron_schedule_interval'] > 0 frontpage error

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#796]
if $_CONF['cron_schedule_interval'] > 0 , frontpage error  (PHP 7.1)

```
(This text is only displayed to users in the group 'Root')

E_WARNING(2) - A non-numeric value encountered @ /path_to_public/lib-common.php line 8685


Call Stack
#	Function	File	Line
1	require_once	/path_to_public/index.php	35
```

lib-common.php line 8685:

` if ($_CONF['cron_schedule_interval'] > 0 && COM_onFrontpage()) {   `

**Comment by eSilverStrike** [comment]
I can't reproduce this on PHP 7.1.1 

What is your $_CONF['cron_schedule_interval'] set as in the Geeklog Config?

**Comment by ivywe** [comment]
$_CONF['cron_schedule_interval'] set 86400
PHP Version:7.1.2

thanks.

**Comment by ivywe** [comment]
Onother PHP 7.1.1 works well. 
onother reason?
It may not be a bug. ??

**Comment by eSilverStrike** [comment]
It sounds like $_CONF['cron_schedule_interval'] is not set or is a non numeric value for some reason. Is this the only config value not working? Are other config values that contain just numbers working (like story cache time)?

After we get the config values from the database we use unserialize to get the proper information. I know that the php unserialize function has changed in PHP7 but I would have thought if it was a problem it would have affected PHP 7.1.1 as well

http://php.net/manual/en/function.unserialize.php

@dengenxp @dhaun @mystralkk Any ideals? This is not something I can test as I don't have PHP 7.1.2 installed.

**Comment by ivywe** [comment]
I found!

gl_vars:
`INSERT INTO `gl_vars`VALUES ('last_scheduled_run','');`
...error

`INSERT INTO `gl_vars`VALUES ('last_scheduled_run','1498061237');`
...ok

now last_scheduled_run is automatically set, the site works well.

**Comment by eSilverStrike** [comment]
Great. I also added a check for 'last_scheduled_run' to make sure it is a number. If not it gets set to 0.

**Comment by ivywe** [comment]
thanks!
it works nice!
