### ISSUE TITLE
Links Plugin - Cannot Edit Link

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#798]
When you click on the edit button beside the link (either in admin or on for example:

https://www.geeklog.net/links/index.php

you create a new link instead.

The id of the link is not getting passed properly. For fix see: https://www.geeklog.net/forum/viewtopic.php?showtopic=96468&lastpost=true

**Comment by ivywe** [comment]
https://github.com/ivywe/geeklog-ivywe/commit/b4c9ef76b893e67847249390446a27bf2e37f113
my repository are fixed, maybe.
