### ISSUE TITLE
apostrophe in group name

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Core/geeklog#800]
Is it normal not to be able to use an apostrophe in group names?

**Comment by eSilverStrike** [comment]
I don't think we should use them. 

This is similar to my question about user names #786

**Comment by hostellerie** [comment]
What could be the issue by using apostrophe in group name ?

**Comment by eSilverStrike** [comment]
Nothing particularly really. I just think special characters really should be used in system names. (not a huge deal really).

**Comment by eSilverStrike** [comment]
Decided to leave functionality as is. See #810
