### ISSUE TITLE
Group Assignments and Rights Issues

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#803]
According to Geeklog "Security Groups on this site are hierarchical."

For the initial discussion started by remy see: https://www.geeklog.net/forum/viewtopic.php?showtopic=96573

There appears to be issues with assign groups within groups. It is not clear if a user is inherited from another group or not.  GL should distinguish between permanent membership and inherited membership.

**Proposal to Fix**: The admin screen should reflect the state of the membership, either permanent (blue), either inherited (proposal: green). Than, GL only updates the table according to the blue tick boxes and ignores the green ones.

This can be done by a select value, rendered as a tick box. Whereas a mouse hover can reveal the parent group(s). This eliminates the need for a tree view (and the hidden code for shadowed tick boxes). 

**Confirm this is not possible with groups - A belongs to B, B belongs to C, and C belongs to A.**

-----------------------------------

There exists a similar issue with the rights admin screen. The effects are even more confusing.

**Example:** Include polls admin in a group. The polls admin rights show now with a shadowed tick box.
Try to edit this group to remove just one (polls) right. Impossible. Just save now.
After you tried this, the next screen shows blue ticket boxes. Remove one (polls) right. Save.
GL won't let you do this. The right returns with a shadowed ticket box.
Damn. Than remove the group polls admin from that group. Now you get those polls admin rights permanently with blue ticket boxes (out of the blue).

Sometime I was even able to let toggle some poll admin rights between blue and shadowed without even having the poll admin included.

This screen also could make use of the proposed green ticket boxes. It than shows which rights are inherited (they show now as shadowed ticket boxes, until the group is saved again) and which rights are permanent. Than Admin can choose if he wants to make one of these inherited rights a permanent one. Currently this is only possible by adding polls admin, save twice, remove polls admin and save, than remove the desired permanent rights. Not very intuitive.

**Comment by remyKobolski** [comment]
Assume 3 groups: G1 contains G2 contains G3.
Whenever a user, say M1 joins G3, membership in G2 and G1 is assumed (inherited).
Whenever a user, say M2 joins G1, than G2, than G3 the memberships view is the same, though the database is different (group assignment):

case (A):
G1 -> G2, M2
G2 -> G3, M2
G3 -> M1, M2

As soon as M1 is updated, even without a change, the database will look like:

case (B):
G1 -> G2, M1, M2
G2 -> G3, M1, M2
G3 -> M1, M2

The question is now, what should be the designed case, case (A) or case (B).
When case (A) is designed, than updates should avoid making M1 (permanent) member of G1 and G2.
When case (B) is designed, than the join of M1 in G3 should result in the auto-join of M1 in G2 and in G1.

The GL code supports case (A) and case (B). The API seems to be unaware of case (B). The admin update scripts seem to be unaware of case (A).

Worst case.
I have >1000 groups in my system. Whenever I add a system admin to the Root group, I get >1000 rows extra in the table 'group_assignments' (when saved twice) which makes it virtually impossible to remove the system Admin again.

Same story for rights.

**Comment by eSilverStrike** [comment]
No matter what, we need to fix the admin interface. The color idea remy proposed I like.

Groups can belong to 0 to many groups. We will have to make sure that the admin interface doesn't allow for groups to circle back and be assigned to themselves again (i.e. A -> B -> A)

The Geeklog upgrade procedure will also have to be updated to check for this group assignment circle. If found the upgrade cannot start until fixed.

While we are at it I wonder if we should add a unique alias to each group that cannot be changed. Something based on the plugin short name and the name of the group for example "staticpage.admin". A lot of plugins use the name of the group (which can be edited by the admin). When the plugin is deleted these edited groups get left behind.

To fix the underlining problem of group hierarchy's I see  2 options:

**Option 1**
Fix the admin interface and leave things pretty much the same where a record is generated for each group the user belongs to (even if it belongs to a hierarchy or not). Doing it this way means for the most part we can leave the security functions like SEC_getUserGroups alone. We would have to add a column to the group assignments table though to track what records are part of the hierarchy (which would be used by the admin interface so records are added and deleted properly). Doing it this way should keep things fast but it does mean the group assignment table has the potential to be very large.

**Option 2**
The second option would be to only have user group records the user specifically belongs too exist in the group assignment table. Any inherited groups the user belongs to would be figured out when COM_getPermSQL (and any other security function) is called by Geeklog. This could become very slow but since security permissions only get updated every so often we could cache these results (like we do for the topic assignments). Doing it this way is much cleaner but would also require updating a number of existing security functions.

**Notes**
 COM_getPermSQL is used by Geeklog and it's plugins all over the place to return part of a SQL statement that lists groups that the user belongs (COM_getPermSQL then uses SEC_getUserGroups). At least I hope everything uses COM_getPermSQL... (if not making changes will break things) anyways all security group functions like SEC_inGroup would also have to be updated.

I like option 2 myself. Any thoughts on this @dengenxp, @dhaun , @mystralkk?

**Comment by remyKobolski** [comment]
Maybe it is enough to show inherited groups in the admin group screen (group.php and user.php) as shadowed (i.e. read only). This can support both case (A) and case (B). Though It has not the same features as proposed with green tick boxes, but a keen Admin will feel the common sense of it. And current (API) code does not have to change.

@eSilverstrike:
An additional column does not solve anything, but will introduce maintenance problems.
To figure out inherited groups (or inherited rights) is always slow. Option 1 does not speed up because the GL code will drill down the inherited tree anyway. So, to my opinion, the way to go is to adjust the admin feature scripts user.php and group.php.

**Comment by remyKobolski** [comment]
Patched my system for the bulk of oddities. Patches are attached.

Whenever SEC_getUserGroups is called WITH parameter $uid, a second global array is created, which is used in formatting the listings. This works for the group screen of admin/user.php and the rights screen of admin/group.php. Though the maning of the global array is misleading; it should be named $_MAINGROUPS as opposed to $_INHERITED.

It is important to understand the hidden items when the tick boxes are shadowed. I removed them and this avoids blowing up the table group_assignments, so there is only case (A) in the database.

I'm sure a core developer can adjust these patches to fit in the coming release(s).

[patch_seclib.txt](https://github.com/Geeklog-Core/geeklog/files/1228763/patch_seclib.txt)
[patch_adminlib.txt](https://github.com/Geeklog-Core/geeklog/files/1228764/patch_adminlib.txt)

**Comment by eSilverStrike** [comment]
Thanks. I will review and add the patches when I get back. I want to setup some test groups and users, and some stories on my dev server and make sure hierarchies work as expected based on our previous conversations.

**Comment by eSilverStrike** [comment]
Okay I added the patches and looked around the code a bit more. 

We still need to add a few things:
- On the group edit form. Security groups that are already inherited should be checked and disabled. Doing this will prevent Group 1 from being able to inherit itself by accident
- We should mention in the Security Groups and Rights descriptions what a disabled and checked group or right means (that it is inherited)
- User Group Administration Page (accessible from group list) - Doesn't work with inherited users. Shows inherited users as Available members and Group Members. Should probably indicate the group members that are inherited only and don't allow them to be removed from the list box or some other idea as it can get confusing
- Users in group Page (accessible from group list) - Maybe include description indicating these users either belong to the group or an inherited group of this group

**Comment by eSilverStrike** [comment]
Okay I have added in the above items so this issue should be fixed now.
