### ISSUE TITLE
User Account Delete Option is the default button on the My Account Page

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#808]
This probably can be dealt with in the theme templates but I notice if you change something in My Account (usersettings page) and press enter the delete account button will be pressed.

Obviously the User Delete option has to be enabled in the Config for this to happen.

I think it also makes since to move the delete option and information block below the save and cancel buttons

**Comment by eSilverStrike** [comment]
Actually moving the delete button doesn't make sense since it requires the "Current Password" field.

Looking at this further the only way I see to fix this after some research is adding javascript. Not sure if this is worth doing If no one else sees an easier fix I will just close this issue.

**Comment by mystralkk** [comment]
How about changing the delete button into a chekbox (default unchecked)?  When someone wants to delete their own account, they have to check the delete option and click on the save button.

**Comment by mystralkk** [comment]
Fixed with change set bea6c03.
