### ISSUE TITLE
Protect User Login Form from Brute Force Attacks

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#809]
How can we better protect Geeklog user login form from hackers?

We already have a speed limit on logins.

Some Ideas:
- Add recaptcha to the login page? (maybe invisible recaptcha if the plugin supports it https://github.com/Geeklog-Plugins/recaptcha/issues/2)

- Log all attempts of incorrect passwords used during logins

- Send email alerts to regarding invalid password attempts on accounts (maybe for root accounts only and only after speed limit???)

- Add some sort of support for Ban plugin if password incorrect x number of times in x number of seconds.

- Add config options for restrictions to password quality (like length, alpha and/or numeric, etc...)

Any other ideas?

**Comment by mystralkk** [comment]
How about adding a two-factor authentication?  Making it optional for ordinary users but making it mandatory for admin users?

**Comment by eSilverStrike** [comment]
That would be an option as well.

**Comment by eSilverStrike** [comment]
Okay added user logging of incorrect passwords.

Also added captcha support for login and get password form. So Geeklog should be ready when support for the two forms are added in the recaptcha plugin except for maybe a few tweaks. The 2 forms call the function PLG_templateSetVars and are named "getpassword" and "loginform" (which was already in place). 

SECINT_authform (which asks user to reauthenticate because of token issue) disables PLG_intemplateSetVars. So should make sure this all works properly (captcha shouldn't display for reauthentication) in case of a time out.

Also Modern Curve template for login form may need tweaking to look right.

**Comment by eSilverStrike** [comment]
@mystralkk I with thinking of adding 2 columns to the users table. The first column would track number of invalid login attempts for the user and the other would be a timestamp. This would work with 2 new config options which would be X number of login attempts  allowed in X number of seconds for a user. Basically if the threshold is reached an email would be sent to the admin regarding an assumed attempt to hack the account (or a user just forgot his password. I would also setup a plugin api that would notify any plugins listening (so the ban plugin could be setup to temporarily ban the IP if wanted).

Do you think this is needed? It should prevent hack attempts on users especially if recaptcha is not enabled/installed.

**Comment by mystralkk** [comment]
I agree your idea will work well.

**Comment by mystralkk** [comment]
I want to add a package from a packagist https://packagist.org/packages/robthree/twofactorauth to Geeklog, but somehow I cannot.  I would appreciate it if you would add this module through composer to Geeklog.

**Comment by eSilverStrike** [comment]
It seem to install fine for me (I am not super experienced with composer). I added the composer.phar file to the system\build directory and ran it from there

php composer.phar require robthree/twofactorauth

It updated some files in 

system\build\composer\

and then added a bunch of the robthree library files to

system\build\vendor\robthree

I didn't get any errors. You want me to commit to the master branch or create a new  branch feature/twofactor ?

**Comment by mystralkk** [comment]
Please add the composer.phar to /system instead of system/build and 

php composer.phar require robthree/twofactorauth

and a create a new  branch feature/twofactor.

**Comment by eSilverStrike** [comment]
That is what I initially tried in the system directory since those are the libraries for Geeklog. I added the composer.phar file and ran the command but I get the error:

[InvalidArgumentException]
Could not find a matching version of the package robthree/twofactorauth

Looking on the web now to see if I can find a solution. Is this the same error you got?

**Comment by eSilverStrike** [comment]
Okay I got it to work. In system/composer.json I took out the code

```
  "repositories": [
    {
      "type": "composer",
      "url": "https:\/\/www.phpclasses.org\/"
    },
    {
      "packagist": false
    }
  ]  
```
and was then able to add the package. I then added the above code back into the new composer.json file. (or should I leave it out?)

Changed files include

system\composer.json and composer.lock
system\vender\autoload.php
system\vendor\composer\ (some autoload files)
system\vendor\robthree\ (40 or so files)

Should I leave that code out of the composer.json file? Let me know and then I will add the branch.

Tom

**Comment by mystralkk** [comment]
Thanks a lot.  I had the same error you had.

**Comment by eSilverStrike** [comment]
Okay I added the branch and I added the code back into composer.json that I took out. Not sure if we will need to take it out again when the package needs updating.

**Comment by mystralkk** [comment]
I added two factor authentication to the master branch.

**Comment by eSilverStrike** [comment]
While working on #757 I realized that we don't have any restrictions on password quality which is a big No, No in my opinion. Users can enter a password with 1 character if they wanted. We should have some configuration options that allow admins to set min password lengths and maybe even other quality issues like having both alpha and numeric characters, etc...

This would affect a number of systems including 
- when we send new passwords for new users
- User changing their password in user settings
- User requesting new password from Forget Password Page
- User that is set to status of New Password required

**Comment by eSilverStrike** [comment]
@mystralkk Should we just require new passwords to have a minimum of 8 characters and at least 1 of each alpha, numeric, and special character?

Or should we make this somewhat configurable for Admins?

**Comment by mystralkk** [comment]
We should require users have stronger passwords.  So, this feature don't have to be configurable.

**Comment by eSilverStrike** [comment]
Okay what should the requirement be then? I am thinking:

- minimum of 8 characters
- at least 1 number
- at least 1 letter (small or capital)
- at least 1 symbol (punctuation and whitespace)

Also the password will be case sensitive.

Sound good?

**Comment by mystralkk** [comment]
Sounds good, except for "at least 1 symbol (punctuation)."  This may be good for admins, but too strict for non-admins.

**Comment by eSilverStrike** [comment]
Okay passwords now must contain 8 characters and have at least 1 letter and 1 number in it. New user passwords are generated with this in mind and checks have been added for:
- User changing their password in user settings
- User requesting new password from Forget Password Page
- User that is set to status of New Password required
