### ISSUE TITLE
Trying to use mb4 Characters in User Names causes SQL Error

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#810]
UTF-8mb4 Icons/emoji's like ❤ and 😊 are being used in User Names. For some reason using UTF-8mb4 Icons along with ' causes a sql error (for new users and updates). Should check all 3 places user names can be added/edited like Admin User Form, New User Form, and User Settings page.

Maybe DB_escapeString for some reason cannot handle this?

After a quick check of the code I notice that GLText::remove4byteUtf8Chars also is not being used to check to see if even the database can handle the icons (the one I was testing could) in usernames and other user fields.

It would almost be easier to not allow icons and some special characters in User Names (but some other user fields should be okay)

This is also related to issue #786 and #800

**Comment by mystralkk** [comment]
What is the value of $_DB_charset in db-config.php?  Unless it is 'utf8mb4', the database driver operates assuming it is 'utf8'.  When you upgraded Geeklog from v2.1.1 to v2.1.2, $_DB_charset was added as 'utf8', so you might want to change it manually.

**Comment by eSilverStrike** [comment]
Good point I hadn't checked that. Just checked and it is already set to 'utf8mb4' so that is not the issue. I haven't had time to really dive into the issue. Are you able to reproduce if when you save a user name like:

Test❤'12

Also what are you thoughts on having names (like user and groups) contain icons and special characters?

**Comment by mystralkk** [comment]
I created a user named Test❤'12 without errors.  I'm using PHP 7.1.10 and MySQL 5.7.18 on Windows 10. 
 $_DB_charset is 'set to utf8mb4'.  As for icons and special characters, I think all valid utf-8 characters including icons and Chinese characters should be allowed.

**Comment by eSilverStrike** [comment]
Sounds good. I will close the other issues and leave this one open until I confirm why mine is failing.

**Comment by eSilverStrike** [comment]
Okay I found the error. For some reason the collation for columns in my user table was only utf8_general_ci. Once I switched them to utf8mb4_general_ci every thing worked fine.

I also added checks for the user information if the config option "remove_4byte_chars" is set mb4 characters will be removed from the user information.
