### ISSUE TITLE
Article Dates Calendar Picker year can go back farther than Dropdown Year

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#811]
In the Article editor when using the jQuery Calendar picker you can go back more than 1 year but in the Dropdown in the editor can only go back to the previous year. This happens with:

Publish Date
Archive Date
Disable Comment Date

This means you can pick a year via the picker that is not available in the dropdown which results in the incorrect date being saved.

**Comment by mystralkk** [comment]
Fixed with change set 6afb02c
