### ISSUE TITLE
Remove some small tables from database

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#821]
The tables below are read-only and are just used to make a list of options in COM_optionList().  I am thinking of dropping these tables and changing COM_optionList() or creating a new function to return the original lists.  Thoughts?

- $_TABLES['commentcodes']
- $_TABLES['commentmodes']
- $_TABLES['cookiecodes']
- $_TABLES['featurecodes']
- $_TABLES['frontpagecodes']
- $_TABLES['postmodes']
- $_TABLES['sortcodes']
- $_TABLES['statuscodes']
- $_TABLES['trackbackcodes']

**Comment by eSilverStrike** [comment]
Yeah I never really understood the use of those tables. I guess the plan was to make it easier to add options to the different core features but those options would still have to be coded for, so what was the point...

Maybe @dhaun knows?

I think the best option is what you suggest, remove the tables from the database and hardcode the lists in a function. It will make retrieving the information a little faster.

**Comment by mystralkk** [comment]
Implemented with changeset 6f80123.
