### ISSUE TITLE
Anonymous Name Cookie Issue when URL Routing Enabled

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#823]
A very weird error that appears to only happen if you post an anonymous comment that has a anonymous username with emojis in it (mb4 characters). It does not matter if the config option remove_4byte_chars is set to true or false

After you post the anonymous comment with the anonymous username

George 😣 1

Login as Admin and then if you enable URL Rewrite and URL Routing, if you visit a topic page or an article page you will get the following error. This does not happen when URL Routing is disabled.

E_ERROR(1) - Invalid cookie: 'anon_name=George 1' @ ...\geeklog\system\vendor\pear\http_request2\HTTP\Request2.php line 560

Call Stack
--
1 | COM_handleException |   |  

array(3) {
  [0]=>
  array(6) {
    ["file"]=>
    string(57) "...\geeklog\system\classes\router.class.php"
    ["line"]=>
    int(91)
    ["function"]=>
    string(9) "addCookie"
    ["class"]=>
    string(13) "HTTP_Request2"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(2) {
      [0]=>
      string(9) "anon_name"
      [1]=>
      string(9) "George  1"
    }
  }
  [1]=>
  array(6) {
    ["file"]=>
    string(57) "...\geeklog\system\classes\router.class.php"
    ["line"]=>
    int(268)
    ["function"]=>
    string(5) "proxy"
    ["class"]=>
    string(6) "Router"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(1) {
      [0]=>
      string(58) "domain_name/article.php?story=script-switch-check"
    }
  }
  [2]=>
  array(6) {
    ["file"]=>
    string(47) "...\geeklog\public_html\index.php"
    ["line"]=>
    int(102)
    ["function"]=>
    string(8) "dispatch"
    ["class"]=>
    string(6) "Router"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by mystralkk** [comment]
Oh, I escaped cookie name and values in the wrong way.  Probably, changeset ba71400 has fixed this issue.
