### ISSUE TITLE
groupAssignments improvement

### ISSUE THREAD

**Issue by remyKobolski** [Geeklog-Core/geeklog#826]
[modelsforhierarchicaldata-100520123959-phpapp02.pdf](https://github.com/Geeklog-Core/geeklog/files/1545579/modelsforhierarchicaldata-100520123959-phpapp02.pdf)

Refer to attached pdf, topic ClosureTable.

proposal: add to the group_assignments table a row, so that the group refers to itself. 

As far as I can see, this will not interfere with core code. However, a group hierarchy query can be done with just one sql statement. Queries can be executed to retrieve all ancestors (retrieve rights), all descendants (to avoid circularity) and even the complete tree. 
Well, the associated sql has to change, and the user/group admin script can be made more transparent. Also, the row has to be inserted for any new group and deleted when a group ceases to exist. Deletion of the row while the group still exists must be denied.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
