### ISSUE TITLE
Switch from Geeklog's Session library to the built in PHP Sessions

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#828]
Use $_SESSION variable to manage Geeklog Sessions. This will make it easier to add variables when needed.

Is this a good idea? 

Are there any other advantages or disadvantages over the Geeklog Session library?

**Comment by eSilverStrike** [comment]
Not sure if this is needed but I came across this drop-in library called Zebra_Session

https://github.com/stefangabos/Zebra_Session/

It is a drop-in replacement for PHP's default session handler which stores session data in a MySQL database, providing both better performance and better security and protection against session fixation and session hijacking. Not sure if is faster or not but it should be easy to test and would allow us to support 2 session handling types (file or MySql)

**Comment by eSilverStrike** [comment]
@mystralkk saw you are working on a new session class that uses PHP sessions 585dbdb0641be2043b7791135279ee984386a503

So just updating this issue and we should also take a look at  the related issues mentioned above (and summarized here):

- Zebra Session: apparently a drop-in replacement for PHP sessions that allows the use of session handling with MySQL. Users can switch if they want. Is this worth adding?
- Demo Mode emailing #843 
- #842

**Comment by eSilverStrike** [comment]
> Zebra_session class requires MySQL, so if we use this class we will have to give up supporting PostgreSQL users.  Besides, though this class doesn't  require InnoDB engine, those who use MyISAM engine will end up corrupting database tables.

Just a though about  your comment via email @mystralkk that we can consider later

Zebra Session would have a config option to enable or disable. We could force the Zebra session tables to be created with InnoDB in MySQL. For PostgreSQL users would not have the option to enable the config option.

At some point I was also considering maybe dropping PostgreSQL support. None of us use it or test the PostgreSQL code.  As far as I know it has been about 3 years since someone has. What are your thoughts on this?

**Comment by mystralkk** [comment]
Till some point in the past I did test the code for PostgreSQL, but I have to admit I haven't run a Geeklog site with PostgreSQL at backend.  So, it is quite likely that support for PostgreSQL is only partial and broken.  I agree to drop PostgreSQL support in the near future.

**Comment by mystralkk** [comment]
I implemented the Session class and replaced GL's session library with it (change set 9c0fe2f).

**Comment by eSilverStrike** [comment]
That's great. I'll do some testing when I get back from vacation near the end of August. I also plan on working on a few other features and bugs

**Comment by eSilverStrike** [comment]
Things look good. haven't had any issues so far so closing...

**Comment by eSilverStrike** [comment]
@mystralkk Just wondering if the directory and file 

/data/session/index.html

is needed that you committed from last year?

If it is I will need to update the Geeklog clear cache function to not delete the directory and file.

**Comment by mystralkk** [comment]
I originally created the directory and the file to store session files there, but I don't use them for the present.  So, there are not necessary now.

**Comment by eSilverStrike** [comment]
Okay I removed them then. Just trying to clean up the last few issues in milestone 2.2.1 so we can do a beta version
