### ISSUE TITLE
After token expired you can re-authentication with any existing user

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#842]
After token expired you can re-authentication with any existing user using their username or password. This means an Admin can edit an article and leave it and let the token expire. A user with no admin rights can then come along and re-authenticate with his own correct user name and password and save the article and then get access to the Admin account since the re-authenticated user is not actually logged in.

Re-authentication should only happen with the user account that is currently logged in.

**Note:** Also user can attempt as many logins as he wants. Should maybe only allow the same amount as the normal login.

**Comment by eSilverStrike** [comment]
Below is a note based on a few emails sent out discussing the issue. It was determined that it is not a not a  serious bug as long as you don't share your PC with others.  In order to fix this issue, it would be necessary to use PHP's native session mechanism and store the current user id in $_SESSION variable.  So I would put off handling this issue till Geeklog uses PHP's native session.

I have linked this issue up with others which should all be solved at the same time when sessions are added.

**Comment by eSilverStrike** [comment]
Related to converting to use PHP Sessions:
#828  Switch from Geeklog's Session library to the built in PHP Sessions
#765 Add a Demo Mode for Geeklog (would allow us to display emails on screen instead of actually sending emails)
#488 Content lost during OAuth login (Allow OAuth and OpenID to re-authenticate on saving if token expired)

**Comment by mystralkk** [comment]
With Session class implemented, you can get the id of the current user by calling

`Geeklog\Session::getUid()`

**Comment by mystralkk** [comment]
Fixed with change set f37507a
