### ISSUE TITLE
Option to allow Demo Mode to Display Emails instead of Actually Sending them

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#843]
Related to issue #765 when we added the demo mode. These are the main points below about this feature.

It has been determined someone could spam email addresses in demo mode by creating user accounts with other people's email address. Of course the demo site will be reset every hour but it is possible for someone to do this.

If we disable emails then we should include a on site message when emails are sent that they are disabled and include the email in this on site message so testers can still log into new user accounts etc...

I was hoping to just store the email message in a global variable and then display it in the system message when it displays (like the one notifying new users that their password has been emailed). Problem is most of the time after an email is sent a redirect is used which obviously makes using a global variable no good.

It was determined the best option is to use $_Session variable to store the email message to display after the redirect.

**Comment by mystralkk** [comment]
Implemented with change set 8e2c2e6.

**Comment by eSilverStrike** [comment]
@mystralkk Hey I just added a commit that adds the ability to show multiple emails at once in demo mode. I added a session variable system-msg array which will then be displayed by COM_createHTMLDocument (which once displayed then clears the session variable).

The session variable system-msg is designed to be used by anything in Geeklog (sort of like the post variable $msg) so I created a function called COM_setSystemMessage to protect the setting of this variable. It's not strictly just for the demo mode.

Question - This session variable can be displayed by the same page load (for example with Admin Mail Users form) and by on a new page load (for example emailing an article to someone).

What's the difference between Session::setVar and Session::setFlashVar? I ended up using Session::setVar since the other flash function wouldn't work on the same page load.

**Comment by mystralkk** [comment]
Variables set by Session::setVar() will be remembered as long as the session is alive.  No matter how many pages in Geeklog you load, such variables persist.  On the other hand, variables set by Session::setFlashVar will only be valid till the next time you load a page in Geeklog.  So, if you process form $_POST variables and want to set some message for the user, it is handy to set the message by using Session::setFlashVar, redirect the user and show the message by Session::getFlashVar.  You don't have to reset session variables manually.

**Comment by eSilverStrike** [comment]
That's what I thought. 

When COM_mail is used by some feature in the Geeklog demo we don't know if the final page is the current page being loaded or will end in a redirect. With Admin Mail Users page it all happens in one page load which for some reason COM_createHTMLDocument could not access the Session Flash variable to display the system message. So the Session flash variable is not accessible in the same page load but works fine on a new page. So I had to use regular Session variable since I could access it both wasys as needed.

Is it possible to get Session::getFlashVar to work on the same page load as when you set it like Session::getVar?

**Comment by mystralkk** [comment]
It is not with current implementation since variables retrieved by Session::getFlashVar are taken out from $_SESSION variable only when the Session class is initialized.  To do what you want to, it would be necessary to make something like Session::setVarOnce.  Variables set by the method will be accessed only once in the same/new session.

**Comment by eSilverStrike** [comment]
Sounds good. I will leave things as is then.
