### ISSUE TITLE
Theme add css: Reset iOS css style for form button

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#848]
Reset iOS css style for form button

```
input[type="submit"],
input[type="button"] {
  border-radius: 0;
  -webkit-box-sizing: content-box;
  -webkit-appearance: button;
  appearance: button;
  border: none;
  box-sizing: border-box;
  cursor: pointer;
}
input[type="submit"]::-webkit-search-decoration,
input[type="button"]::-webkit-search-decoration {
  display: none;
}
input[type="submit"]::focus,
input[type="button"]::focus {
  outline-offset: -2px;
}
```

learn more
https://qiita.com/_upto_me_/items/b35f405a87a2dc56fd48

**Comment by mystralkk** [comment]
Added these CSS styles to "additional.css" of respective themes

**Comment by eSilverStrike** [comment]
I reached out to @dengenxp a while back and didn't hear anything back. Not sure if you want to try? In the absence of Dengen I guess are best course of action is to continue to add any css changes to the additional.css file you created. In the next version of Geeklog if we still have not heard back we can either update the css source files ourselves (something I have yet to look into really)

geeklog/public_html/layout/denim_three/css_src/

to generate new css files or think of another solution.

**Comment by mystralkk** [comment]
Maybe he is too busy or has already lost interest in Geeklog...  It would be no use my trying to contact him for now.  By the way, I didn't create "additional.css"; I just added the CSS code to existing "additional.css".

**Comment by eSilverStrike** [comment]
Sounds good.
