### ISSUE TITLE
Update the Geeklog Installer to Uikit 3

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#849]

**Comment by mystralkk** [comment]
Partially implemented with change set 28bdba2.  The installer works fine, but it has some parts that look a bit strange.  I would appreciate any help since I am not good at UIkit.

**Comment by eSilverStrike** [comment]
Yup I will take a look.

**Comment by eSilverStrike** [comment]
FYI I am currently updated the install templates for uikit3

**Comment by mystralkk** [comment]
Thanks!
