### ISSUE TITLE
Geeklog 2.1.3 in new Hosting - cannot find Language folder

### ISSUE THREAD

**Issue by AlexL777** [Geeklog-Core/geeklog#852]
Hello Developers,

I have an issue installing Geeklog 2.1.3 in the new webhosting. I adjusted the old database to replace the paths with find and replace.

But in the frontend at http://geeklog.cms-blogger.eu the language can not be found.

The content of my siteconfig.php looks like this.

    // $_CONF['developer_mode'] = true;

    $_CONF['path'] = '/home/cmsblogg/geeklog.cms-blogger.eu/';
    $_CONF['path_system'] = $_CONF['path'] . 'system/';

    $_CONF['default_charset'] = 'utf-8';

    $_CONF_FCK['imagelibrary'] = '/images/library';

    $_CONF['language'] = 'german';
    $_CONF['path_language'] = '/language/';`

What am I doing wrong or what am I not considering yet?

Thanks in advance.

Alexander

**Comment by eSilverStrike** [comment]
There are more paths than that. I would assume the language path should be

/home/cmsblogg/language/

but I don't know how you have copied over all the files so it could be wrong.

The best way to change hosts is to run the Geeklog install again (for Geeklog 2.1.3, just download the package on Geeklog.net and copy over the install directory in the admin directory) and pick the migrate button. It will change all the paths for you automatically.

**Comment by AlexL777** [comment]
Thank you for these hints and I got it. The path to the language in the siteconfig.php must be like this:

    $_CONF['path_language'] = '/home/cmsblogg/geeklog.cms-blogger.eu/language/';  

So it worked immediately.

Now the problem is solved and you are welcome to close the issue.
