### ISSUE TITLE
[Feature request] Feature to put Geeklog in read-only mode.

### ISSUE THREAD

**Issue by darkshram** [Geeklog-Core/geeklog#856]
Recently there was a critical power failure at the data center where I host my Geeklog web site. So added an A record in the DNS servers to have www point at 2 IP addresses and quickly and **temporarily** set up a back-up in another server. The thing is I would like to have the back-up server to stand only until main server is online again and do not want any user to post anything there (main activity happens in Forum).

So it would be great to have a feature to put all Geeklog in a read-only mode or this kind of scenarios, specially because I plan to keep the back-up server. Maybe have the Geeklog to indicate it in <title>Web site - slogan (read-only mode)</title> and disable all the 'post' buttons.

**Comment by eSilverStrike** [comment]
This is not really possible. Geeklog has no control over what plugins like the forum can post. If the plugin supports Geeklog's security model then you could modify the security of the group dealing with posting of content to disable submitting of content.

It sounds like you really just want this issue for the forum. You can add the feature request here:

https://github.com/Geeklog-Plugins/forum/issues

Currently with the forum you can only enable or disable posting for anonymous users. We could expand on this config option. Or possibly we could addin a new user group which would allow more fine grain control over who could actually post.
