### ISSUE TITLE
Phing Language Batch File Does not Remove Language Variables when Synching

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#857]
We run phing language batch file to synchronise all the other language files to the English language file.

I notice that when I had to remove a language element from an array that when I synched the other files by running the batch it did not get removed from the array. The element had to be removed as it dealt with filling a select list with options found  in $LANG_postmodes. Therefore I had to remove the element manually.

**Comment by eSilverStrike** [comment]
Note: The batch does delete variables from other variables in the languages files but not  $LANG_postmodes (and maybe others?)

**Comment by mystralkk** [comment]
I changed some files for building.  Could you check if the syncing process works fine now?

**Comment by eSilverStrike** [comment]
@mystralkk Seems to work (it removes and deleted variables from array) except that with the current repository the batch file is hanging on the install language files. I had to control C to exit from the batch file. 

In the install language directory I see 2 extra files "_list.php" and "_list.php.tmp". All language files (including those for Geeklog and the plugins) do seem to be updated though.

I ran the process 4 times and twice it went through successful (with no extra files) the other times it hanged. I didn't commit any of the changes so you could try it yourself a few times to see if you have any issues.

**Comment by mystralkk** [comment]
I changed some build files and they seem to work fine now.
