### ISSUE TITLE
Installer - Migrate with an Upgrade doesn't for some reason doesn't update plugin version number at end of plugin upgrade function 

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#859]
When running the Geeklog installer 2.2.0, I select migrate (which also updates the DB which is at Geeklog version 2.1.2 on my test server) 

Migrate that also upgrades the plugins doesn't for some reason run the update sql statement with DB_Query near the  end of the function plugin_upgrade_staticpages. It is suppose to update the plugin version number, etc... in DB:

`DB_query("UPDATE {$_TABLES['plugins']} SET pi_version = '$code_version', pi_gl_version = '{$inst_parms['info']['pi_gl_version']}', pi_homepage = '{$inst_parms['info']['pi_homepage']}' WHERE pi_name = 'staticpages'");`

plugin_upgrade_staticpages works fine in all other cases. It works fine when just upgrading Geeklog from the installer (no migrate) and just upgrading the plugin from the Geeklog admin.

This issue seems to happen with Staticpages and XMLSitemap plugins only. 

Polls, Links, Calendar and Spamx plugin upgrades fine.

I have tested with PHP 5.6 and 7.1 and with different IIS web server versions, all with the same results.

**Comment by eSilverStrike** [comment]
OK a bit of an update

In the installer class the function pluginUpgrades is run to go through all the plugin upgrades. In the function I temporarily added and ORDER BY clause to the sql statement for the plugin load order.

Now the staticpages and xmlsitemap plugin load fine but the last 2 do not so this seems to be an issue with the last 2 plugins being upgraded.

Could this be some sort of memory issue?

Also watch out for the other function in the installer class called upgradePlugins (not pluginUpgrades ). It is virtually the same function except for the name. Not sure why it exists but we will deal with it latere (there are other funcitons as well like autoInstallPlugin, pluginAutoInstall and maybe more...)

**Comment by mystralkk** [comment]
I updated XMLSitemap plugin and plugin version numbers are now updated during the migration.
