### ISSUE TITLE
Installer seems to have some duplicate functions

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#860]
There seems to be duplicate functions in the installer class.

There are functions in the installer class called upgradePlugins and pluginUpgrades ). It is virtually the same function except for the name.  Both are called.

There are other functions as well like autoInstallPlugin and pluginAutoInstall. One is called within the class one is called by another file.

We should check for other functions like these and maybe remove the ones we do not need.

**Comment by mystralkk** [comment]
Fixed with change set 2313dd4.
