### ISSUE TITLE
Add reCaptcha API which plugins can use to show if they support it

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#869]
Add some sort of api that allows plugins to notify the recaptcha plugin what they support.

Currently either no support, V2, and/or invisible.

This may be a little difficult to display in the Geeklog Configuration with the recaptcha "Geeklog Integration" since the config options to enable support would have to be added or deleted dynamically depending on what plugins are installed.

**Comment by mystralkk** [comment]
Implemented with change sets eec2ede and 3849985.  Now, plugins use their plugin_supportsRecaptcha_xxx() callback function to inform the reCAPTCHA plugin.
