### ISSUE TITLE
User Group Form Inherited Group Members List Width

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#870]
If no one is listed in the  Inherited Group Members list it 's width is really small. The width should be the same size as the list above

**Comment by eSilverStrike** [comment]
This only happens with the denim_curve theme. It is because there are some css styles stored in the denim themes custom.css file (when it should be in the style.css file).

I notice that the denim_three theme also has some css in the custom.css file that should be moved over as well.

**Comment by dengenxp** [comment]
Fixed with changeset e5f29cd

**Comment by eSilverStrike** [comment]
Thanks!
