### ISSUE TITLE
Fix warning of count () in php 7.2

### ISSUE THREAD

**Issue by hirorongl** [Geeklog-Core/geeklog#875]
E_WARNING(2) - count(): Parameter must be an array or an object that implements Countable @ system/lib-plugins.php line 869

 `           if (($plg_array !== false) && (count($plg_array) > 0)) {
`
fix line
`            if (($plg_array !== false) && (is_array($plg_array) && count($plg_array) > 0)) {
`

**Comment by eSilverStrike** [comment]
Fixed. Related to #874
