### ISSUE TITLE
[Edit]Rescue in Install does not work

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#878]
From @ivywe 

admin/install/rescue.php does not work. 

/admin/install/rescue.php contains the line

$count = DB_count($_TABLES['vars'], 'name', 'geeklog'); 

Need to update to work with Geeklog 2.2.0 and older versions (or at least say use and older version of resucue on older versions of Geeklog).

**Comment by mystralkk** [comment]
Fixed with changeset dc2a4b2da928de291cb24171ed65a2c69383b216

**Comment by mystralkk** [comment]
The reason Rescue didn't work was not that `vars` table is removed (`vars` table already exists with Geeklog 1.3.8) but that $count variable at line 304
```PHP
        $count = DB_count($_TABLES['vars'], 'name', 'geeklog'); // Check if vars table exists and geeklog version record is found
```
will always return 0 since there is no row with the `name` column being 'geeklog'.

**Comment by eSilverStrike** [comment]
You are right of course. 

I wonder if we should look for the database version instead...

`$count = DB_count($_TABLES['vars'], 'name', 'database_version'); // Check if vars table exists and geeklog version record is found`

**Comment by mystralkk** [comment]
I changed so that we check the numbers of items in $_TABLES['conf_values'] and $_TABLES['vars'] respectively.
