### ISSUE TITLE
Hide Admin URL in Geeklog Var list inserted into header code

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#880]
From Ivy.

Not sure which JavaScript needs this but if we can we should hide the admin url for better security.

var geeklog={ doc:document,win:window,$:function(id){ return this.doc.getElementById(id); },site_url:"https://www.geeklog.net",site_admin_url:"https://www.geeklog.net/admin",layout_url

**Comment by mystralkk** [comment]
Fixed with change set e38ee30
