### ISSUE TITLE
Remove the FCKeditor from Geeklog

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#889]
We currently default to using the CKEditor which is currently being supported.

The FCKeditor is not supported anymore and the last update was over 4 years ago

https://ckeditor.com/blog/FCKeditor-2.6.11-Released/
https://ckeditor.com/blog/?tags=FCKeditor

I believe for security reason we should remove it.

If we remove support we should also have the Geeklog upgrade check if it is in use and then remove it from the site being upgrade configuration as well.

Related to #887 (should remove any directory files in images dealing with the FCKeditor)

**Comment by eSilverStrike** [comment]
Anyone see a reason to keep the FCKEditor? With the last version released 4+ years ago, and I don't know anyone using it, I think it should be removed. @dengenxp @mystralkk @dhaun

**Comment by mystralkk** [comment]
It should be removed for security reasons.

**Comment by eSilverStrike** [comment]
Removed FCKEditor. Added Warning message in Upgrade.

Renamed toolbar id in HTML from "fckeditor_toolbar_selector" to "adveditor_toolbar_selector"

Removed image folder and files for FCKEditor - #887
