### ISSUE TITLE
PHP 7.2 Issues

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#892]
Some PHP 7.2 errors

1)
Wed 12 Sep 2018 15:33:19 EDT -  - E_SYNTAX(0) - Call to undefined function mcrypt_create_iv() @ /home/system/lib-security.php line 1337  
This function was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0. 

2) Happens when you "send ping" for an article
_WARNING(2) - sizeof(): Parameter must be an array or an object that implements Countable @ /home//system/classes/XML/RPC.php line 1724

**Comment by mystralkk** [comment]
Fixed with changeset 1b6b440
