### ISSUE TITLE
Clear Cache function shows error since upgrade to 2.2.0

### ISSUE THREAD

**Issue by jrmain** [Geeklog-Core/geeklog#894]
When I click the `Clear Cache` button in the admin panel, I get this error:
```E_WARNING(2) - Invalid argument supplied for foreach() @ /var/www/jdrgaming/lib-common.php line 6465
Call Stack
#	Function	File	Line
1	COM_cleanDirectory	/var/www/jdrgaming/admin/clearctl.php	74

array(3) {
  ["dir"]=>
  string(48) "/var/www/jdrgaming/images/_thumbs/library/image/"
  ["leave_dirs"]=>
  array(0) {
  }
  ["leave_files"]=>
  array(1) {
    [0]=>
    string(10) "index.html"
  }
}
```
If I recreate the folder `images/_thumbs/library/image`, and recreate `index.html` within that folder, the error does not occur when I click `Clear Cache`, but the file and folder are also removed, so the next time I click `Clear Cache`, I get the error again.

**Comment by eSilverStrike** [comment]
This depends on issue #887 as this directory may not be needed anymore

**Comment by eSilverStrike** [comment]
This directory has now been removed in issue #887 since it wasn't being used anymore. Clear Cache has been updated.
