### ISSUE TITLE
CKEditor - Save toolbar button

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#896]
When editing articles or staticpages (and maybe other things as well) that use the advance editor you can change the tool bar.

The "Full Feature" toolbar has a "Save" button. Pressing this for articles results in a sql error. Pressing this for a staticpage just loads the staticpage list and doesn't save anthing.

If this is not easy to make work properly and actually save the item then we should remove the Save button from the toolbar.

**Comment by mystralkk** [comment]
Removed save button with change set 3efc75a
