### ISSUE TITLE
Saving Article When You have Browsed for an Image that is not allowed

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#897]
Create a new article or edit an existing one. Go to images and Browse for a file that is not an image. Add the appropriate image tag to the article text and then hit Preview

You are shown the article preview and the file is not uploaded (which is good) but no error message is displayed.

If you hit Save instead you get an error message only. The rest of the Geeklog site is not shown.

File Upload Errors - 2018/10/04 11:32AM
Mime type, text/plain, or extension of textfilename.txt not in list of allowed types.

**Comment by mystralkk** [comment]
Fixed with change set 535e41c.
