### ISSUE TITLE
Custommenu does not work 

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#900]
@ivywe reported that custom menu does not work in Geeklog 2.2.

**Comment by ivywe** [comment]
@Tom Custommenu plugin made by @dengenxp

**Comment by eSilverStrike** [comment]
Oh so this does not deal with the custom menu hook for the Geeklog menu bar? 

I did not know @dengenxp  had made a custom menu plugin.

The only menu plugin I know of is https://github.com/Geeklog-Plugins/menu

**Comment by ivywe** [comment]
@Tom,

http://www.trybase.com/~dengen/log/downloads/index.php/12

**Comment by eSilverStrike** [comment]
Good to know. I will add it to the list of possible menu plugins to include to Geeklog if we ever get to improving the Geeklog menu and navbar #701 .
