### ISSUE TITLE
[Bugs] Article editor tab does not work when $_CONF['advanced_editor'] is True.

### ISSUE THREAD

**Issue by Geeklog-jp** [Geeklog-Core/geeklog#905]
Article editor tab does not work when $_CONF['advanced_editor'] is True.
All themes.

**Comment by eSilverStrike** [comment]
The tab works and the advanced editor displays fine for me  and on the demo site as well. What is not working on the tab?

**Comment by Geeklog-jp** [comment]
Sorry it's my mistake.
It works correctly.

**Comment by eSilverStrike** [comment]
No problem :-)
