### ISSUE TITLE
documentation contains 404's

### ISSUE THREAD

**Issue by remyKobolski** [Geeklog-Core/geeklog#909]
Documentation in the tarball refers to images/newlogo.gif. This is only correct when the html is accessed directly. Help functions in the configuration access the html indirectly, resulting 404's.
Copying that image to any directory with 'images' in their name resolves the issue.

Pls. note that this is a very legacy problem. It exists ever.

**Comment by eSilverStrike** [comment]
Changed the docs to reference the image directly to avoid duplicating the logo image.
