### ISSUE TITLE
cache clear: forum contains hidden file

### ISSUE THREAD

**Issue by remyKobolski** [Geeklog-Core/geeklog#910]
See also #894

The official download contains a file .gitignore which is not deleted by clearCache.
Resulting in the error 'directory cache/forum not empty'.

**Comment by eSilverStrike** [comment]
Thanks for your bug report.

If you look at the code, the only .gitignore file we have is in the root and we don't include that in the release package. I double checked and it is not there.

I am not sure how one got in your /data/cache/ directory. 

You downloaded the file named geeklog-2.2.0.tar.gz correct off of Github or the one from here Geeklog.net?

https://www.geeklog.net/downloads/index.php/file_5b324b8ed4c56

**Comment by remyKobolski** [comment]
I downloaded the forum plugin and uploaded that to Geeklog using the upload function.
This is because the tarball does not contain the forum. But alas, you know that.

So I did the process again. It f**cks the cache direcory. See screenshot.

![cachewithforum](https://user-images.githubusercontent.com/31035236/51086592-b1d32600-1748-11e9-8d95-53530f8580ec.png)

Then I pushed the link to clear the cache. Resulting in 
> E_WARNING(2) - rmdir(....snipped..../data//forum): Directory not empty @ ....snipped.../myCobol/lib-common.php line 6492

See screenshot 2.

![cachewithforum](https://user-images.githubusercontent.com/31035236/51086607-c1526f00-1748-11e9-8fb8-64c4b29aa1f9.png)

> I am not sure how one got in your /data/cache/ directory.

But I am.  I double checked by now and it is definitely there.

**Comment by remyKobolski** [comment]
I feel so sorry that I mixed up the cache with the data directory. Above comments clearly refer to the data directory, which contains the directories cache and forum. The latter after uploading the plugin.
I am sure this mixup (on my side) is caused by clearCache, which apparently does much more than clearing the cache. 
And still, the forum-plugin-download contains a hidden directory that troubles.

**Comment by remyKobolski** [comment]
FYI: the plugin forum forum-2.9.2-2.1.2.zip does NOT contain that hidden file .gitignore.
But forum-2.9.3-2.1.3.zip does.

**Comment by eSilverStrike** [comment]
Okay I see the issue. I have updated the forum zip file and removed the .gitignore file. I will have to update the clear cache function to handle hidden files.
