### ISSUE TITLE
download plugin is missing files

### ISSUE THREAD

**Issue by remyKobolski** [Geeklog-Core/geeklog#912]
> Sun Jan 13 17:34:49 2019 - 404 Error generated by 2@84.63.207.0 for URL: http://mycobol.net/downloads/css/default/images/background.gif - Referring URL: http://mycobol.net/downloads/index.php - User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

The url in download.css refers to relative positions. Nevertheless, the graphic cannot be found in absolute positions, like layout/.../css

**Comment by remyKobolski** [comment]
FYI: the image background.gif seems to lack a long time. In the previous version of the download plugin, the css that refers to the url is commented out.

**Comment by eSilverStrike** [comment]
Closing this issue as moving it to proper repository. See https://github.com/Geeklog-Plugins/downloads/issues/12
