### ISSUE TITLE
COM_redirect contains debugging with false information

### ISSUE THREAD

**Issue by remyKobolski** [Geeklog-Core/geeklog#913]
The function COM_redirect logs a false positive with incorrect information:

> Sun Jan 13 22:44:02 2019 - 84.63.207.0 - COM_redirect failed to redirect to "http://mycobol.net/admin/plugins/downloads/index.php?mode=edit".  Headers were already sent at line 0 of "".  

The redirect did not fail and the line number and filename do not have content. The code:

```
    if (isset($_CONF['rootdebug']) && $_CONF['rootdebug']) {
        // for debugging
        COM_errorLog(
            sprintf(
                '%1$s failed to redirect to "%2$s".  Headers were already sent at line %3$d of "%4$s".',
                __FUNCTION__, $url, $line, $file
            )
        );
    }
```

is incorrect and the log is **always** forwarded ) for admin).

**Comment by eSilverStrike** [comment]
@mystralkk We talked about this before in issue #719 and I am not sure why this debugging code is here...

What was the reason behind it always triggering the failed message  when rootdebug is true even when the redirect is successful?

If it is needed should we add another $_CONF['developer_mode_log'] variable for it instead?

**Comment by eSilverStrike** [comment]
Added new $_CONF['developer_mode_log']['redirect'] to siteconfig.php to enable or disable Debug log for Redirects.
