### ISSUE TITLE
Spammers Creating User Accounts using Same Gmail Email Account

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#918]
Not sure if this is worth adding an exception but Gmail allows users to add in as many periods or as little in an email address and treats it as the same email address.

I notice a few spammers have taken advantage of this and we are seeing user accounts created technically using the same gmail email address. For example:

 i.z.a.b.e.la.3.8.e.j.u.s.z.k.iewicz@gmail.com
 izabe.l.a38.e.jusz.k.iew.i.cz@gmail.com

Sending emails to these addresses will both go to the same Gmail Email Account

For more about this issue see: https://stackoverflow.com/questions/14865869/do-all-email-providers-ignore-periods-in-front-of

**Comment by mystralkk** [comment]
Implemented with change set 4e6de4c
