### ISSUE TITLE
[Feature Requests] Create a right user.mass.delete

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#92]
**Reported by hallomarkus on 28 Feb 2007 18:23**

**Description:**
Create a right user.mass.delete

**Additional Information:**
One of the most dangerous things admins can do (also accidentally) is deleting topics and mass deleting users.

There is already a feature request [0000563] topic.delete should be a separate right

I`d like to add this FR to create a right user.mass.delete or similar.

There should also be a config.php variable "onlyrootmassdeletes" similar to "onlyrootfeatures".

It was discussed here: 
http://www.geeklog.net/forum/viewtopic.php?showtopic=74747

[Mantis Bugtracker #191](http://project.geeklog.net/tracking/view.php?id=191)

**Comment by mystralkk** [comment]
**Comment posted by hallomarkus on 9 May 2008 06:46**

geeklog 1

**Comment by eSilverStrike** [comment]
Outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
