### ISSUE TITLE
Geeklog debug level in siteconfig.php

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#920]
// $_CONF['developer_mode_php']['error_reporting'] = -1;

1 is too strict.

// $_CONF['developer_mode_php']['error_reporting'] = 4439;

How about 4439?

**Comment by eSilverStrike** [comment]
What PHP error constants make up 4439?

It may be to strict in some cases but most of the time we use -1 when developing to make sure our code is error free as possible.

I can add some other comment examples in siteconfig.php if you want?

**Comment by eSilverStrike** [comment]
Then leave $_CONF['developer_mode_php']['error_reporting'] commented out and then the default 4439 will be used as set in lib-common. $_CONF['developer_mode_php']['error_reporting'] is not required to be set for developer mode.

**Comment by ivywe** [comment]
thanks!
