### ISSUE TITLE
Rescue.php "Edit Select $_CONF" set database null

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#921]
"Edit Select $_CONF" set conf_var NULL

**Comment by eSilverStrike** [comment]
Which option do you set to NULL?

**Comment by ivywe** [comment]
![rescue](https://user-images.githubusercontent.com/1426188/52289822-1da85780-29b2-11e9-9174-c837e97c07c8.PNG)
all <input> elements are set null.

**Comment by eSilverStrike** [comment]
Hmm it is working for me. 

Is db-config pointing to the correct database?

**Comment by ivywe** [comment]
yes! Enable/Disable Plugins works well.
English language mode "Edit Select $_CONF" is okay!
Please test Japanese mode.

**Comment by eSilverStrike** [comment]
I tried it in Japanese and it works for me. I wonder why it is not working for you... I looked at the code briefly and it should all work especially if enable/disable blocks and plugins work.

Are you using the latest version of rescue.php from the repository or the one from Geeklog 2.2.0? I know @mystralkk made a few fixes a while ago #878 .

**Comment by ivywe** [comment]
I am using the latest version.
PHP version: 7.1.2

sorry, I tried it in English again and it does't works for me.

**Comment by eSilverStrike** [comment]
I was using PHP 7.0. I switched to PHP 7.1 and it worked fine as well for any language.

Try downloading the rescue.php file again. Maybe it got corrupted somehow. I am not sure what is broken on your end. The code should run but yours for some reason is not returning the data from the database. Does yours look like this:
            ```
<form id="config-operator" method="post" action="<?php echo $self . '?view=updateConfigs' . '&amp;lang=' . urlencode($lang); ?>" />
                <?php
                    foreach ($configs as $config) {
                        $sql = "SELECT value FROM {$_TABLES['conf_values']} WHERE name ='{$config}' LIMIT 1";
                        $res = DB_query($sql);
                        $row = DB_fetchArray($res);
                ?>
                        <fieldset><legend><?php echo $config; ?>:</legend><input type="text" size="80" id="<?php echo $config; ?>" name="<?php echo $config; ?>" value="<?php echo unserialize($row['value']); ?>" /></fieldset>
                <?php
                    }
                ?>
                <input type="submit" value="<?php e(41); ?>" onclick="this.disabled=true;this.form.submit();" />
            </form>
```

**Comment by ivywe** [comment]
PHP 7.1.2 -> PHP 7.1.26 updated.
then  the confusion has been cleared up.
thanks.

**Comment by eSilverStrike** [comment]
Ahh, I was using 7.1.26 so that is why I was not seeing the error then. I will close.
