### ISSUE TITLE
The table of the image part of the article editing is longer than container.

### ISSUE THREAD

**Issue by milk54** [Geeklog-Core/geeklog#922]
The table of the image part of the article editing is longer than container, So uk-overflow-auto of class is not written in css of UIkit 2.27.5.
Please write .uk-overflow-auto{overflow: auto; -webkit-overflow-scrolling: touch;} in css file, Or change uk-overflow-auto to uk-overflow-container.

**Comment by eSilverStrike** [comment]
So in the editor template files for articles you want

`
<div class="uk-overflow-auto uk-margin-small">`

changed to

`
<div class="uk-overflow-container uk-margin-small">`

I tried it but couldn't get Firefox to simulate touch controls so I couldn't tell if it was working.

I assume this will also be needed for Denim_three which uses UIKit3?

**Comment by eSilverStrike** [comment]
Thanks
