### ISSUE TITLE
lilb-admin icon min-size is too large

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#925]
all of icon size are 16px.
so, "min-width:32px" is unnecessary.

from:
$LANG_ADMIN[$icon_type], array('style' => 'vertical-align: middle; min-width:32px'));
to:
$LANG_ADMIN[$icon_type], array('style' => 'vertical-align: middle;'));

**Comment by eSilverStrike** [comment]
Do you mean line 333 in the latest code of lib-admin.php?

`$icon_arr[$icon_type] = COM_createImage($icon_url, $LANG_ADMIN[$icon_type], array('style' => 'vertical-align: middle;'));`

It already is set that way.

**Comment by ivywe** [comment]
sorry, I see.
