### ISSUE TITLE
Remove SLV Module in Spam-x Plugin

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#926]
The SLV module uses http://linksleeve.org/ to validate a link as spam. Linksleeve domain has expired.  Since it is not working it should not be removed.

I do not see any point in contacting the maintainers as far as I know the underlying code hasn't been updated for years now.

Plus we added Akismet module which was suppose to be a replacement. Related to #733 

We just need to remove the following files and any reference in the docs. I don't think there are any config options (but we should double check):
/plugins/spamx/SLVwhitelist.Admin.class.php
/plugins/spamx/SLVreport.Action.class.php
/plugins/spamx/SLVbase.class.php
/plugins/spamx/SLV.Examine.class.php

**Comment by eSilverStrike** [comment]
@mystralkk Found some SLV references in the spam-x documents. I removed it from the english and changed up the example  in the Action Modules section. Can you update the Japanese docs and then close this issue?

**Comment by mystralkk** [comment]
Thanks.  Done.
