### ISSUE TITLE
XML Sitemap exclude registrations with regular expressions of ID

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#927]
I want to exclude registrations with regular expressions.
`^[_] ^[-] 404` 

example
Staticpage 404 ,  _**** -***  ... I want to exclude.

**Comment by eSilverStrike** [comment]
I am not sure I understand what you mean by registrations?

**Comment by eSilverStrike** [comment]
I plan on closing this issue soon unless more info is provided.
