### ISSUE TITLE
[Feature Requests] email notifications should be routable to various admins

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#93]
**Reported by hallomarkus on 28 Feb 2007 18:32**

**Description:**
email notifications should be routable to various admins

**Additional Information:**
Email notifications should be routable to various admins. Especially with large sites a user manager may want to handle user registrations only.

Up to now the config.php reads:

``` PHP
// Send an email notification when a new submission has been made. The contents
// of the array can be any combination of 'story', 'comment', 'trackback',
// 'pingback', and 'user'.
// Example: $_CONF['notification'] = array ('story', 'comment');
// The email will be sent to $_CONF['site_mail'] (see above).
$_CONF['notification'] = array ('story', 'comment','trackback', 'pingback', 'event', 'user');
```

It would be better if one could chose like:

Send an email notification when a new submission has been made to = array ('Story Admin', 'Root')

Send an email notification when a new user registered to = array ('User Admin', 'Story Admin')

...and so on...

It was discussed here: 
http://www.geeklog.net/forum/viewtopic.php?showtopic=74747

[Mantis Bugtracker #192](http://project.geeklog.net/tracking/view.php?id=192)

**Comment by mystralkk** [comment]
**Comment posted by hallomarkus on 9 May 2008 06:44**

geeklog 1

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
