### ISSUE TITLE
Improve Install UTF-8 Option

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#936]
Should we default Geeklog Installs to UTF-8? Right now it does not. It defaults to Latin-1 (iso-8859-1)

UTF-8 is needed for emojis and multi language sites.

We should better explain what the default is and the differences between the 2 character sets as most users will not know.

**Comment by mystralkk** [comment]
Additionally, all languages files should only be in UTF-8.  It's a pain to maintain a language file in two charsets, such as ISO-8859-2 and UTF-8.

**Comment by eSilverStrike** [comment]
I agree it is a pain. I assumed this was done way back to support databases set at a certain current character set/collation and the web servers as well. Would changing this affect things now?

I would think most new website would use utf8mb4 now for databases to support emoticons.

I also think we should drop some language files as they have not been maintained in a long time.

**Comment by mystralkk** [comment]
I would suggest all charsets in Geeklog be UTF-8 and UTF-8 option on installation be deleted.  Other character sets will be silently converted to UTF-8 when updating their sites.

**Comment by eSilverStrike** [comment]
So their DB would be converted then? The config option default_charset is also used for "Character encoding used by Geeklog when serving HTML pages or sending email" so we wouldn't want characters being saved by Geeklog forms into databases that support for example just latin

**Comment by mystralkk** [comment]
On second thought, converting DB into UTF-8 by Geeklog might cause trouble.  So, as you suggested, it would be much better to default to UTF-8 only with fresh install.

**Comment by eSilverStrike** [comment]
@mystralkk While testing #1025 I notice that on new installs **unchecking** the UTF-8 option doesn't keep the old charset settings.  In site config this:

$_CONF['default_charset'] = 'iso-8859-1';

gets changed to

$_CONF['default_charset'] = 'utf-8';

and in dbconfig this remains:

$_DB_charset = '';

This kind of relates to my #1025 issue... with the $_DB_charset and the problems I had upgrading with the different table collations.

Something is messed up with the logic and the $_DB_charset should get automatically set to something.... and written to the dbconfig? Or is the user supposed to update it manually? (if so I should put this in the docs and have it commented in the dbconfig file

I assume the $_DB_charset should start off as 'latin1' in dbconfig.php.dist since $_CONF['default_charset'] = 'iso-8859-1' in siteconfig.php.dist

I've confused myself a bit on this but I think we should get the basics of it working for Geeklog v2.2.1 and then rework it better later in Geeklog v2.2.2

**Comment by eSilverStrike** [comment]
Number of recent commits for #1025 apply to this issue as well.

**Comment by eSilverStrike** [comment]
@mystralkk (thinking next version of Geeklog only) - All these character sets are sure a pain! 

Just thinking, can we run the site default charset as UTF-8 (therefor all the languages, etc) and still keep the websites existing database collation as what ever it is set as? Is it backwards compatible like that?

For new installs we can then require MySQL to use utf8mb4 (the true UTF-8 character set) which supports all languages right?

I see that for MySQL 8 "From MySQL 8.0, utf8mb4 is the default character set, and the default collation for utf8mb4 is utf8mb4_0900_ai_ci." not sure what the difference is in that collation.

https://mysqlserverteam.com/mysql-8-0-collations-migrating-from-older-collations/

**Comment by mystralkk** [comment]
@eSilverStrike wrote:
> Just thinking, can we run the site default charset as UTF-8 (therefor all the languages, etc) and still keep the websites existing database collation as what ever it is set as? Is it backwards compatible like that?

I don't think so.  If the charset for database is, say, latin1, we cannot save UTF-8 data without losing any part of them.

> For new installs we can then require MySQL to use utf8mb4 (the true UTF-8 character set) which supports all languages right?

We can require this since it seems that current MySQL servers all support utf8mb4 charsets.

>I see that for MySQL 8 "From MySQL 8.0, utf8mb4 is the default character set, and the default collation for utf8mb4 is utf8mb4_0900_ai_ci." not sure what the difference is in that collation.

I understand utf8mb4_0900_ai_ci is like utf8mb4_general_ci.  "ai" stands for "accent insensitive" so it doesn't distinguish 'a' from 'á'.

**Comment by eSilverStrike** [comment]
>> I don't think so. If the charset for database is, say, latin1, we cannot save UTF-8 data without losing any part of them.

Right, I was thinking more of a conversion between the 2 but thinking it through more I see the problems. We could convert some characters but language ones like for example the Chiniese Language would be impossible.

**Comment by eSilverStrike** [comment]
Based on issue #1025 we have done a lot of updates to the install to better detect character sets and updated the help in the install and docs to better explain language character sets, database character sets, and database collation for MySQL and PostgreSQL.

When we drop support for some languages (#975) we should also look at converting some the languages to UTF-8 and maybe default the install to UTF-8 and move away from these legacy collations and character sets (can't do this for upgrades). Obviously we will still have to support the older character sets since many older Geeklog installs may still use them.

**Comment by mystralkk** [comment]
It is possible to make everything UTF-8 for fresh install, so I would remove UTF-8 option.  Of course, we have to keep other charsets for upgrading.

Thus, making all language files UTF-8 will cause trouble for those using legacy charsets other than latin1 when upgrading from older versions.  For example, when Russian users using a legacy charset (Windows-1251) upgrade to Geeklog 2.2.2, they will have to use "russian_utf-8.php" as their language file.  Probably, their database was created with either of CP1250, CP1251, and KOI8-U charsets, which makes it hard to save UTF-8 data.

**Comment by mystralkk** [comment]
Removed 'UTF-8 Option' for fresh install.

**Comment by eSilverStrike** [comment]
Hmmm. Also what happens to an upgrade that the language is not supported anymore since we removed it? Does it just default back to english? We should maybe have a warning message for admins explaining what happen (using COM_setSystemMessage) for this if the install cannot detect it before the update.

I think a minimum Geeklog version number for languages was also mentioned in an issue. Should this be implemented so for example if an admin uses a specific language he will be notified it is not fully updated to the current version of Geeklog (like with themes). We could also mention in the message if they choose to update it they can submit the language file to Geeklog.net increasing the chances of getting some of these language files updated by the community.

**Comment by mystralkk** [comment]
> Hmmm. Also what happens to an upgrade that the language is not supported anymore since we removed it? Does it just default back to english? We should maybe have a warning message for admins explaining what happen (using COM_setSystemMessage) for this if the install cannot detect it before the update.

I changed the installer to show a warning after upgrade or migration when the language the user was using is no longer supported.

> I think a minimum Geeklog version number for languages was also mentioned in an issue. Should this be implemented so for example if an admin uses a specific language he will be notified it is not fully updated to the current version of Geeklog (like with themes).

In my opinion, a minimum Geeklog version number for languages is hard to control and hardly worth the effort.

Suppose the minimum Geeklog version number for languages (Geeklog 2.2.2) is '2.2.2'.  Someone posted a language file, say, translated into Dutch, but not all the entries in the file are translated.  How should we give a version number to this file?  Then, the user improved the translation and posted it.   What should be the version number?

**Comment by eSilverStrike** [comment]
Minimum Geeklog version number would stay the same until all variables are up to date. I guess an actual version number of the language file would have to be created to avoid the confusion you mentioned.

As you said probably not worth the effort though it would be nice if we got some more language submissions from those that update their files.  Maybe a message about how to do this in the comment at the top of each language files.
