### ISSUE TITLE
Home Page returns 404 Error if URL Routing Enabled and Site URL has a Directory in it

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#937]
Home Page returns 404 Error if URL Routing enabled and Site URL has a Directory in it.

For example if site_url = http://www.domain.com/_sub

If site_url does not have a directory it then works fine.

**Comment by eSilverStrike** [comment]
@mystralkk – I spent a couple of hours on this and kept running into problems. Can you take a look at it?

Here is what I found so far for URL Rewrite, URL Routing with index.php, and URL Routing without index.php.

For viewing the homepage (and page 2, etc..) and the topics (and their page 2, etc…)  this works fine if the site url does NOT have a directory in it (http://www.example.com/).

If it does (http://www.example.com/_sub), things start to break down as it assumes the directory in the site url is actually a variable name for when URL Routing is enabled.

When Routing is enabled the Router class gets fired which means the URL class gets run twice if a route is found. Once before the router class and then again when the router class does its thing to return the original url.

I think the problem resides in the url class getArguments function as it needs to take into account if the site url has a directory in it which must be stripped first before the arguments are gathered.

So the whole issue happens in public_html/index.php around line 117 when COM_setArgNames is called. (when url rewrite and url routing are both enabled)

The other thing that needs to be fixed in the URL Class is when the numArguments function does not return the correct value when URL Routing is enabled. Since the URL class gets run twice thanks to the router class the second time around (when the url is converted to a normal one) no arguments are found. This function needs to be able to count the number of variables when url routing is enabled. I wasn’t sure the best way to do this….

**Comment by eSilverStrike** [comment]
## Test Current Fix

@mystralkk  - Okay I spent another few hours and I got it working for the homepage. In the url class getArguments function I setup a check which will remove the directories as needed. This has been tested on IIS. Can you test on Apache?

This is how I tested. The following is tested with directory in site_url and NOT, for URL Rewrite (with no routing), and then routing enabled with index.php and without. This means you have to test the following pages below 6 different times making sure you change the htaccess as needed and clearing the Geeklog cache.

-	home page
-	home page (second page)
-	Topic A
-	Topic A (second page)
-	Some staticpage

## numArguments Issue

The issue of numArguments in the URL Class does not work for Routing (it works for URL rewrite) and is still a problem. I am not sure how to fix this…. Part of the issue is because the Routing loads the page twice...

## Routing Causes Page to Load Twice

I also found another Routing issue which I am not sure how to fix. This needs to be looked at well. With routing enabled most times (at least on IIS) Geeklog ends up loading the page twice (meaning lib-common.php loads twice, etc creating longer page load times and increases the use of resources).  It first loads the page based on the url, for  example:

http://www.example.com/index.php/topic/Geeklog/2

When the Routing dispatch function is called it then finds the route

Thu Jun 20 11:39:42 2019 -  - Router::dispatch: "/topic/Geeklog/2" matched with regular expression rule "/topic/@topic/@page", converted into "http://www.example.com/index.php?topic=Geeklog&page=2"  

And then reloads the page. Can’t we use the info from the route to get the arguments instead of reloading the whole page? Is this something we can fix?

**Comment by mystralkk** [comment]
I tested your Current Fix and found it works well.  Thank you for fixing this.

As for "Routing Causes Page to Load Twice," I don't think this can be helped.  Since Geeklog doesn't have a true front controller, it has to load, say, "http://www.example.com/index.php?topic=Geeklog&page=2" in order to **get the actual content** corresponding to "http://www.example.com/index.php/topic/Geeklog/2," not just to get the arguments.   

I am not sure if I understand "numArguments Issue", but if loading the URL class twice causes the issue, making the class singleton might solve it.

**Comment by eSilverStrike** [comment]
The title of this issue is fixed. Moved other issues found to separate issue #945
