### ISSUE TITLE
Staticpage denim_three theme: cachetime input area is too small

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#943]
cache_time input area is too small in denim_three/admin/ templates.

from:
 `<dd><input type="text" value="{cache_time}" name="cache_time" id="sp-advanced_editor-cachetime" class="uk-input uk-form-width-xsmall"{xhtml}></dd>
`
to:
` <dd><input type="text" value="{cache_time}" name="cache_time" id="sp-advanced_editor-cachetime" class="uk-input uk-form-width-small"{xhtml}></dd>`

**Comment by eSilverStrike** [comment]
Double check Articles and Blocks cache time as well for Denim3 theme.
