### ISSUE TITLE
I added ini_set('opcache.enable', 0); in opcache.enable.php/public function load_baseconfig()

### ISSUE THREAD

**Issue by P2Tera** [Geeklog-Core/geeklog#951]
my server is opcache.enable=1.
when fullinnstall with change db_prefix,
extra plugins's db_prefix is nochange.
so, I added ini_set('opcache.enable', 0); in opcache.enable.php/public function load_baseconfig()

**Comment by mystralkk** [comment]
Fixed with change set 0ac32ab.  This was a bug of the installer.  You can now restore the setting for opcache.enable.
