### ISSUE TITLE
CUSTOM_userCreate() is called twice

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#952]
From forum post: https://www.geeklog.net/forum/viewtopic.php?showtopic=97085 by OMAL

I use CUSTOM_userCreate() to add additional data to an additional table when admin creates an user.
But I got the fatal error of "Duplicate entry for key 'PRIMARY' to the table" when I create an user.

USER_createAccount() in lib-user.php has the following lines and that causes the error.
PHP Formatted Code
```
    // call custom registration function and plugins
    if ($_CONF['custom_registration'] && function_exists('CUSTOM_userCreate')) {
        CUSTOM_userCreate($uid, $batchImport);
    }
    PLG_createUser($uid);
```

CUSTOM_userCreate function is called here, and again in the PLG_createUser function.

**Comment by mystralkk** [comment]
Fixed with change set a5b2754
