### ISSUE TITLE
Generate User Image/Icon from Username using PHP Dynamically

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#954]
I find most users don't include a user photo so it would be nice if we had a setting which Admins could enable that generates a photo if the user doesn't upload one when a new account is created. It would be based on their initials and the background would be colored accordingly (and maybe even the letter colored).

This example here uses the PHP GD Libraries

https://phppot.com/php/how-to-generate-initial-avatar-image-from-username-using-php-dynamically/

```
function createAvatarImage($string)
{
 
    $imageFilePath = "images/".$string . ".png";

    //base avatar image that we use to center our text string on top of it.
    $avatar = imagecreatetruecolor(60,60);
    $bg_color = imagecolorallocate($avatar, 211, 211, 211);
    imagefill($avatar,0,0,$bg_color);
    $avatar_text_color = imagecolorallocate($avatar, 0, 0, 0);
	// Load the gd font and write 
    $font = imageloadfont('gd-files/gd-font.gdf');
    imagestring($avatar, $font, 10, 10, $string, $avatar_text_color);
    imagepng($avatar, $imageFilePath);
    imagedestroy($avatar);
 
    return $imageFilePath;
}
```

Here is some other examples that might be even better:

https://www.w3schools.in/php-script/create-text-pictures-with-phptext-class/

https://github.com/laravolt/avatar

**Do it with CSS instead?**

Now that I think about it, doing it with CSS might be better (have a config setting as well). 

https://stackoverflow.com/questions/34310271/css-place-in-circle-first-letter-of-the-name

https://blog.nodebb.org/goodbye-gravatar-hello-user-icons/

Doing it with CSS is a cleaner solution that allows for changes later but we need to make sure this works with plugins like the forum so the Geeklog function USER_getPhoto will need to be updated

**Comment by mystralkk** [comment]
I visited https://stackoverflow.com/questions/34310271/css-place-in-circle-first-letter-of-the-name and tried implementing this feature with change set 5b2f9ed.

<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/2015377/63645656-2b4ee000-c73e-11e9-9c89-815bcc7b3a06.png">

**Comment by eSilverStrike** [comment]
Note: We may have to update some plugins (like the forum which I am doing) to support this feature better. For example the forum does some checks of config options, etc... it self before using the function USER_getPhoto (this function also now does these checks). These type of checks plugins may do can interfere with displaying the user generated icons if enabled.

**Comment by eSilverStrike** [comment]
Just a note about the User Generated icons. Since they use CSS where as an actual user photo is an image, the2 behave and scale differently depending on how they are contained within other html.

This created a bit of a problem with the forum responsive layout which the above changes fixed (for the most part) and hopefully this still work gracefully in other areas where the user photo/icon is displayed.

In the new basic theme I plan to make (#854) I plan to show the user photo/icon in comments so this will be a further test if the fix above works. If not I will readdress it at that point.

**Comment by eSilverStrike** [comment]
@mystralkk - I initially thought the choice to use span was the best option since it requires the least amount of processing power but I have since run into issues with trying to make the span behave like an actual user image on a html page. This is especially problematic when dealing with responsive layouts.

I thought I had possibly fixed the issue enough with a later commit but that is not the case when I went a head and updated one of the themes to use a userphoto in comments.

I’ve spent the last few hours looking into the issue and have determined that we need to use an img tag as no amount of css trickier allows us to get a span or a div to be treated the same as an img tag.

So I found a solution that allows us to still use most of our code.

https://ui-avatars.com/

They have an api which will auto generate our images. They have over 28 million daily requests with an average processing time of 2.8 ms and been online since 2017. So I don’t think they are going anywhere soon…

UI Avatars has a simple-to-use API with no limiting or login. No usage tracking and no information is stored. The final images are cached, but nothing else. Here is an example:

https://ui-avatars.com/api/?name=TT&color=FFFFFF&background=784DD1&size=128


They also have their php libraries on Github

https://github.com/LasseRafn/ui-avatars
https://github.com/LasseRafn/php-initial-avatar-generator

Which if we wanted we could include and create our own auto generator within Geeklog instead of using their website api. For example by using the library above and this page:

https://github.com/LasseRafn/ui-avatars/blob/master/api/index.php

by adding it to a php file which we would then refer directly to as the source for our user generated images. The problem with this is we would obviously have to

-	Include the libraries
-	Handle the cache image files created
-	Only supports PHP 7+

So what do you think @mystralkk ? I would like to go ahead and add the support for using ui-avatars.com for generating our user icons. If it ever goes down, at that point we could use something else or include their libraries and do the generation locally.

**Comment by mystralkk** [comment]
As you suggest, it would be best to use https://ui-avatars.com/ as an external service.

**Comment by eSilverStrike** [comment]
The last commit updated the following:

- Updated automated generated user avatars to use ui-avatar.com api
- Update Denim and Denim Three theme comments to show user photos
- Fixed a bug where comment signatures could repeat on the next post
- Renamed theme_getCSSClasses_foo to theme_getThemeItem_foo to better reflect what it does
- Renamed PLG_getCSSClasses to PLG_getThemeItem to better reflect what it does
- Updated locations used by PLG_getThemeItem  to better reflect what they need
- Fixed function naming mistakes in all themes except denim 9as it was correct)

**Comment by Subset-spasm31** [comment]
I think this https://phps.space/questions/create-custom-color-schemes-using-letters-in-php could really help you out
