### ISSUE TITLE
Banned Users still have clickable author names in Comments, Articles etc..

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#964]
Users who are banned by admins that still have content visible on the site (like comments, articles, staticpage, forum posts, etc..), the author names are still clickable and give no indication they have been banned. When users click on the banned author/user name they will get an access denied message (admins do not).

We should strike through the author name of banned users and for those who do not have access to their user page we should not include a link.

Maybe we can update the function COM_getDisplayName (or create another function) to take all this into account and then update the core plugins and forum to use the new function so everything is consistent.

**Comment by mystralkk** [comment]
Fixed with change set f09206e.

**Comment by eSilverStrike** [comment]
Looks good. Implemented it in the forum plugin as well.
