### ISSUE TITLE
Invisible Captcha Issue - No Fail Message and not recorded in log

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#965]
After a user complained he could not add a comment I looked into it and tried submitting a comment as an anonymous user.

I had these issues with the invisible recaptcha on Geeklog.net when adding a comment as an anonymous user for an article (comment form is displayed with the article. Not sure if it is an issue for other things that use the invisible recaptcha. I have since switched the comment form to V2 recaptcha until this issue gets resolved.

When hitting submit the form would just refreshed. No error message is displayed helping explain to the user what is the problem. I would think we should be able to catch the error hopefully like with V2 recaptcha.

Also invisible recaptcha failures are not recorded in the recaptcha log.

**Comment by mystralkk** [comment]
Fixed the rest with change set 864c820.

**Comment by eSilverStrike** [comment]
@mystralkk Can you take a look at the forum invisible recaptcha issue if you have time?

https://github.com/Geeklog-Plugins/forum/issues/56

I tried before last year and couldn't get it to work. I haven't looked at it again this year yet but would like it working as when I update Geeklog.net with Geeklog v2.2.1 I will most likely have to update the forum plugin on Geeklog.net with the yet unreleased version  so recaptcha works (as there are a number of other forum bugs that I need to fix before an actual release).

Can you also see if the failed recaptcha message on forum topic posts are returned correctly like with #863

**Comment by eSilverStrike** [comment]
So on Geeklog.net I tried the forum with invisible captcha and the lost password and they worked fine when the invisible recaptcha gets triggered. 

I tried the comments for article and polls (I didn't try the others) and the invisible recaptcha displays and when I successfully complete it the page refreshes and says I need to input my name and comment (I had already entered it before the invisible recaptcha was triggered). V2 recaptcha works fine for comments.

@mystralkk I left Geeklog.net with invisible reCAPTCHA enabled for comments so you can test it out and see.

**Comment by eSilverStrike** [comment]
@mystralkk- Okay I did a bit more testing and invisible captcha works if you preview your comment first and then submit it.

If you don't preview it and just submit it the invisible captcha comes up fine but once you complete the captcha Geeklog gives you the error:

> Please fill in the Title and Comment fields, as they are necessary for your submission of a comment.

and shows you the empty comment form. Some how it looses the text you submited.

**Comment by eSilverStrike** [comment]
Another issue that is a real pain to test :-)

Okay I figured out why the issue is happening. The issue only happens when the advanced editor is used and the textarea is "comment_html" and not "comment". On the form submit in the form tag for the comment the javascript function:

`set_postcontent();`

is supposed to run when the advanced editor is used. This function doesn't get triggered by the invisible recaptcha call back.

With my commit b8ddf94 and bfa0e9b I fixed this. I added a new plugin info variable called “js_onsubmit” and “js_onsubmit_advanced_editor”  which plugins can set which will only be used for invisible captcha. This way for example the forum doesn’t need to set anything it doesn’t have to. I think these are the only 2 situations we have to worry about for plugins needing to set javascript possibly??? What do you thing @mystralkk ?

When testing this stuff you need to take several situations in account. 

-	The comment form requires javascript so it is disabled if javascript is not set so we don’t have to worry about that.
-	 “skip_preview in posts”
-	Advanced Editor enabled or not
-	Comment on Same Page? 

How does my commits look? Is their a better way to do this where we can take into account the need for a plugin to insert javascript on a submit or not or do you think what I have committed will be fine?

**Comment by mystralkk** [comment]
Look nice to me.  I couldn't figure out why this issue happened.
