### ISSUE TITLE
Links in Configuration Tooltips Descriptions do not function

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#966]
The links in the configuration tooltips descriptions that popup for the Geeklog Configuration items do not work (internal and external links). They only work if you are viewing the config doc page directly. 

Maybe when it is a tooltip and the user clicks on a link in the tooltip we can open the full page like what happens if they click on the variable name of config option in the tooltip.

**Comment by mystralkk** [comment]
Fixed with change set 7a66710.

**Comment by eSilverStrike** [comment]
In the tooltip descriptions it looks to be fixed for external links and some of the internal ones (like the Enable URL Rewrite tooltip). The Enable URL Routing tooltip still has an issue for some reason in the description for the URL their.

**Comment by mystralkk** [comment]
I can't reproduce the issue you mentioned in English or Japanese docs.

**Comment by eSilverStrike** [comment]
Sorry.

Just tried it again in MS Edge and it works. Looks like it only doesn't work in Firefox Developer when the development tools are open. This is the second time I have had an issue with javascript and Firefox Developer.  I will remember next time to triple check things.
