### ISSUE TITLE
Renaming theme_xxx_[themeName] functions

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#969]
I suggest renaming theme_xxx_[themeName] functions in "layout/[themeName]/functions.php" to just theme_xxx.  Since no two "functions.php" files will be loaded at the same time, function names don't have to have its theme name as a suffix.  Besides, in so doing, it will be much easier to make a child theme.  Any thoughts?

**Comment by eSilverStrike** [comment]
Makes sense and your right that it is a pain when doing a child theme. Surprised I didn't think of it.

The only possible future issue I see is Dengen's #845 feature of creating a separate Admin theme. Still for admin theme functions we can just have new function names like theme_admin_xxx 

I haven't heard from @dengenxp in a while so I am not sure if he is still planning to do the feature.

**Comment by mystralkk** [comment]
Changed with change set 9d45d69.  Now theme API no longer requires theme name as a suffix.  However, for backward compatibility, function names like "theme_js_[ThemeName]" are still valid.
