### ISSUE TITLE
lib-plugins.php bug: Autotag plugin, PHP mode and requires close tag mode, autotag does not works.

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#973]
Autotag plugin, PHP mode and requires close tag mode, autotag does not works.

//fix by hiroron 2019/09/24

lib-plugins.php line: 1674
from:
```
    //See if any tags require close tags
    $tags_requireclose = array_flip(PLG_collectTags('closetag'));

```
to:
```
    //See if any tags require close tags
    $tags_requireclose = array();
    $collectclosetags = PLG_collectTags('closetag');
    $i = 0;
    foreach ($collectclosetags as $key => $val) {
        $tags_requireclose[$i] = $key;
        $i++;
    }
```

**Comment by eSilverStrike** [comment]
Thanks. I could have sworn this was working before but I checked my autotags testing page and it wasn't allowing autotags with closed tags to be in another autotag with a closed tag.

Ivy can you give me an example of your autotag with the php code so I can add it to my tests?

In the autotags editor you have checked:
Requires Close Tag
Replace with PHP?

and what is the content you have in the "Replace With"?

Thanks

**Comment by ivywe** [comment]
example 
https://github.com/ivywe/geeklog-ivywe/blob/Geeklog2.2/extended/system/custom/phpautotags_l.php

[l:en]English words[/l][j:ja]日本語をここに記述[/l]
