### ISSUE TITLE
Spam-X personal blacklist regexp 

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#974]
As report by @dhaun 

> I tried adding:
> 
> fifa.20
> 
> to the Spam-X personal blacklist. That should be treated as a regexp and should have caught "Fifa 20" and the like. But it didn't.
> 
> Has anything changed in that Spam-X module that I missed?
> 

Should confirm this change (sounds like a bug to me) and if it affects any other SPAM-X modules.

**Comment by mystralkk** [comment]
Fixed with change set 69efe57.
