### ISSUE TITLE
Drop Support for Some Languages

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#975]
Some of the language files have not been translated and updated in a long time. They contain a lot of English language text.

Some language files even seem to be corrupted at some point and no one noticed like the file ukrainian_koi8-u.php for Geeklog and the Staticpages Plugin.

I think we should have a discussion about removing all language files we know are not really being used anymore?

This would include language files for the Geeklog CMS, The Core Plugins, and the Install.

I think we should keep.

English
Japanese
French
German
Hebrew

Are there any other languages we should keep? 

Is this something we should do or not?

**Comment by mystralkk** [comment]
Which language does OMAL (who often posted on geeklog.net recently)  and their users use?

**Comment by eSilverStrike** [comment]
I reached out to him to find out. I guess the best thing to do would be to add an article about this and maybe a poll to figure out what languages people use and which ones we should keep. (by asking them to post in the comment section)

**Comment by mystralkk** [comment]
That would be nice.

**Comment by eSilverStrike** [comment]
By the way OMAL uses Japanese.

**Comment by mystralkk** [comment]
I didn't know that.

**Comment by eSilverStrike** [comment]
Just added this to the 2.2.1 milestone so I remember to add a article and poll about this issue. Once I do that I will move this issue to a later version

**Comment by mystralkk** [comment]
I wrote a simple script to check how much each language file is translated.  Though in some entries translation might not be necessary, the results are below:

## The rates of Core language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>afrikaans_utf-8.php</td><td>44.2</td></tr><tr><td>bosnian_utf-8.php</td><td>30.4</td></tr><tr><td>bulgarian_utf-8.php</td><td>24.4</td></tr><tr><td>catalan_utf-8.php</td><td>34.5</td></tr><tr><td>chinese_simplified_utf-8.php</td><td>58.3</td></tr><tr><td>chinese_traditional_utf-8.php</td><td>58.3</td></tr><tr><td>croatian_utf-8.php</td><td>24.2</td></tr><tr><td>czech_utf-8.php</td><td>28.7</td></tr><tr><td>danish_utf-8.php</td><td>28.6</td></tr><tr><td>dutch_utf-8.php</td><td>44.5</td></tr><tr><td>estonian_utf-8.php</td><td>66.6</td></tr><tr><td>farsi_utf-8.php</td><td>34.9</td></tr><tr><td>finnish_utf-8.php</td><td>33.8</td></tr><tr><td>french_canada_utf-8.php</td><td>31.1</td></tr><tr><td>french_france_utf-8.php</td><td>65.3</td></tr><tr><td>german_formal_utf-8.php</td><td>66.2</td></tr><tr><td>german_utf-8.php</td><td>66.2</td></tr><tr><td>hebrew_utf-8.php</td><td>74.4</td></tr><tr><td>hellenic_utf-8.php</td><td>34.9</td></tr><tr><td>indonesian_utf-8.php</td><td>31.3</td></tr><tr><td>italian_utf-8.php</td><td>64.8</td></tr><tr><td>japanese_utf-8.php</td><td>92.7</td></tr><tr><td>korean_utf-8.php</td><td>47.0</td></tr><tr><td>norwegian_utf-8.php</td><td>31.1</td></tr><tr><td>polish_utf-8.php</td><td>45.2</td></tr><tr><td>portuguese_brazil_utf-8.php</td><td>34.3</td></tr><tr><td>portuguese_utf-8.php</td><td>29.4</td></tr><tr><td>romanian_utf-8.php</td><td>24.2</td></tr><tr><td>russian_utf-8.php</td><td>39.5</td></tr><tr><td>serbian_utf-8.php</td><td>58.7</td></tr><tr><td>slovak_utf-8.php</td><td>24.7</td></tr><tr><td>slovenian_utf-8.php</td><td>61.4</td></tr><tr><td>spanish_argentina_utf-8.php</td><td>29.5</td></tr><tr><td>spanish_utf-8.php</td><td>46.7</td></tr><tr><td>swedish_utf-8.php</td><td>34.1</td></tr><tr><td>turkish_utf-8.php</td><td>43.8</td></tr><tr><td>ukrainian_utf-8.php</td><td>47.4</td></tr></table>

## The rates of calendar language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>czech_utf-8.php</td><td>59.1</td></tr><tr><td>danish_utf-8.php</td><td>58.6</td></tr><tr><td>dutch_utf-8.php</td><td>59.1</td></tr><tr><td>estonian_utf-8.php</td><td>82.2</td></tr><tr><td>french_canada_utf-8.php</td><td>54.8</td></tr><tr><td>french_france_utf-8.php</td><td>82.7</td></tr><tr><td>german_formal_utf-8.php</td><td>81.7</td></tr><tr><td>german_utf-8.php</td><td>81.7</td></tr><tr><td>hebrew_utf-8.php</td><td>95.6</td></tr><tr><td>italian_utf-8.php</td><td>81.7</td></tr><tr><td>japanese_utf-8.php</td><td>96.2</td></tr><tr><td>korean_utf-8.php</td><td>60.7</td></tr><tr><td>russian_utf-8.php</td><td>60.7</td></tr><tr><td>slovak_utf-8.php</td><td>59.6</td></tr><tr><td>slovenian_utf-8.php</td><td>82.7</td></tr><tr><td>spanish_utf-8.php</td><td>59.6</td></tr><tr><td>ukrainian_utf-8.php</td><td>60.7</td></tr></table>

## The rates of links language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>chinese_simplified_utf-8.php</td><td>25.7</td></tr><tr><td>chinese_traditional_utf-8.php</td><td>25.7</td></tr><tr><td>czech_utf-8.php</td><td>25.2</td></tr><tr><td>dutch_utf-8.php</td><td>20.1</td></tr><tr><td>estonian_utf-8.php</td><td>89.6</td></tr><tr><td>french_canada_utf-8.php</td><td>15.9</td></tr><tr><td>french_france_utf-8.php</td><td>65.9</td></tr><tr><td>german_formal_utf-8.php</td><td>72.6</td></tr><tr><td>german_utf-8.php</td><td>72.6</td></tr><tr><td>hebrew_utf-8.php</td><td>97.4</td></tr><tr><td>italian_utf-8.php</td><td>88.6</td></tr><tr><td>japanese_utf-8.php</td><td>97.4</td></tr><tr><td>korean_utf-8.php</td><td>25.2</td></tr><tr><td>polish_utf-8.php</td><td>24.7</td></tr><tr><td>russian_utf-8.php</td><td>25.2</td></tr><tr><td>slovenian_utf-8.php</td><td>90.7</td></tr><tr><td>spanish_utf-8.php</td><td>24.2</td></tr><tr><td>ukrainian_utf-8.php</td><td>25.2</td></tr></table>

## The rates of polls language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>chinese_simplified_utf-8.php</td><td>11.4</td></tr><tr><td>chinese_traditional_utf-8.php</td><td>12.1</td></tr><tr><td>dutch_utf-8.php</td><td>10.7</td></tr><tr><td>estonian_utf-8.php</td><td>67.8</td></tr><tr><td>french_canada_utf-8.php</td><td>9.2</td></tr><tr><td>french_france_utf-8.php</td><td>76.4</td></tr><tr><td>german_formal_utf-8.php</td><td>75.0</td></tr><tr><td>german_utf-8.php</td><td>75.0</td></tr><tr><td>hebrew_utf-8.php</td><td>96.4</td></tr><tr><td>italian_utf-8.php</td><td>77.1</td></tr><tr><td>japanese_utf-8.php</td><td>97.8</td></tr><tr><td>korean_utf-8.php</td><td>11.4</td></tr><tr><td>russian_utf-8.php</td><td>11.4</td></tr><tr><td>slovenian_utf-8.php</td><td>77.1</td></tr><tr><td>spanish_utf-8.php</td><td>12.1</td></tr><tr><td>ukrainian_utf-8.php</td><td>12.1</td></tr></table>

## The rates of recaptcha language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>french_france_utf-8.php</td><td>3.3</td></tr><tr><td>japanese_utf-8.php</td><td>70.0</td></tr></table>

## The rates of spamx language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>dutch_utf-8.php</td><td>77.4</td></tr><tr><td>estonian_utf-8.php</td><td>69.5</td></tr><tr><td>farsi_utf-8.php</td><td>5.9</td></tr><tr><td>french_canada_utf-8.php</td><td>60.9</td></tr><tr><td>french_france_utf-8.php</td><td>62.2</td></tr><tr><td>hebrew_utf-8.php</td><td>88.7</td></tr><tr><td>italian_utf-8.php</td><td>75.4</td></tr><tr><td>japanese_utf-8.php</td><td>97.3</td></tr><tr><td>russian_utf-8.php</td><td>69.5</td></tr><tr><td>slovenian_utf-8.php</td><td>74.8</td></tr><tr><td>spanish_utf-8.php</td><td>60.2</td></tr><tr><td>ukrainian_utf-8.php</td><td>69.5</td></tr></table>

## The rates of staticpages language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>chinese_simplified_utf-8.php</td><td>41.7</td></tr><tr><td>chinese_traditional_utf-8.php</td><td>41.7</td></tr><tr><td>czech_utf-8.php</td><td>20.3</td></tr><tr><td>danish_utf-8.php</td><td>21.3</td></tr><tr><td>dutch_utf-8.php</td><td>35.8</td></tr><tr><td>estonian_utf-8.php</td><td>68.4</td></tr><tr><td>farsi_utf-8.php</td><td>39.5</td></tr><tr><td>french_canada_utf-8.php</td><td>33.6</td></tr><tr><td>french_france_utf-8.php</td><td>72.7</td></tr><tr><td>german_formal_utf-8.php</td><td>77.0</td></tr><tr><td>german_utf-8.php</td><td>77.0</td></tr><tr><td>hebrew_utf-8.php</td><td>87.1</td></tr><tr><td>italian_utf-8.php</td><td>73.2</td></tr><tr><td>japanese_utf-8.php</td><td>98.3</td></tr><tr><td>korean_utf-8.php</td><td>41.1</td></tr><tr><td>polish_utf-8.php</td><td>38.5</td></tr><tr><td>portuguese_brazil_utf-8.php</td><td>37.4</td></tr><tr><td>slovenian_utf-8.php</td><td>78.0</td></tr><tr><td>spanish_utf-8.php</td><td>34.7</td></tr><tr><td>swedish_utf-8.php</td><td>32.0</td></tr><tr><td>turkish_utf-8.php</td><td>33.1</td></tr><tr><td>ukrainian_utf-8.php</td><td>41.1</td></tr></table>

## The rates of xmlsitemap language files translated
<table class="table is-striped is-bordered">
<tr><th>Language</th><th>Rates(%)</th></tr><tr><td>estonian_utf-8.php</td><td>57.4</td></tr><tr><td>french_france_utf-8.php</td><td>63.8</td></tr><tr><td>german_formal_utf-8.php</td><td>57.4</td></tr><tr><td>german_utf-8.php</td><td>57.4</td></tr><tr><td>hebrew_utf-8.php</td><td>65.9</td></tr><tr><td>italian_utf-8.php</td><td>59.5</td></tr><tr><td>japanese_utf-8.php</td><td>93.6</td></tr><tr><td>slovenian_utf-8.php</td><td>63.8</td></tr></table>

**Comment by eSilverStrike** [comment]
We got an updated version for the Persian Language (for Geeklog and the Core Plugins) so we should keep it as well.  See #1080

So we will keep for Geeklog and the Core plugins:

English
Japanese
French
German
Hebrew
Persian

@mystralkk  Any else?

I would like to keep Chinese and Spanish maybe but the translation % is not that high.

**Comment by mystralkk** [comment]
It would be good to keep Chinese and Spanish since a lot of people use these languages.  Similarly, Russian is a good candidate.

**Comment by eSilverStrike** [comment]
I think that is a good selection of languages plus we have a few RTL language in there with Hebrew and Persian.

English
Japanese
French France
French Canada
German
Hebrew
Persian
Chinese Simplified
Chinese Traditional
Spanish
Russia

Do we only have the 2 character sets?

$LANG_CHARSET = 'iso-8859-1';
$LANG_CHARSET = 'utf-8';

Should we drop iso-8859-1 for most or all languages?

We should also check what happens during the upgrade and also how Geeklog handles when the site and or user accounts are set to use a language that is not available any more.

Also wondering if we should add at least a minimum supported Geeklog version number variable for each language file.  This way we can warn the Admin with a message if they have a selected language that doesn't meet the min Geeklog version like we do for themes. This version number only refers to all the required language arrays are set in the file not if all the translations are complete (to prevent potential PHP errors). Figure this might be important since upgrading the old unsupported language files will be left and the Admin may not realize this. Of course this means extra work for us to update the script that synchs the language files. 

Maybe combine all Lang Settings into an array while we are at.

$LANG_SETTINGS = array(
'CHARSET' => 'iso-8859-1',
'ISO639_1' => 'fr',
'gl_version' => '2.2.2' // Minimum Geeklog version language is compatible with
);

**Comment by mystralkk** [comment]
> Should we drop iso-8859-1 for most or all languages?

In my opinion, iso-8859-1 should be dropped since UTF-8 is its superset.

> Also wondering if we should add at least a minimum supported Geeklog version number variable for each language file. This way we can warn the Admin with a message if they have a selected language that doesn't meet the min Geeklog version like we do for themes. This version number only refers to all the required language arrays are set in the file not if all the translations are complete (to prevent potential PHP errors). Figure this might be important since upgrading the old unsupported language files will be left and the Admin may not realize this. Of course this means extra work for us to update the script that synchs the language files.

Maybe combine all Lang Settings into an array while we are at.

$LANG_SETTINGS = array(
'CHARSET' => 'iso-8859-1',
'ISO639_1' => 'fr',
'gl_version' => '2.2.2' // Minimum Geeklog version language is compatible with
);

I agree.  Setting up one array containing all language information is a simple and good way.

**Comment by mystralkk** [comment]
@eSilverStrike  Is it OK now to keep:

English
Japanese
French France
French Canada
German
Hebrew
Persian
Chinese Simplified
Chinese Traditional
Spanish
Russia

and drop all the others?  Or should we wait till Geeklog 2.2.3 or later?

**Comment by eSilverStrike** [comment]
I think so. If you have the time we might as well get it done. I guess we should cleanup the other plugin language files as well.

**Comment by mystralkk** [comment]
Thanks.  Done.
