### ISSUE TITLE
Install Migration Notice - User Image not found when it actually exists in the folder

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#986]
I notice that I got a pile of migration notices in the error log like this:

`Migration notice: The image "29024.jpg" listed in the "gl_users" table could not be found in C:/wamp64/www/rtest/public_html/images/userphotos/  `

The first one in the list was missing so that notice was correct. All the other notices that followed did exist though. 

It looks like once the migration  finds 1 image missing it is reporting all images missing after it.

**Comment by mystralkk** [comment]
I changed some code to fix this issue with change set 3590352.

**Comment by eSilverStrike** [comment]
Thanks for taking a look. I had looked at the code before and didn't see the issue. I reran it and then double checked the files missing and some of them for some reason were corrupted. Copying over the files again seems to have fixed the issue.
