### ISSUE TITLE
User Settings Page Has Settings that are Not Useful and Not Used Anymore

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#988]
The User Settings page has language variables that are not used anymore by the core themes. These should be removed.

**Some User Settings  Not Needed?**
See discussion below about Block Filters, Topic and Authors Filter, and No Topic Icons. Are these even needed?

**Tidy up User Tables - Table Columns not being used in some User Tables**
Brought to our attention by OMAL: https://www.geeklog.net/forum/viewtopic.php?msg=1&showtopic=97165

The columns "emailstories" and "willing" in the gl_userprefs table do not seem to be used anymore. (didn't check other columns)

There is a config option called emailstories which appears to be used instead.

Double check if we need these to columns and remove.

Looking further into this we have a lot of user tables which I never understood... and there appears to be possibly more columns not being used like in gl_userinfo (userspace and tokens???)

gl_user
gl_userinfo - misc info about user
gl_userindex - Used for lists of topics for daily digest, topics, blocks to exclude
gl_userprefs - misc preference
gl_usercomment - used for comments

I know character limits on tables may become a factor but I think we should combine some of these tables into gl_user? @mystralkk what do you think? Or maybe not and just keep them separate?

**Comment by mystralkk** [comment]
I tried combining these five tables into one and had no errors, so it is possible to do so.

**Comment by mystralkk** [comment]
The columns "emailstories" and "willing" in the gl_userprefs table might not be used now, but this in itself is not a bug that could cause a fatal error.  So, why don't we put the milestone of this issue to 2.2.2 or later?

**Comment by eSilverStrike** [comment]
Good point, I made the changes to the issue. BTW you have Admin access to the Repository correct? If you want to make changes to issues labels, etc.. that make sense  you are more than welcome to do so.

Thinking this over I don't necessarily mind that they are in separate tables as one long table could get confusing to some. That being said if we do keep the tables we should update some of the names and move columns around. Not sure what the best approach is...

If we do keep the tables (or at least some of them) I think a table name should be changed along with some columns moved around.

gl_userindex - Rename to something like gl_userlists. This table will contain any list of items (like topics and blocks) the user has set along with any related fields.

homepage column in gl_user should be moved to gl_userinfo

maybe only combine gl_userinfo, gl_userprefs, and gl_usercomments?

Also remember (not that it affects this improvement really) that plugins can add their own user information to the User Profile in a separate table. The forum does this for example.

**Comment by mystralkk** [comment]
Certainly I have Admin access to the Repository, but I don't want to change what you have set before I discuss the issues and/or milestones with you.

**Comment by eSilverStrike** [comment]
Just wondering if we should expand on this improvement. When I was working on issue #989 I found a lot of language variables for user settings that are old and not used anymore...

Also some user settings like the Blocks Filter I don't think are needed. They are confusing to the average user and may actually break the usefulness of the site if the user disables the wrong block. 

I also wonder if settings like no topic icons and filtering of Topics and authors are needed anymore either? (or have a config option to disable user settings like this?)

I will update the issue to better reflect this discussion. 

Who ever eventually works on this issue we should confirm what we want to do.

**Comment by eSilverStrike** [comment]
Should we add a "last_IP" column to one of the tables to handle SPAM and fake user accounts better? 

Related to #1076

**Comment by mystralkk** [comment]
Well, 'userspace' column in $_TABLES['userinfo'], and 'willing' and 'emailstories' columns in $_TABLES['userprefs'] are no longer used.  Plus, 'tid', 'etids', 'aids' and 'boxes' columns in $_TABLES['userindex'], and 'noicons' column in $_TABLES['userprefs'] are unnecessary based on issue #274.  Should we remove these eight columns and combine $_TABLES['usercomment'], $_TABLES['userindex'], $_TABLES['userinfo'] and $_TABLES['userprefs'] tables into one such as $_TABLES['user_attributes']?

**Comment by eSilverStrike** [comment]
Sounds good to me.

**Comment by eSilverStrike** [comment]
I guess we should keep etids column as that is used for the Daily Digest.

**Comment by mystralkk** [comment]
Okay, I will take care to keep edits column.

**Comment by mystralkk** [comment]
Finished removing unnecessary settings and tables with change set 69320eae987525ca4de90dbd4eb10089a0642d5c
