### ISSUE TITLE
[Patches] Config: Mail Settings[auth] should be a dropdown

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#99]
**Reported by @dhaun on 15 Apr 2008 19:06**

**Description:**
Configuration > Geeklog > Site > Mail: Mail Settings[auth] currently is a text field. It should be a dropdown for true/false, though.

[Mantis Bugtracker #607](http://project.geeklog.net/tracking/view.php?id=607)

[gl_mail_settings_tweak.zip](https://github.com/Geeklog-Core/geeklog/files/90365/gl_mail_settings_tweak.zip)
[gl_mail_settings_tweak_no_context.zip](https://github.com/Geeklog-Core/geeklog/files/90366/gl_mail_settings_tweak_no_context.zip)
[mxsql_1.5.2_to_1.6.0.zip](https://github.com/Geeklog-Core/geeklog/files/90364/mxsql_1.5.2_to_1.6.0.zip)

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 23 Apr 2008 19:50**

From the code, it looks like it wasn&#039;t prepared for arrays of mixed types. An array of all texts works, as do those of all boolean (default permissions, for example).

I guess there isn&#039;t much we can do at this time - it&#039;ll probably have to wait for after the 1.5.0 release.

Workaround: Use 1 instead of true.

**Comment by mystralkk** [comment]
**Comment posted by kantai on 24 Apr 2008 12:59**

&quot;From the code, it looks like it wasn&#039;t prepared for arrays of mixed types. An array of all texts works, as do those of all boolean (default permissions, for example).&quot;

That&#039;s correct.

**Comment by mystralkk** [comment]
**Comment posted by THEMike on 14 Sep 2008 09:21**

I think this is a really simple change in the configuration variables table and it will automatically become a drop down.

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 22 Nov 2008 18:34**

Hey Mike, I don&#039;t really see that &quot;really simple change in the configuration variables table&quot;. The mail settings are an array of strings, with the exception of the &#039;auth&#039; flag. The config class can&#039;t handle such mixed array currently, from what I can see.

What am I missing?

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 10 Apr 2009 21:40**

Pushing this back into the Future

**Comment by mystralkk** [comment]
**Comment posted by dhaun on 19 Apr 2009 17:05**

Mail Settings[backend] should also be a dropdown (smtp, sendmail, mail).

**Comment by mystralkk** [comment]
**Comment posted by m_c on 19 Apr 2009 22:15**

It&#039;s an outcome of ignoring the 1NF (first normal form) in the database - that is single cell&#039;s data atomicity. All the mail settings were stuffed into one single config value and became impossible to control.

It was designed this way, because it was quick &amp; easy to pass the whole mail_settings array to the Mail::factory in COM_mail().

I&#039;ve made a fix, which...

/**
 * Converts the old mail_settings multi-setting into several atomic settings.
 *
 * It adds new mail_xxx fields to the configuration, transfers the settings
 * from the existing mail_settings field and finally deletes the mail_settings
 * entry in the config. 
 */

I&#039;ve attached the diff&#039;s in both non- and readable forms and also the migration files. Overall, those cover:

 * both MySQL and MsSQL migration files
 * config-install.php
 * english UTF-8 language file
 * all the relevant references throughout the code
 * documentation

**Comment by mystralkk** [comment]
**Comment posted by m_c on 19 Apr 2009 22:20**

Oh, by the way - the fix includes the desired dropdowns. :-)

**Comment by eSilverStrike** [comment]
Is this something we want to add to the 2.2.0 milestone? If not I think we should close the issue.

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.
