### ISSUE TITLE
Use Actual Theme Names in Configuration and User Settings

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#993]
Right now the configuration and user settings uses the directory name for theme names. We should use the name stored in them_config function (and I guess make sure it is not blank). 

For Geeklog Configuration the version number of theme along with min geeklog version should also be listed.

Geeklog Configuration for theme option should not allow a theme to be saved which is not compatible.

User Settings should not display any themes that are not deemed compatible.

**Comment by mystralkk** [comment]
Fixed with change set bcd80755e890ff4c1ff455a7a08f5a246548e74c.
