### ISSUE TITLE
Upgrade from Geeklog 2.2.0 to Geeklog 2.2.1 Fails with Key was Too Long MySQL Error

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#994]
Looking into this error...

`Fatal error: 1071: Specified key was too long; max key length is 767 bytes in .../system/databases/mysqli.class.php on line 468`

**Comment by eSilverStrike** [comment]
Okay I found the error. It is in the mysql upgrade 2.2.0 to 2.2.1 file

`$_SQL[] = "ALTER TABLE {$_TABLES['sessions']} MODIFY `sess_id` VARCHAR(250) NOT NULL default ''";`

I found this on the internet:

> 767 bytes is the stated prefix limitation for InnoDB tables in MySQL version 5.6 (and prior versions). It's 1,000 bytes long for MyISAM tables. In MySQL version 5.7 and upwards this limit has been increased to 3072 bytes. ... This is because the maximum length of a utf8mb4 character is four bytes.

Changing the varchar from 250 to 190 seems to work...

@mystralkk Obviously the install tables creation will have to be fixed. Will anything else in the new session class?

**Comment by mystralkk** [comment]
All right, I fixed the bug with change set a93f690.
