### ISSUE TITLE
Spam-X Plugin Can Error out when comparing content with banned users homepage

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#998]
Got the following error when attempting to submit a forum post or comment post on Geeklog.net after upgrading to Geeklog v2.2.1

`Tue 19 Nov 2019 13:18:25 EST - ip here - E_WARNING(2) - preg_match(): Unknown modifier 'f' @ /plugins/spamx/BannedUsers.Examine.class.php line 70  `

Seems like one of our banned users had a homepage url that looked like this:

`http://www.example.com/#f`

Here is line 70 from BannedUsers.Examine.class.php
```
            $pattern = $this->prepareRegularExpression($val);

            if (preg_match($pattern, $comment)) {
```
$pattern returns:

`#http://www.example.com/#f#i`

so it looks like the function prepareRegularExpression needs to filter $val first

**Comment by mystralkk** [comment]
Fixed with change set 7ac96a6.
